dfinity/ic-js

candid/nns_dapp.certified.idl.js
candid/nns_dapp.did
candid/nns_dapp.idl.js
scripts/nns-dapp.update.sh

Creating neurons requires access to the nns-dapp canister.  The candid files for this are not in the repo yet.
- Added a script to import the nns-dapp did file.
- Imported the did file and compiled it to generate idl.js files.
- The import script has been used - once
- Given that the did file compiles we can have some confidence that it is correct.  Also, it is essentially unmodified from the did file in the nns-dapp and that should be correct.

Add nns-dapp candid

---

package-lock.json
package.json

Publish methods to support createNeuron in the nns-dapp.
* Bumped the version number to 0.2.2
* Fixed the build, by including the proto files
No code changes.

Release 0 2 2

---

src/index.ts
src/types/ledger.ts

Export `common` types
- export `common` types
- remove re-declaration of type `BlockHeight`

feat: export common types

---

.eslintrc.json
src/governance.spec.ts
src/governance.ts
src/mocks/governance.mock.ts
tsconfig.json

`getNeuron` function.
- add and expose `getNeuron` function as implemented in project `ts`

feat: get neuron

---

README.md

Update introduction of the README file with a more generic text.

docs: update readme intro

---

src/utils/converter.utils.ts

Remove unused code.
* Remove unused converters.
No tests needed.

Fix: Remove unused converters

---

CHANGELOG.md

Init a `CHANGELOG.md` file and document the breaking changes that will be introduced with next version.

docs: init changelog and list breaking changes

---

src/canisters/governance/request.converters.ts
src/governance.spec.ts
src/governance.ts

Neuron can join community fund.
* New method `joinCommunityFund` in Governance Canister.
* New tests for `joinCommunityFund`.

L2-360: Governance Join Community Fund

---

CHANGELOG.md
src/canisters/governance/response.converters.ts
src/governance.spec.ts
src/governance.ts
src/types/governance_converters.ts

Remove "isCurrentUserController" property in "Neuron" type.
* Remove property "isCurrentUserController" in "Neuron" type.
* Clean up unnecessary parameters.
* Updated tests to new parameters.

Chore: Remove isCurrentUserController

---

src/canisters/governance/request.converters.ts
src/governance.spec.ts
src/governance.ts

Add method to split a neuron in the Governance Service.
* New method splitNeuron in Governance Service.
* Test for the new method.

Feat: Governance Split Neuron

---

src/canisters/governance/request.converters.ts

Refactor to spare duplicate code.

refactor: neuron commands

---

src/canisters/governance/payloads.ts

Fix the principal rendering in the proposal payload.
Unfortunately I didn't find the better place so this is a temporary solution.
no test update

feat: set Principal toJSON

---

src/canisters/governance/request.converters.ts
src/governance.spec.ts
src/governance.ts

Add method to merge two neurons.
* New method "mergeNeurons" in Governance Sercice.
* New test for new method.

Feat: Merge Neurons

---

src/canisters/governance/request.converters.ts
src/governance.spec.ts
src/governance.ts

Add governance services to add and remove hotkeys.
* New governance methods: addHotkey and removeHotkey.
* New tests for both new methods.

L2-357: Hotkey functionality

---

src/account_identifier.spec.ts
src/canisters/governance/request.converters.ts
src/errors/governance.errors.ts
src/governance.spec.ts
src/governance.ts
src/utils/accounts.utils.spec.ts
src/utils/accounts.utils.ts

Add method to disburse neuron.
* Add "disburse" to Governance Service.
* New accounts utils file with verifyCheckSum util.
* New Error "InvalidAccountIDError"
* Move around some tests. There were many tests inside wrong "describe".
* New test for new method on Governance Service.
* New test for new accounts utils.

L2-432: Disburse Neuron

---

src/canisters/governance/request.converters.ts
src/errors/governance.errors.ts
src/governance.spec.ts
src/governance.ts
src/utils/neurons.utils.ts
src/utils/number.utils.spec.ts
src/utils/number.utils.ts

Add method to merge maturity of a neuron.
* New method "mergeMaturity" on Governance Service.
* Test new method.

L2-372: Merge Maturity

---

src/canisters/governance/request.proto.converters.ts
src/canisters/governance/response.converters.ts
src/canisters/governance/response.proto.converters.ts
src/governance.spec.ts
src/governance.ts
src/types/governance_converters.ts

Make neuron functionality compatible with hardware wallets.
* Use the `hardwareWallet` flag in methods.
* Create a new method "XXXXHardwareWallet" for the compatible version.
* Add a new test in all the methods for hardware wallet compatibility.

L2-486: Neuron functionality compatible HW

---

src/canisters/governance/response.converters.ts

Fix the conversion from Protobuf PrincipalId to string.
* Convert PrincipalId to UIntArray and then use Principal instead of converting directly to string.
No tests. This was a typing problem.

L2-569: Fix conversion from Proto PrincipalId

---

src/governance.ts
src/index.ts
src/utils/accounts.utils.spec.ts
src/utils/accounts.utils.ts

Export util to validate account id string.
* Export "accounts.utils.ts"
Not applicable.

L2-479: Expose account utils

---

candid/payloads.did
candid/payloads.idl.js

feat: update payload version -> 60a1f53

---

HACKING.md

Missing new line in markdown list.

docs: fix formatting

---

packages/sns/src/enums/swap.enums.ts
packages/sns/src/index.ts

More candid type exposed for sns swap and define missing candid enums
- expose more types
- define enum for swap state

feat: expose more sns types for the swap

---

packages/nns/candid/genesis_token.did
packages/nns/candid/governance.certified.idl.js
packages/nns/candid/governance.d.ts
packages/nns/candid/governance.did
packages/nns/candid/governance.idl.js
packages/nns/candid/ledger.did
packages/nns/candid/sns_wasm.did
packages/nns/proto/governance.proto
packages/nns/proto/governance_pb.d.ts
packages/nns/proto/governance_pb.js
packages/nns/src/canisters/governance/response.converters.ts
packages/nns/src/governance.canister.ts
packages/nns/src/types/governance_converters.ts

Add new property in Neuron type: "spawn_at_timestamp_seconds".
* Changes in candid and derived files.
* Changes in Neuron type inside NeuronInfo.
Not applicable.

L2-843: Spawning state

---

CHANGELOG.md
packages/nns/src/canisters/governance/request.converters.ts
packages/nns/src/canisters/governance/response.converters.ts
packages/nns/src/types/governance_converters.ts

Add SetSnsTokenSwapOpenTimeWindow support
- type SetSnsTokenSwapOpenTimeWindow
- request converter function
- response converter function

feat: SetSnsTokenSwapOpenTimeWindow request/response converters

---

CHANGELOG.md
package-lock.json
package.json
packages/nns/package.json
packages/sns/package.json

docs: release v0.6.0

---

CHANGELOG.md
README.md
package-lock.json
packages/utils/LICENSE
packages/utils/README.md
packages/utils/esbuild.mjs
packages/utils/jest.config.js
packages/utils/package.json
packages/utils/src/index.ts
packages/utils/src/utils/agent.utils.ts
packages/utils/src/utils/asserts.utils.spec.ts
packages/utils/src/utils/asserts.utils.ts
packages/utils/src/utils/did.utils.spec.ts
packages/utils/src/utils/did.utils.ts
packages/utils/tsconfig.json

We begin to have utilities and constants we use everywhere. Therefore it can be useful to group these in a library.
- init new library
- move some utilities for assertion, conversion and agent

feat: new library utils

---

package-lock.json
package.json

build: bump agent-js v0.12.2

---

packages/sns/src/enums/governance.enums.ts
packages/sns/src/governance.canister.spec.ts
packages/sns/src/governance.canister.ts
packages/sns/src/index.ts
packages/sns/src/sns.wrapper.spec.ts
packages/sns/src/sns.wrapper.ts
packages/sns/src/types/governance.params.ts

Add methods to manageNeuron and abstraction to neuron permissions.
* New Governance canister methods: manageNeuron, addNeuronPermissions.
* New Swap canister method addNeuronPermissions.
* Add the enum of neuron permissions.
* Test the new methods.

L2-871: Add Hotkey Functionality

---

.github/workflows/nightly.yml
scripts/build-nightly

Publish a nightly version of `@dfinity/utils` to npm.
- update ci accordingly

build: publish a nightly version of utils

---

packages/nns/candid/sns_wasm.certified.idl.js
packages/nns/candid/sns_wasm.d.ts
packages/nns/candid/sns_wasm.did
packages/nns/candid/sns_wasm.idl.js
packages/sns/candid/icrc1_ledger.certified.idl.js
packages/sns/candid/icrc1_ledger.d.ts
packages/sns/candid/icrc1_ledger.did
packages/sns/candid/icrc1_ledger.idl.js
packages/sns/candid/sns_governance.certified.idl.js
packages/sns/candid/sns_governance.d.ts
packages/sns/candid/sns_governance.did
packages/sns/candid/sns_governance.idl.js
packages/sns/candid/sns_root.certified.idl.js
packages/sns/candid/sns_root.d.ts
packages/sns/candid/sns_root.did
packages/sns/candid/sns_root.idl.js

Update candid definitions of last commit in the IC repo.
- bump candid files and generate idl files

feat: update sns candid definitions

---

package-lock.json
package.json

Update agent-js `v1.0.0-beta.0` to fix Safari desktop login in NNS-dapp dev version.

build: agent-js beta.0 to fix safari desktop login

---

packages/sns/src/ledger.canister.spec.ts
packages/sns/src/ledger.canister.ts
packages/sns/src/sns.wrapper.spec.ts
packages/sns/src/sns.wrapper.ts
packages/sns/src/types/ledger.params.ts

User can get the balance of an account.
* Add "balance" method to Ledger Canister.
* Add "balance" method to Wrapper.
* Add "ledgerMetadata" method to Wrapper.
* New tests for all new methods.

L2-993: Sns Ledger Balance

---

CHANGELOG.md

Release a definitive version of last improvements and breaking changes to npm.

docs: release v0.7.0

---

.github/workflows/publish.yml

Publish standard version of the libraries to npm on GitHub release.
- new GitHub actions triggered on `released`

build: publish to npm on release

---

packages/nns/candid/sns_wasm.certified.idl.js
packages/nns/candid/sns_wasm.d.ts
packages/nns/candid/sns_wasm.did
packages/nns/candid/sns_wasm.idl.js
packages/sns/candid/icrc1_ledger.did
packages/sns/candid/sns_governance.certified.idl.js
packages/sns/candid/sns_governance.d.ts
packages/sns/candid/sns_governance.did
packages/sns/candid/sns_governance.idl.js
packages/sns/candid/sns_swap.certified.idl.js
packages/sns/candid/sns_swap.d.ts
packages/sns/candid/sns_swap.did
packages/sns/candid/sns_swap.idl.js
packages/sns/src/index.ts
packages/sns/src/swap.canister.spec.ts

Update `sns-js` with the last definition of the Snses canisters.
- update did files
- adapt tests for changes

feat: update sns did

---

.github/workflows/publish.yml
CHANGELOG.md
package-lock.json
packages/cmc/package.json
packages/nns/package.json
packages/sns/package.json
packages/utils/package.json

Remove manual trigger of npm official publish and bump version numbers to release.

build: release v0.8.0 and manual trigger

---

packages/nns/src/constants/constants.ts

Remove unused constant.
* Remove `TOKEN_DECIMAL_ACCURACY`
Not applicable

Chore: Remove unused constant

---

packages/sns/README.md
packages/sns/src/converters/governance.converters.ts
packages/sns/src/governance.canister.spec.ts
packages/sns/src/governance.canister.ts
packages/sns/src/sns.wrapper.spec.ts
packages/sns/src/sns.wrapper.ts

Add `sns/startDissolving`  and `sns/stopDissolving` functions
- https://dfinity.atlassian.net/browse/GIX-985
- https://dfinity.atlassian.net/browse/GIX-986
Are required for upcoming `nns-dapp` features implementation.

feat: startDissolving + stopDissolving

---

CHANGELOG.md
packages/nns/src/canisters/governance/request.proto.converters.ts
packages/nns/src/governance.canister.spec.ts
packages/nns/src/governance.canister.ts

Support for Join Community Fund for HW neurons.
* Use proto when joining a neuron if HW.
* Test new functionality

Feat: Support Join Community Fund HW

---

package-lock.json
package.json

Bump agent-js v0.14.0.
Release notes: https://github.com/dfinity/agent-js/releases/tag/v0.14.0

build: bump agent-js v0.14.0

---

packages/nns/src/enums/governance.enums.ts

https://dfinity.atlassian.net/browse/GIX-1068
Add new `topic` and `nnsFunction` types.
- `Topic`  enum
- `NnsFunction` enum (not yet in use)

Add new replica related types (topics and proposal)

---

packages/nns/src/enums/governance.enums.ts

Add `UpdateSnsWasmSnsSubnetIds` nnsFunction support.
https://dfinity.atlassian.net/browse/GIX-1082
[related `ic` update](https://gitlab.com/dfinity-lab/public/ic/-/merge_requests/8107/diffs)
- extend the NnsFunction enum
- remove not yet used `RetireReplicaVersion` item

feat: add  RetireReplicaVersion UpdateSnsWasmSnsSubnetIds

---

HACKING.md

Improve the section on developing with local changes and nns-dapp.
* Changes in HACKING.md
Not applicable

Chore: Improve Hacking docs

---

packages/cmc/candid/cmc.did
packages/nns/candid/genesis_token.did
packages/nns/candid/governance.did
packages/nns/candid/ledger.did
packages/nns/candid/sns_wasm.certified.idl.js
packages/nns/candid/sns_wasm.d.ts
packages/nns/candid/sns_wasm.did
packages/nns/candid/sns_wasm.idl.js
packages/nns/src/mocks/sns_wasm.mock.ts
packages/sns/candid/icrc1_ledger.did
packages/sns/candid/sns_governance.certified.idl.js
packages/sns/candid/sns_governance.d.ts
packages/sns/candid/sns_governance.did
packages/sns/candid/sns_governance.idl.js
packages/sns/candid/sns_index.certified.idl.js
packages/sns/candid/sns_index.d.ts
packages/sns/candid/sns_index.did
packages/sns/candid/sns_index.idl.js
packages/sns/candid/sns_root.did
packages/sns/candid/sns_swap.certified.idl.js
packages/sns/candid/sns_swap.d.ts
packages/sns/candid/sns_swap.did
packages/sns/candid/sns_swap.idl.js

Upgrade candid files to commit that will be released Tuesday 1st of November.
* Update candid files and related.
* Change sns-wasm mock to adapt to new response type.

GIX-1097: Update candid canisters

---

packages/utils/README.md
packages/utils/src/index.ts
packages/utils/src/utils/version.utils.spec.ts
packages/utils/src/utils/version.utils.ts

We also need smallerVersion in the hardware-wallet-cli.
* Add new util smallerVersion in utils package.
* Test the new util.

Chore: New util smallerVersion

---

packages/sns/README.md
packages/sns/src/converters/governance.converters.ts
packages/sns/src/governance.canister.spec.ts
packages/sns/src/governance.canister.ts
packages/sns/src/sns.wrapper.spec.ts
packages/sns/src/sns.wrapper.ts
packages/sns/src/types/governance.params.ts

Extend sns wrapper with dissolve delay management features;
Part of https://dfinity.atlassian.net/browse/GIX-1107
- setDissolveTimestamp
- increaseDissolveDelay
- extend governance.canister spec
- sns.wrapper spec

feat: increaseDissolveDelay and setDissolveTimestamp

---

package-lock.json
packages/sns/README.md
packages/sns/package.json
packages/sns/src/constants/governance.constants.ts
packages/sns/src/converters/governance.converters.ts
packages/sns/src/sns.wrapper.spec.ts
packages/sns/src/sns.wrapper.ts
packages/sns/src/types/governance.params.ts
packages/sns/src/utils/governance.utils.spec.ts
packages/sns/src/utils/governance.utils.ts
packages/utils/README.md
packages/utils/src/utils/arrays.utils.spec.ts
packages/utils/src/utils/arrays.utils.ts

Add functionality to stake an SNS neuron.
* Add public methods stakeNeuron and getNextNeuronAccount to SnsWrapper.
* Add governance util getNeuronSubaccount.
* New array utils "bigIntToUint8Array" and "numberToUint8Array".
* New tests for public methods in SnsWrapper.
* New tests for new utils.

GIX-1115: Stake SNS Neuron

---

packages/cmc/candid/cmc.did
packages/nns/candid/genesis_token.did
packages/nns/candid/governance.certified.idl.js
packages/nns/candid/governance.d.ts
packages/nns/candid/governance.did
packages/nns/candid/governance.idl.js
packages/nns/candid/ledger.did
packages/nns/candid/sns_wasm.did
packages/sns/candid/icrc1_ledger.did
packages/sns/candid/sns_governance.certified.idl.js
packages/sns/candid/sns_governance.d.ts
packages/sns/candid/sns_governance.did
packages/sns/candid/sns_governance.idl.js
packages/sns/candid/sns_index.did
packages/sns/candid/sns_root.did
packages/sns/candid/sns_swap.did

Update candid files for commit pushed in SNS-1 canisters
* Update candid and related files.
Not applicable

GIX-1138: Update Candid for SNS-1

---

packages/sns/README.md
packages/sns/src/converters/governance.converters.ts
packages/sns/src/enums/governance.enums.ts
packages/sns/src/governance.canister.spec.ts
packages/sns/src/governance.canister.ts
packages/sns/src/sns.wrapper.spec.ts
packages/sns/src/sns.wrapper.ts
packages/sns/src/types/governance.params.ts

Implement stake and auto stake maturity for Sns neuron.

feat: sns neuron stake maturity

---

CHANGELOG.md

Document changes to release `v0.10.0`.

docs: release v0.10.0

---

packages/sns/README.md
packages/sns/src/governance.canister.spec.ts
packages/sns/src/governance.canister.ts
packages/sns/src/mocks/governance.mock.ts
packages/sns/src/sns.wrapper.spec.ts
packages/sns/src/sns.wrapper.ts
packages/sns/src/types/governance.params.ts

getProposal wrapper function for proposal detail page.
- add `getProposal` function
- wrapper / `getProposal`
- government canister / `getProposal`

Gix 1219 fetch sns proposal

---

CHANGELOG.md

Docs changelog to release `v0.11.0`

docs: release changelog v0.11.0

---

CHANGELOG.md
package-lock.json
packages/cmc/package.json
packages/nns/package.json
packages/sns/package.json
packages/utils/package.json

Init next version `v0.12.0`. To be merged once #259 released.
- bump semver

build: init next version v0.12.0

---

scripts/build-next

Next dependencies should be set for ledger.

build: fix next dependencies

---

CHANGELOG.md
package-lock.json
package.json
packages/cmc/package.json
packages/ledger/package.json
packages/nns/package.json
packages/sns/package.json
packages/utils/package.json

Previous release fails in the CI. This PR fixes the release numbers.

build: clean release v0.12.1

---

CHANGELOG.md

docs: prepare release v0.13.0

---

CHANGELOG.md
package-lock.json
package.json
packages/cmc/package.json
packages/ledger/package.json
packages/nns/package.json
packages/sns/package.json
packages/utils/package.json

Bump version number for next release.

build: open next release v0.14.0

---

CHANGELOG.md
package-lock.json
packages/cmc/package.json

Utils is a peer dependencies of Cmc.

build: fix cmc utils peer dependencies

---

ADMIN.md

Summarize how to initialize a new `ic-js` library.

docs: create a new ic-js library

---

CHANGELOG.md
package-lock.json
package.json

- bump agent-js `v0.15.3`
- bump all dev dependencies

build: bump agent-js v0.15.3

---

packages/sns/src/sns.wrapper.ts
packages/sns/src/swap.canister.ts

Update the types to cover all the response cases.
- `fromDefinedNullable` -> `fromNullable`

fix: get open ticket types

---

HACKING.md
package-lock.json
packages/ckbtc/package.json
packages/cmc/package.json
packages/ledger/package.json
packages/nns/package.json
packages/sns/package.json
packages/utils/package.json

Bump last version of agent-js
As in `HACKING.md` (actualized in this PR):
> npm rm @dfinity/agent @dfinity/candid @dfinity/principal --workspaces
> npm i @dfinity/agent @dfinity/candid @dfinity/principal --save-peer --workspaces

build: bump agent-js v0.15.4

---

packages/nns/src/enums/governance.enums.ts

Extend nnsFuncton enum to add new payload `UpdateElectedReplicaVersions` support.
https://dfinity.atlassian.net/browse/GIX-1372

Extend nnsFuncton enum with UpdateElectedReplicaVersions

---

packages/ckbtc/README.md
packages/ckbtc/candid/minter.certified.idl.js
packages/ckbtc/candid/minter.d.ts
packages/ckbtc/candid/minter.did
packages/ckbtc/candid/minter.idl.js
packages/ckbtc/src/index.ts
packages/ckbtc/src/minter.canister.spec.ts
packages/ckbtc/src/minter.canister.ts
packages/ckbtc/src/types/minter.responses.ts

There was a breaking changes in the ckBTC minter declaration of `update_balance` which we need to include in next version.
- update candid and adapt accordingly

feat: update ckBTC update_balance declaration

---

packages/sns/src/index.ts

Export SNS Swap ticket type.
* Add ticket type to index file for sns-js.
Not applicable.

Chore: Export sns swap ticket type

---

packages/nns/src/index.ts

Expose the return type of getLatestRewardEvent.
* Add RewardEvent to the exposed data in nns-js
Not applicable

Chore: Expose Reward Event

---

CHANGELOG.md
package-lock.json
package.json
packages/ledger/src/utils/ledger.utils.ts
packages/nns/package.json

Fix imports and prepare version to release v0.15.1.

fix: absolute utils import in ledger library

---

packages/cmc/candid/cmc.did
packages/nns/candid/genesis_token.did
packages/nns/candid/governance.certified.idl.js
packages/nns/candid/governance.d.ts
packages/nns/candid/governance.did
packages/nns/candid/governance.idl.js
packages/nns/candid/ledger.did
packages/nns/candid/sns_wasm.did
packages/nns/src/canisters/governance/request.converters.ts
packages/nns/src/canisters/governance/response.converters.ts
packages/nns/src/governance.canister.spec.ts
packages/nns/src/types/governance_converters.ts

Governance is adding a new Action variant.
This PR: Updates candid file for NNS canisters.
* Update candid files and related.
* Add the new variant in the Action converters, yet, not converting it. This will be done in another PR. This is ok because this proposal won't be used in a month or so.
I tested that this version works against an older version of the Governance canister.

Feat: Update candid file for NNS

---

packages/sns/src/index.ts

Expose more Sns types to improve typing declaration when the library is being used by consumers.

feat: export more Sns types

---

packages/sns/src/index.ts

Export one more type used in NNS-dapp tests.

feat: export one more Sns types

---

CHANGELOG.md
package-lock.json
package.json
packages/ckbtc/package.json
packages/cmc/package.json
packages/ledger/package.json
packages/nns-proto/package.json
packages/nns/package.json
packages/sns/package.json
packages/utils/package.json

Open next version to integrate the libs in NNS-dapp.

build: open next version

---

packages/nns/src/governance.canister.ts

Cleaning up some code.
In `packages/nns/src/governance.canister.ts`:
1. Use `isNullish` instead of `=== undefined`
2. Use `nonNullish` instead of `!== undefined`
3. Use `fromNullable` instead of `[0]`
`npm run test --workspace=packages/nns`

Use isNullish and fromNullable in governance.canister.ts

---

.github/workflows/nightly.yml
.github/workflows/publish.yml
CHANGELOG.md

Let's release new versions and publish `ic-management` at the same time.
- update CHANGELOG for release
- add new package to CI jobs

build: release v0.17.0

---

packages/ic-management/src/index.ts

Expose canister ic-mgmt options for consumers.

feat: export ic-mgmt options type

---

CHANGELOG.md
package-lock.json
packages/ckbtc/package.json
packages/cmc/package.json
packages/ic-management/README.md
packages/ic-management/package.json
packages/ledger/package.json
packages/nns-proto/package.json
packages/nns/package.json
packages/sns/package.json
packages/utils/package.json
scripts/docs.js

Open next version to build and release next with next version numbers.
Reactivate the publish of all libs in the CI as it was temporary commented in #363.

build: bump next and reactivate publish for all libs

---

packages/nns/src/canisters/governance/response.converters.ts

Fix wrong import `"@dfinity/utils/src"`
- `@dfinity/utils/src` -> `@dfinity/utils`

fix: import

---

CHANGELOG.md
package-lock.json
package.json
packages/ic-management/README.md

chore: release v0.0.18

---

CHANGELOG.md
package-lock.json
package.json
packages/ckbtc/package.json
packages/cmc/package.json
packages/ic-management/README.md
packages/ic-management/package.json
packages/ledger/package.json
packages/nns-proto/package.json
packages/nns/package.json
packages/sns/package.json
packages/utils/package.json

Bump next after release v0.0.18.

chore: open next version

---

packages/ledger/candid/icrc1_ledger.certified.idl.js
packages/ledger/candid/icrc1_ledger.d.ts
packages/ledger/candid/icrc1_ledger.did
packages/ledger/candid/icrc1_ledger.idl.js
packages/ledger/src/mocks/ledger.mock.ts

Update the ICRC ledger did file with last version.

feat: update ICRC ledger did file

---

packages/ledger/README.md
packages/ledger/src/utils/payment.utils.ts

Add a mention about the fact that the payment function is a draft.

docs: ICRC-22 draft mention

---

packages/nns/candid/governance.certified.idl.js
packages/nns/candid/governance.d.ts
packages/nns/candid/governance.did
packages/nns/candid/governance.idl.js
packages/nns/candid/sns_wasm.certified.idl.js
packages/nns/candid/sns_wasm.d.ts
packages/nns/candid/sns_wasm.did
packages/nns/candid/sns_wasm.idl.js
packages/nns/src/canisters/governance/request.converters.ts
packages/nns/src/canisters/governance/response.converters.ts
packages/nns/src/types/governance_converters.ts

Rename a field in 1-proposal types.
- neuronsFundInvestment -> neuronsFundInvestmentIcp
Locally after creation an sns proposal

1-proposal-related-candid-update

---

packages/sns/candid/sns_governance.certified.idl.js
packages/sns/candid/sns_governance.d.ts
packages/sns/candid/sns_governance.did
packages/sns/candid/sns_governance.idl.js
packages/sns/candid/sns_root.certified.idl.js
packages/sns/candid/sns_root.d.ts
packages/sns/candid/sns_root.did
packages/sns/candid/sns_root.idl.js
packages/sns/candid/sns_swap.certified.idl.js
packages/sns/candid/sns_swap.d.ts
packages/sns/candid/sns_swap.did
packages/sns/candid/sns_swap.idl.js

Update `/sns` candid types to latest `ic/master` (27ee689d96352e941dfc7ef1909b4044047a991a) to get the latest fields.
- `import-candid`
- `compile-idl-js`
Build and tested w/ latest nns-dapp. No changes found.

Update sns candid types

---

CHANGELOG.md
package-lock.json
package.json
packages/ckbtc/package.json
packages/cmc/package.json
packages/ic-management/package.json
packages/ledger/package.json
packages/nns-proto/package.json
packages/nns/package.json
packages/sns/package.json
packages/utils/package.json

build: open next

---

HACKING.md
packages/sns/README.md
packages/sns/src/index.ts
packages/sns/src/sns.wrapper.spec.ts
packages/sns/src/sns.wrapper.ts
packages/sns/src/swap.canister.spec.ts
packages/sns/src/swap.canister.ts

Expose swap canister endpoint `get_auto_finalization_status`.
* Add method getFinalizationStatus in swap canister.
* Add method getFinalizationStatus in wrapper.
* Test new swap canister method.
* Test new wrapper method.
* Fix some prettier commas.

GIX-1841: Add getFinalizationStatus endpoint

---

package-lock.json
packages/ckbtc/package.json
packages/cmc/package.json
packages/ic-management/package.json
packages/ledger/package.json
packages/nns/package.json
packages/sns/package.json
packages/utils/package.json

Upgrade agent-js to populate fix for a proper evaluation of the subdomain when used in the browser without `host`.
https://github.com/dfinity/agent-js/releases/tag/v0.19.2

build: upgrade agent-js v0.19.2

---

package-lock.json
packages/ic-management/package.json

Remove unused dependencies indicated in `package.json` of `@dfinity/ic-management`.

build: remove unused dependencies

---

CHANGELOG.md
packages/ledger/candid/icrc1_index.certified.idl.js
packages/ledger/candid/icrc1_index.d.ts
packages/ledger/candid/icrc1_index.did
packages/ledger/candid/icrc1_index.idl.js
packages/ledger/src/index.canister.spec.ts

Update icrc1 index did files.
The transaction returned by the canisters contain more information.

build: update icrc1 index did files in ledger

---

CHANGELOG.md
package.json
packages/cmc/candid/cmc.certified.idl.js
packages/cmc/candid/cmc.d.ts
packages/cmc/candid/cmc.did
packages/cmc/candid/cmc.idl.js

This PR just bump the did files in Cmc and does not implement new features. Maintaince PR to keep it up-to-date.

build: bump did files in cmc

---

scripts/build-next

Fix https://github.com/dfinity/ic-js/actions/runs/6323493751/job/17171159406

build: fix next CI job that tries to bump a library we have not published yet

---

README.md

Quick review on main README to integrate ledger-icrc/icp and add some badges.

docs: review main README

---

.github/pull_request_template.md

Remind the devs to keep the changelog up to date in every PR.
* Change the PR template.
Not necessary. Only doc changes.

Chore: Update PR template

---

packages/ledger-icrc/README.md

Fix a typo in README which is the root cause that leads to the issue faced in #462 question.

docs: fix typo in ledger-icrc README

---

CHANGELOG.md
package-lock.json
package.json
packages/ckbtc/package.json
packages/ledger-icp/package.json
packages/ledger-icrc/package.json
packages/nns/package.json
packages/sns/package.json
packages/utils/package.json

Review changelog and semver to create a new release.

build: docs and semver for release

---

packages/sns/candid/sns_governance.certified.idl.js
packages/sns/candid/sns_governance.d.ts
packages/sns/candid/sns_governance.did
packages/sns/candid/sns_governance.idl.js
packages/sns/candid/sns_governance_test.certified.idl.js
packages/sns/candid/sns_governance_test.d.ts
packages/sns/candid/sns_governance_test.did
packages/sns/candid/sns_governance_test.idl.js

Upgrade sns governance canister types
- `import-candid` & `compile-idl-js`
Still works.

Upgrade sns governance candids

---

packages/nns/README.md

I followed the README to setup a sample script and I have to say that an example of local usages would have been useful. 
Therefore providing this PR to add it.

docs: governance canister local snippet

---

packages/nns/README.md
packages/sns/src/index.ts

Expose `SnsPercentage` to be used in `nns-dapp`
- add export
- npm run format
Works
Not necessary

expose SnsPercentage

---

packages/ckbtc/src/index.ts

It's convenient to be able to refer to this type.
`export RetrieveBtcStatusV2`
Used in an nns-dapp branch.
not necessary

Export RetrieveBtcStatusV2

---

CHANGELOG.md
package-lock.json
package.json
packages/ckbtc/package.json
packages/cmc/package.json
packages/ic-management/package.json
packages/ledger-icp/package.json
packages/ledger-icrc/package.json
packages/nns/package.json
packages/sns/package.json
packages/utils/package.json

Prepare release. Bump version and doc changelog.

build: bump version and CHANGELOG for release

---

.github/workflows/update-ic.yml

Improve the PR description of the workflow that updates the candid interfaces.
* Change in `/workflows/update-ic.yml`.
Not necessary.
Not necessary.

Chore: Improve text

---

packages/cketh/README.md
packages/cketh/src/index.ts
packages/cketh/src/minter.canister.spec.ts
packages/cketh/src/minter.canister.ts

Expose ckETH `retrieve_eth_status`. 
- nothing particular, just expose the function and calls it

feat: ckETH retrieve_eth_status

---

packages/ckbtc/README.md
packages/cketh/README.md
packages/ledger-icp/README.md
packages/sns/README.md

A dev reported an "bug" on the [forum](https://forum.dfinity.org/t/error-importing-ckbtccanister-from-dfnity-ckbtc-package/27881/2?u=peterparker) this weekend which actually was an issue due to a typo in a README of ckBTC-js.
This PR correct the typo, another similar typo and improve few other code snippets to avoid misunderstandings.

docs: snippets typos

---

packages/ic-management/README.md
packages/ic-management/candid/ic-management.certified.idl.js
packages/ic-management/candid/ic-management.d.ts
packages/ic-management/candid/ic-management.did
packages/ic-management/candid/ic-management.idl.js

Update ic-management did files.
Hard to tell what changed as the all format of the did file was modified in this [PR](https://github.com/dfinity/interface-spec/pull/275). I commented the PR to require consistency in the format for the future.

feat: update ic-mgmt did types

---

packages/ckbtc/candid/minter.did
packages/cmc/candid/cmc.did
packages/ledger-icrc/candid/icrc_index-ng.did
packages/ledger-icrc/candid/icrc_index.did
packages/ledger-icrc/candid/icrc_ledger.did

Update those did files provided by #574 for which only the reference in comments was modified.

build: update did comments

---

package-lock.json
package.json
packages/cketh/README.md
packages/ic-management/README.md
packages/sns/README.md
packages/utils/README.md

Bump dev dependencies with latest versions including last version of TypeScript.
- bump libs
- docs gets updated because tsdoc-documentation can notice more fields given the TypeScript update (I guess, did not debug)

build: bump dev dependencies

---

packages/ledger-icp/src/ledger.canister.spec.ts

Address comment from https://github.com/dfinity/ic-js/pull/594 which accidentally auto-merged even though there was an unresolved comment.
Change test description.
only test
not necessary

NNS1-2886: Fix test description

---

packages/ckbtc/candid/minter.d.ts
packages/cketh/candid/minter.d.ts
packages/cmc/candid/cmc.d.ts
packages/ic-management/candid/ic-management.d.ts
packages/ledger-icp/candid/index.d.ts
packages/ledger-icp/candid/ledger.d.ts
packages/ledger-icrc/candid/icrc_index-ng.d.ts
packages/ledger-icrc/candid/icrc_index.d.ts
packages/ledger-icrc/candid/icrc_ledger.d.ts
packages/nns/candid/genesis_token.d.ts
packages/nns/candid/governance.d.ts
packages/nns/candid/governance_test.d.ts
packages/nns/candid/sns_wasm.d.ts
packages/sns/candid/sns_governance.d.ts
packages/sns/candid/sns_governance_test.d.ts
packages/sns/candid/sns_root.d.ts
packages/sns/candid/sns_swap.d.ts

Didc was bumped to v0.3.7 in PR #603. This PR generates the TS/JS files with it.
- new services' interfaces generated by v0.3.7

build: generate did files with didc v0.3.7

---

package.json
packages/sns/candid/sns_governance.certified.idl.js
packages/sns/candid/sns_governance.d.ts
packages/sns/candid/sns_governance.did
packages/sns/candid/sns_governance.idl.js
packages/sns/candid/sns_governance_test.certified.idl.js
packages/sns/candid/sns_governance_test.d.ts
packages/sns/candid/sns_governance_test.did
packages/sns/candid/sns_governance_test.idl.js
packages/sns/candid/sns_root.certified.idl.js
packages/sns/candid/sns_root.d.ts
packages/sns/candid/sns_root.did
packages/sns/candid/sns_root.idl.js
packages/sns/candid/sns_swap.did

Automatic updates of all candid are blocked by breaking changes.
See https://github.com/dfinity/ic-js/pull/606
But there are no breaking changes in the sns package, so let's keep that up to date.
Ran:
1. `scripts/import-candid ../../ic`
2. `scripts/compile-idl-js`
3. `git checkout -- packages/{ckbtc,cketh,cmc,ledger-icp,ledger-icrc,nns}`
Bumped size limit in `package.json`.
Not tested.
not necessary

Update Candid files for sns package

---

CHANGELOG.md
packages/cketh/README.md
packages/cketh/src/errors/minter.errors.ts
packages/cketh/src/minter.canister.spec.ts
packages/cketh/src/minter.canister.ts
packages/cketh/src/mocks/minter.mock.ts

Provide support to withdraw ckErc20 -> Erc20.
- Expose new feature `withdrawErc20` (similar to existing `withdrawEth`).
- Rework ckEth minter errors parsing to bubble the details instead of parsing it to string
- Implement errors for new withdrawal type

feat: withdraw Erc20

---

packages/nns/src/enums/governance.enums.ts

Add new proposal types to the `NnsFunction` enum:
- `DeployGuestosToSomeApiBoundaryNodes`
- `DeployGuestosToAllUnassignedNodes`
- `UpdateSshReadOnlyAccessForAllUnassignedNodes`
- `ReviseElectedHostosVersions`
- `DeployHostosToSomeNodes`
- Update `NnsFunction` enum
Pass.
Not yet

Add new proposal types to the NnsFunction enum

---

CHANGELOG.md
package-lock.json
packages/ckbtc/package.json
packages/cketh/package.json
packages/cmc/package.json
packages/ic-management/package.json
packages/ledger-icp/package.json
packages/ledger-icrc/package.json
packages/nns/package.json
packages/sns/package.json
packages/utils/README.md
packages/utils/package.json
packages/utils/src/utils/agent.utils.ts

Bump agent-js v1.3.0 and remove `retryTimes` default value to 10 given that the issue is fixed in agent-js.

build: bump agent-js v1.3.0 and remove retryTimes default 10

---

packages/cketh/candid/minter.certified.idl.js
packages/cketh/candid/minter.d.ts
packages/cketh/candid/minter.did
packages/cketh/candid/minter.idl.js
packages/cketh/src/minter.canister.spec.ts

Update ckETH Candid types as proposed by PR #623 and add new optional minter info fields to test mock data.
- Copy Candid updates from PR #623
- Add last scraped block numbers fields to mock data

feat: update ckETH most recent Candid types

---

packages/ckbtc/candid/minter.did
packages/cketh/candid/minter.did
packages/cketh/candid/orchestrator.did
packages/cmc/candid/cmc.did
packages/ledger-icp/candid/index.did
packages/ledger-icp/candid/ledger.certified.idl.js
packages/ledger-icp/candid/ledger.d.ts
packages/ledger-icp/candid/ledger.did
packages/ledger-icp/candid/ledger.idl.js
packages/ledger-icrc/candid/icrc_index-ng.did
packages/ledger-icrc/candid/icrc_index.did
packages/ledger-icrc/candid/icrc_ledger.did
packages/nns/candid/genesis_token.did
packages/nns/candid/governance.did
packages/nns/candid/governance_test.did
packages/nns/candid/sns_wasm.did
packages/sns/candid/sns_governance.did
packages/sns/candid/sns_governance_test.did
packages/sns/candid/sns_root.did
packages/sns/candid/sns_swap.did

The canisters APIs have been updated.
* Updated the candid interface files for the canisters used in this library.
* Updated the javascript bindings for the latest candid interfaces.

Update Candid Files

---

packages/ckbtc/README.md
packages/ckbtc/candid/bitcoin.certified.idl.d.ts
packages/ckbtc/candid/bitcoin.certified.idl.js
packages/ckbtc/candid/bitcoin.d.ts
packages/ckbtc/candid/bitcoin.did
packages/ckbtc/candid/bitcoin.idl.d.ts
packages/ckbtc/candid/bitcoin.idl.js
packages/ckbtc/src/bitcoin.canister.ts
packages/ckbtc/src/index.ts
packages/ckbtc/src/minter.canister.ts
packages/ckbtc/src/types/canister.options.ts
packages/ic-management/candid/ic-management.did
scripts/docs.js
scripts/import-candid

Init Bitcoin canister for library `@dfinity/ckbtc`.
https://github.com/dfinity/bitcoin-canister
- Set-up did files, empty canister JavaScript and docs

feat: init bitcoin canister

---

CHANGELOG.md
package-lock.json
package.json
packages/ckbtc/package.json
packages/cketh/package.json
packages/cmc/package.json
packages/ic-management/package.json
packages/ledger-icp/package.json
packages/ledger-icrc/package.json
packages/nns/package.json
packages/sns/package.json

I think, we  ave got some material which is worth releasing in a version.
- Bump version for next release.

chore: bump next version and prepare release

---

CHANGELOG.md
packages/nns/src/enums/governance.enums.ts

New topics are added in NNS Governance and they need to be supported in ic-js. Related dfinity/ic changes: https://github.com/dfinity/ic/commit/891c74208b7761c69413855dafd28198bc7294a0
Support NNS Governance topics ProtocolCanisterManagement and ServiceNervousSystemManagement
N/A

Support NNS Governance topics ProtocolCanisterManagement and ServiceNervousSystemManagement

---

CHANGELOG.md
packages/nns/candid/genesis_token.did
packages/nns/candid/governance.certified.idl.js
packages/nns/candid/governance.d.ts
packages/nns/candid/governance.did
packages/nns/candid/governance.idl.js
packages/nns/candid/governance_test.certified.idl.js
packages/nns/candid/governance_test.d.ts
packages/nns/candid/governance_test.did
packages/nns/candid/governance_test.idl.js
packages/nns/candid/sns_wasm.did
packages/nns/src/canisters/governance/request.converters.spec.ts
packages/nns/src/canisters/governance/request.converters.ts
packages/nns/src/canisters/governance/response.converters.ts
packages/nns/src/governance.canister.spec.ts
packages/nns/src/types/governance_converters.ts

https://github.com/dfinity/ic-js/pull/676 tried to do this automatically but there were test failures.
1. Ran `scripts/import-candid ../../ic` and `scripts/compile-idl-js`.
2. Reverted everything outside nns package: `git checkout packages/{ckbtc,cketh,cmc,ledger-icp,ledger-icrc,sns}`
3. Added conversion to and from raw action for `InstallCode` action.
Unit tests added for conversion in both directions.

Update candid for nns package

---

packages/ckbtc/candid/minter.did
packages/cketh/candid/minter.certified.idl.js
packages/cketh/candid/minter.d.ts
packages/cketh/candid/minter.did
packages/cketh/candid/minter.idl.js
packages/cketh/candid/orchestrator.did
packages/cketh/src/minter.canister.spec.ts
packages/cmc/candid/cmc.did
packages/ledger-icp/candid/index.did
packages/ledger-icp/candid/ledger.did
packages/ledger-icrc/candid/icrc_index-ng.did
packages/ledger-icrc/candid/icrc_index.did
packages/ledger-icrc/candid/icrc_ledger.did
packages/nns/candid/genesis_token.did
packages/nns/candid/governance.did
packages/nns/candid/governance_test.did
packages/nns/candid/sns_wasm.did
packages/sns/candid/sns_governance.certified.idl.js
packages/sns/candid/sns_governance.d.ts
packages/sns/candid/sns_governance.did
packages/sns/candid/sns_governance.idl.js
packages/sns/candid/sns_governance_test.certified.idl.js
packages/sns/candid/sns_governance_test.d.ts
packages/sns/candid/sns_governance_test.did
packages/sns/candid/sns_governance_test.idl.js
packages/sns/candid/sns_root.did
packages/sns/candid/sns_swap.did

The canisters APIs have been updated.
* Updated the candid interface files for the canisters used in this library.
* Updated the javascript bindings for the latest candid interfaces.

Update Candid Files (with manual fix)

---

CHANGELOG.md
LICENSE
packages/ckbtc/LICENSE
packages/cketh/LICENSE
packages/cmc/LICENSE
packages/ic-management/LICENSE
packages/ledger-icp/LICENSE
packages/ledger-icrc/LICENSE
packages/nns-proto/LICENSE
packages/nns/LICENSE
packages/sns/LICENSE
packages/utils/LICENSE

Rename org in licenses.
- Buld rename DFINITY LLC to DFINITY Stiftung

docs: rename DFINITY LLC to DFINITY Stiftung in liences

---

CHANGELOG.md
packages/cketh/candid/minter.certified.idl.js
packages/cketh/candid/minter.d.ts
packages/cketh/candid/minter.did
packages/cketh/candid/minter.idl.js
packages/cketh/candid/orchestrator.did
packages/cketh/src/minter.canister.spec.ts

Update the did files of ckETH as provided by the weekly job #783 and add the new minter info fields to the mock data for test purpose.

feat: update ckETH minter info did fields

---

.github/workflows/checks.yml
.github/workflows/docs.yml
.github/workflows/update-ic.yml

We are replacing PAT generated by service accounts with GitHub apps.
Full context here: https://dfinity.slack.com/archives/CH4CADCJX/p1733844276935979
Replacing how a token is generated.

chore(IDX): replace PAT with GitHub App

---

CHANGELOG.md
packages/ledger-icp/src/index.ts

Few types exposed which can be useful with the OISY wallet signer.

feat: expose few additional did types  in ledger-icp

---

README.md

List the new library on the "homepage" of the repo.

docs: list zod-schemas on main README

---

CHANGELOG.md
package-lock.json
package.json
packages/ckbtc/package.json
packages/cketh/package.json
packages/cmc/package.json
packages/ic-management/package.json
packages/ledger-icp/package.json
packages/ledger-icrc/package.json
packages/nns/package.json
packages/sns/package.json
packages/utils/package.json

We want to release the lastest change and particularly the patch in utils.
- Bump versions
- Provide release notes in CHANGELOG

chore: prepare new release

---

packages/utils/README.md
packages/utils/src/utils/json.utils.ts

Since I'm already there, I propose to refresh the jsdoc of JSON replacer and reviver.
- Update jsdoc with few additional details and different wording

docs: review json replacer and reviver jsDocs

---

CHANGELOG.md
packages/ledger-icrc/README.md
packages/ledger-icrc/src/ledger.canister.spec.ts
packages/ledger-icrc/src/ledger.canister.ts
packages/ledger-icrc/src/types/ledger.params.ts

We would like to expose method `get_blocks` in class `IcrcLedgerCanister`.
Included method `getBlocks` in `IcrcLedgerCanister`.
Included test for new method.

feat: add method get_blocks to class IcrcLedgerCanister

---

CHANGELOG.md
packages/utils/README.md
packages/utils/src/utils/crypto.utils.spec.ts
packages/utils/src/utils/crypto.utils.ts

For OISY's [PS](https://github.com/dfinity/oisy-wallet/pull/5886#pullrequestreview-2783465116) we need a hash from a string and not an object. That's why this PR extract the generate of the hash for a text value to a standalone function.
- Extract function.
- No logic change.

feat: extract generate hash text

---

CHANGELOG.md
package-lock.json
package.json
packages/ckbtc/package.json
packages/cketh/package.json
packages/cmc/package.json
packages/ic-management/package.json
packages/ledger-icp/package.json
packages/ledger-icrc/package.json
packages/nns/package.json
packages/sns/package.json
packages/utils/package.json

I want to release a version to publish the new utilities.
- Tag version in all package json
- Update CHANGELOG accordingly

chore: prepare release v69

---

eslint.config.mjs
packages/ckbtc/src/minter.canister.ts
packages/ic-management/src/ic-management.canister.spec.ts
packages/ledger-icp/src/ledger.canister.spec.ts

chore: eslint no-import-type-side-effects on

---

eslint.config.mjs
packages/utils/README.md
packages/utils/src/utils/debounce.utils.ts

- Remove exception and add an exception in the single occurence of the rule.

chore: eslint no unsafe function type exception

---

eslint.config.mjs
packages/nns/src/errors/governance.errors.ts

chore: eslint prefer-template on

---

eslint.config.mjs
packages/sns/src/governance.canister.spec.ts

chore: eslint no-inferrable-types on

---

eslint.config.mjs

- Remove exception (no code changes).

chore: remove exception eslint consistent-type-imports

---

eslint.config.mjs
packages/ic-management/src/utils/transform.utils.ts
packages/nns/src/canisters/governance/request.converters.ts
packages/nns/src/canisters/governance/response.converters.ts
packages/utils/README.md
packages/utils/src/parser/token.ts
packages/utils/src/utils/arrays.utils.ts

chore: eslint no else return

---

eslint.config.mjs
packages/ckbtc/src/errors/minter.errors.ts

chore: eslint prefer-nullish-coalescing on

---

eslint.config.mjs
packages/ckbtc/src/utils/btc.utils.ts
packages/ic-management/src/utils/transform.utils.ts
packages/nns/src/canisters/governance/response.converters.ts
packages/nns/src/canisters/governance/services.ts
packages/nns/src/governance_test.canister.ts
packages/sns/src/governance.canister.ts

chore: eslint prefer-destructuring on

---

eslint.config.mjs
packages/ledger-icrc/src/index-ng.canister.spec.ts
packages/ledger-icrc/src/index.canister.spec.ts
packages/ledger-icrc/src/utils/ledger.utils.spec.ts
packages/nns/src/canisters/governance/request.converters.ts
packages/nns/src/canisters/governance/response.converters.ts
packages/nns/src/governance.canister.spec.ts
packages/utils/src/parser/token.spec.ts

chore: eslint object-shorthand on

---

eslint.config.mjs
packages/ckbtc/src/utils/btc.utils.ts
packages/zod-schemas/src/principal.ts

chore: eslint no-unused-vars on

---

eslint.config.mjs
packages/sns/README.md
packages/sns/src/governance.canister.ts

chore: eslint no-unnecessary-type-assertion on

---

eslint.config.mjs
packages/nns/src/governance.canister.spec.ts
packages/utils/src/utils/base32.utils.ts

chore: eslint func-style & prefer-arrow/prefer-arrow-functions on

---

eslint.config.mjs
packages/nns/src/types/governance_converters.ts
packages/sns/src/sns.wrapper.ts

chore: eslint no-useless-rename on

---

eslint.config.mjs
packages/ic-management/src/ic-management.canister.spec.ts
packages/ledger-icrc/README.md
packages/ledger-icrc/src/ledger.canister.ts
packages/nns/README.md
packages/nns/src/canisters/governance/request.converters.ts
packages/nns/src/canisters/governance/response.converters.ts
packages/nns/src/governance.canister.ts
packages/sns/README.md
packages/sns/src/root.canister.ts
packages/sns/src/swap.canister.ts
packages/utils/README.md
packages/utils/src/utils/agent.utils.ts
packages/utils/src/utils/did.utils.ts

chore: eslint arrow-body-style on

---

package-lock.json
package.json

We need https://github.com/dfinity/eslint-config-oisy-wallet/pull/108 to activate the `local-rules/prefer-object-params` in this repo.
- Bump lib

chore: bump eslint-config-oisy-wallet

---

CHANGELOG.md
package-lock.json
package.json
packages/ckbtc/package.json
packages/cketh/package.json
packages/cmc/package.json
packages/ic-management/package.json
packages/ledger-icp/package.json
packages/ledger-icrc/package.json
packages/nns/package.json
packages/sns/package.json
packages/utils/package.json
packages/zod-schemas/package.json

We want to release the latest changes and breaking changes.
- Update CHANGELOG and versions
- When upgrade ledger dependencies in NNS and SNS use a flexible version

chore: prepare release v70

---

package-lock.json
package.json
packages/ckbtc/src/types/minter.responses.ts
packages/ledger-icp/src/types/ledger_converters.ts
packages/ledger-icrc/src/types/ledger.params.ts
packages/nns/src/types/governance_converters.ts
packages/utils/src/utils/date.utils.ts

Get the last cool style.
- Bump `@dfinity/eslint-config-oisy-wallet`
- `npm run format && pm run lint -- --fix`

chore: bump and format with latest eslint-config-oisy-wallet

---

package-lock.json
package.json

- `npm rm prettier && npm i prettier`

chore: bump prettier

---

package-lock.json
package.json

- `npm rm esbuild && npm i esbuild`

chore: bump esbuild

---

.github/workflows/publish.yml

Temporary add `workflow_dispatch:` to publish action to release a patch of zod-schemas.

chore: workflow_dispatch for publish

---

packages/ic-management/src/types/ic-management.params.ts

feat: remove unused interface

---

packages/ic-management/src/ic-management.mock.ts

Spotted unused mocks data in ic-mgmt.

chore: remove unused mocks
