.gitignore
package-lock.json
package.json

nns-js is destined to become a library for other projects to use.  A such the API needs to be accessible without perusing the implementation.
Creating documentation has two steps:
- Generating the docs
- This is hopefully just a case of finding a suitable tool.
- Making the docs easily accessible
- There is no common place where npm packages are documented.  Larger packages have homepages.
- This PR does not address the question of publishing.
- Adds [`typedoc`](https://typedoc.org/) as a dev dependency, and a script to generate the docs.
I have generated the docs.  Some screenshots:

Add documentation tool

---

.gitignore
esbuild.mjs
jest.config.js
package-lock.json
package.json
scripts/rmdir.mjs
src/index.ts
src/utils/proto.ts
tsconfig.json

Bundle the library to ES modules and Common JS in order to be able to use it in nns-dapp
- bundle the library with esbuild
- generate esm modules with code splitting
- provide type declarations
- exclude `test.ts` and `spec.ts` from bundle
- fix test error `unexpected token 'export'`
Using a compiler (esbuild, rollup, etc.) leads to the same restriction as enabling `isolatedModules` for TypeScript to ensure that the compiled code is safe in case `const enum` would be exported (see [blog post](https://ncjamieson.com/dont-export-const-enums/)).
While developing this PR I noticed that the current code does lead to this behavior. Therefor I replaced the use of the enum with a plain `string`. This should be improved.
Same goal as PR [#3](https://github.com/dfinity/nns-js/pull/3) but produces …

build: esm and cjs

---

package.json

Display missing GitHub link and license on [npm](https://www.npmjs.com/package/@dfinity/nns)
- add `license` field to `package.json`
- add GitHub urls to `package.json`
- add license file to distributed files

docs: license and repo on npm

---

.eslintrc.json
.github/workflows/checks.yml

We have few tests but as we write more, it would be good to run them in CI so that they always pass in main.
- Added a github action to run tests.
- Added a github action to run lints, albeit ignoring candid and tests.

Add tests to gh CI

---

package.json

We would like to publish.  The new listProposals() method would be useful for projects that depend on nns-js.
Bumped the version number from 0.1.9 to 0.2.0 to take into account the API change from positional arguments to a dictionary.
There are no code changes so no additional tests should be required.
Run: `npm publish`
Note: This is a normal release, not a nightly release.

Publish version 0.2.0

---

src/canisters/governance/request.converters.ts
src/governance.ts

We need to list a user's neurons in the svelte nns dapp.
Adds the `getNeurons()` method, that gets a caller's own neurons.  The method mirrors the `getNeurons` in `nns-dapp/frontend/ts` however I am a little concerned by the API and would be very open to exposing the same API as raw.
Untested and unused.  The method may well be broken.  I am opening this PR so that the method is available before I have finished the createNeuron function, after which I plan to write tests for both.  The (very early and simple) test framework supports only anonymous calls so far and will have to be extended before this can get proper tests.

List neurons

---

package-lock.json
package.json

Bump agent-js to [v0.10.3](https://github.com/dfinity/agent-js/releases/tag/v0.10.3) with latest security improvements.
- bump dfinity libs to v0.10.3
I locally build and tested nns-js in nns-dapp svelte with the few features we have at the moment. All good.

build: bump agent-js v0.10.3

---

src/governance.ts

We wish to implement the `createNeuron()` function but not to include any nns-dapp code in nns-js.  This PR provides one required supporting function.
- Add `claimOrRefreshNeuronFromAccount()` to the governance canister.

Claim a neuron

---

src/governance.spec.ts
src/governance.ts

Needs for ProposalDetails page. To fetch the proposal data by id provided in url.
- `getProposalInfo()`
🚧

Add getProposalInfo to governance

---

.github/workflows/nightly.yml

The workflow view is broken, as can be seen here:  https://github.com/dfinity/nns-js/actions/runs/1921133150
The problem is that the schedule is commented out, and that makes the file invalid.
The schedule is commented out to prevent this from running until an org npm key is installed, as I have no power to create one myself.  This same goal can and has now been achieved by disabling the workflow in the GitHub UI, as [per the GitHub docs.](https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow).
* Uncomment the schedule
Workflows are rendered correctly on this PR.

Enter a valid schedule

---

src/canisters/governance/request.converters.ts
src/canisters/governance/response.converters.ts
src/governance.ts

Governance converters are classes that actually hold no states and mixes functions and methods.
- removes the classes, because stateless and have no particular purpose
- transform Governance converters (`response.converter.ts` and `request.converter.ts`) methods to functions
- few utilities functions refactored to use objects as parameters instead of comma separated list

refactor: drop governance converters stateless class for functions

---

src/index.ts
src/utils/neurons.utils.spec.ts
src/utils/neurons.utils.ts

Re-implement and expose neurons' utilities to filter ineligible, voted and not voted neurons.
These functions are currently implemented within the UI of the nns-dapp Flutter app.
See [lib/ui/proposals/proposal_detail_widget.dart](https://github.com/dfinity/nns-dapp/blob/62d66de3c3e1fbf4957c79cf50be489307555689/frontend/dart/lib/ui/proposals/proposal_detail_widget.dart#L55)
- add utilities `ineligibleNeurons`, `notVotedNeurons` and `votedNeurons`
- expose the `neurons.utils.ts` to any user of `nns-js` (through an export in `index.ts`)

feat: neurons utils voted, not voted and ineligible

---

.github/workflows/nightly.yml

The name of the nightly build was left teh same as the normal checking workflow by mistake.  This is confusing.
* Give the nightly build an appropriate name
None required

Correct name of the nightly build

---

.github/workflows/nightly.yml
scripts/build-nightly

The nightly build failed because protoc was not installed.  Protoc should not need to be called because the protocol buffer derived files _should_ already be up to date.
* Do not compile the protoc files.
* Set up npm profile as required to publish
This has been run by adding an on-push rule for this branch, pushing, then removing the rule.  See: https://github.com/dfinity/nns-js/actions/workflows/nightly.yml

The proto files on main should already be up to date

---

src/governance.spec.ts
src/governance.ts

Unify the naming of the functions.
We have `listKnownNeurons`, `listProposals` but `getNeurons`.
We have `listProposals` but `getProposalInfo`
- `getNeurons` -> `listNeurons`
- `getProposalInfo` -> `getProposal`
This is a breaking change. Once merged and published, I'll adapt nns-dapp.

feat: unify the governance naming of the functions

---

.github/workflows/checks.yml
package.json
proto/base_types_pb.js
proto/ledger_pb.js
scripts/install-protoc

protobuf builds are not currently tested in CI  That is an omission that should be addressed.
* Add a separate test for protobuf builds.
* Organize the tests a bit:
* The "build" test was just testing the candid build, so was misleading.  It is renamed and there is a new build test.
* Added a new "may-merge" target, similar to that discussed for nns-dapp, to make it clearer what the merge requirements are by not hiding the merge requirements away as an invisible list in the admin panel.
* The workflow now looks like this:  ![Screenshot from 2022-03-04 11-47-11](https://user-images.githubusercontent.com/5982633/156749604-fc89a8c2-3969-4c52-adf8-b7bcfaf91e60.png)
* Install a specific version of protoc.
* Rename the proto build command to `npm run protoc` - the original name is unnecessarily …

Add test for protobuf files

---

src/canisters/governance/request.converters.ts
src/governance.spec.ts
src/governance.ts
src/types/governance_converters.ts

Add functionality to update neuron followees.
* New method `setFollowees` in governance canister.
* Method test.

L2-337: Set Neuron Followee

---

src/governance.spec.ts
src/governance.ts
src/ledger.spec.ts
src/ledger.ts

LedgerCanister#transfer and GovernanceCanister#stakeNeuron support subaccounts.
* Add subaccount id converter to LedgerCanister.
* Add fromSubaccount to stakeNeuron.
* Add fromSubaccount to transfer.
* Add test in Ledger Canister for subaccount.
* Add test in Governance Canister for stake neuron from subaccount.

L2-338: Transfer from subaccounts

---

src/errors/governance.errors.ts
src/governance.spec.ts
src/governance.ts

Add `claimOrRefreshNeuron` method to Governance Canister.
* New method `claimOrRefreshNeuron` in Governance Canister.
* New claimOrRefreshNeuron tests

L2-331: Check Neuron Balances

---

src/canisters/governance/request.converters.ts
src/governance.spec.ts
src/governance.ts

Governance canister methods to start and stop the dissolving process.
* New method `startDissolving`.
* New method `stopDissolving`.
* Test for startDissolving and startDissolving.

L2-364: Start and Stop Dissolving Neuron

---

CHANGELOG.md
package-lock.json
package.json
src/utils/neurons.utils.spec.ts
src/utils/neurons.utils.ts

To improve the logic and avoid the bug (selction of neuron-with-0-voting-power) 'votableNeurons' was added.
Later we could refactor the nns-dapp to switch from custom code to this function.
@peterpeterparker Do we need `notVotedNeurons`? Currently it is used only in the code that will be replaced with `votableNeurons`.
- votableNeurons util
- votableNeurons test

feat: add votableNeurons util

---

.github/workflows/checks.yml

This reverts commit 6c1487f5b90bff657baeff1fe41ae6739917e0d6.
shfmt was failing to install with what looks like a network problem in AWS.  The above PR disabled shfmt.  As soon as shfmt is available again, CI should be green for this PR and it can be merged.
- Re-enable shell script formatting.

Revert "Disable shfmt due to installation problems (#81)"

---

src/canisters/governance/request.converters.ts
src/governance.spec.ts
src/governance.ts

ClaimOrRefreshNeuronFromSubaccount uses manage neuron method.
`claim_or_refresh_neuron_from_account` is deprecated: https://github.com/dfinity/ic/blob/master/rs/nns/governance/canister/canister.rs#L393
* claimOrRefreshNeuronFromAccount uses `mange_neuron` governance canister method
* Change tests to stake a neuron to mock changed call.
* New tests for claimOrRefreshNeuronFromAccount method.

L2-314: Change Deprecated Method to claim neuron

---

src/canisters/governance/request.converters.ts
src/canisters/governance/response.converters.ts
src/index.ts
src/utils/account_identifier.utils.ts
src/utils/converter.utils.ts

To display the account identifier of the ledger identity in nns-dapp we need to access the existing converter `principalToAccountIdentifier`.
- expose account identifier utils
- move account identifier utils to dedicated file from generic converter

feat: expose account identifier utils

---

src/canisters/governance/request.converters.ts
src/governance.spec.ts
src/governance.ts

Method to spawn a neuron from maturity.
* New method in governance service "spawnNeuron".
* Test for new method "spawnNeuron".

L2-373: Spawn Neuron

---

package-lock.json
package.json

eslint does not support yet typescript v4.6+
- downgrade typescript to v4.5.5

build: downgrade typescript for eslint

---

src/canisters/governance/request.converters.ts
src/canisters/governance/services.ts
src/governance.spec.ts
src/governance.ts

Spawning a neuron does not need percentageToSpawn.
The ledger IC app does not yet support the property "percentageToSpawn" when spawning.
* Make percentageToSpawn as optional.
* "spawnNeuron" returns new neuron id.
* Refactor some error management code.
* Update test to check return value.

L2-514: Hide Spawn neuron percentage for HW

---

src/errors/governance.errors.ts
src/governance.spec.ts
src/governance.ts

List neurons with hardware wallet is only supported through certified  - update - calls.
- throw an error if listing neurons is called with `certified: false`

feat: throw an error for unsupported list neurons query with hw

---

.github/CODEOWNERS

The CODEOWNERS is required by @dfinity/idx in order for this repo to
accept external contributions.

Add CODEOWNERS file (#647)

---

CHANGELOG.md
package-lock.json
package.json

Prepare release v0.4.3
Document undocumented changes of v0.4.1 and v0.4.2
Note: not sure if we should not have released v0.5.0 back then but let's go with the flow
@bitdivine once merge can you release a version and tag the release?

chore: release v0.4.3

---

CHANGELOG.md
package-lock.json
package.json

Few users are still using nns-dapp on iOS < v14. As a temporary solution we provided to nns-js the polyfill for `setBigUint64` we are already using in nns-dapp.
- bump agent-js `v0.11.3`

build: bump agent-js `v0.11.3` with `setBigUint64` for iOS < v15

---

src/ledger.spec.ts
src/ledger.ts

Add method to ledger canister to get the transaction fee.
* New method "transactionFee" in ledger canister.
* "transfer" method does not get the transfer fee from service if not present and is using a hardware wallet. This part is not used yet, but I fear we'll forget when we remove the protobuf depedency.
* Add tests for the "transactionFee" method.

L2-716: Transaction fee method

---

src/canisters/ledger/ledger.request.converts.ts
src/governance.spec.ts
src/governance.ts
src/ledger.spec.ts
src/ledger.ts
src/types/ledger_converters.ts
src/utils/converter.utils.ts

Simplify the conversion of subaccounts from one type to another.
* Subaccount is kept as array of numbers whichis needed for the Ledger Canister candid implementation.
* Adapt the protobuf converter.
* Fix tests to adapt to new type.

L2-728: Refactor subaccounts type transforms

---

.github/workflows/checks.yml

If the formatter runs slowely, the `candid` ci job might crash first because it runs a `git diff` on the all project to compare changes.
- scope `git diff` in ci jobs to consider only changes that matters for the job

build: scope git diff to fix ci

---

packages/nns/package.json
scripts/build-nightly
scripts/update-version.mjs

Fix nightly job publish to npm.
- create a build script that support workspace
- remove `npm install` to build version with exact dependencies and no minor updates
- remove `npm pack` that is executed automatically by `npm publish`

build: fix nightly

---

.eslintrc.json
packages/nns/src/account_identifier.ts
packages/nns/src/canisters/governance/request.converters.ts
packages/nns/src/canisters/governance/request.proto.converters.ts
packages/nns/src/canisters/governance/response.converters.ts
packages/nns/src/canisters/ledger/ledger.request.converts.ts
packages/nns/src/errors/governance.errors.ts
packages/nns/src/errors/ledger.errors.ts
packages/nns/src/genesis_token.ts
packages/nns/src/governance.ts
packages/nns/src/ledger.ts
packages/nns/src/sns_wasm.ts
packages/nns/src/types/governance_converters.ts
packages/nns/src/types/ledger_converters.ts
packages/nns/src/utils/account_identifier.utils.ts
packages/nns/src/utils/agent.utils.ts
packages/nns/src/utils/proto.utils.ts

Enforce usage of `type` in import with eslint rules [consistent-type-imports](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/consistent-type-imports.md).
This aligns the behavior to our svelte projects.
- set `consistent-type-imports` and fix lint errors

build: enforce type import

---

packages/nns/src/sns_wasm.spec.ts
packages/nns/src/sns_wasm.ts

There are many sns therefore use a function name with plural as in candid.

refactor: wasm list sns plural

---

.github/workflows/nightly.yml
scripts/build-nightly

As for nns-js, it would be handy to build and publish a nightly version of sns-js.
For CI:
- update `package.json` with nightly info in sns package
- build all workspaces
- publish sns nighlty to npm in

build: build and publish nightly sns to npm

---

CHANGELOG.md
packages/nns/src/canisters/governance/response.converters.ts
packages/nns/src/types/governance_converters.ts
packages/nns/src/utils/did.utils.ts

Map proposal info `deadline_timestamp_seconds` to the converter. We will ultimately need this information in NNS-dapp to get to know if a proposal duration is still valid or not.

feat: map proposal info deadline_timestamp_seconds

---

packages/sns/src/enums/swap.enums.ts
packages/sns/src/index.ts
packages/sns/src/sns.spec.ts
packages/sns/src/sns.ts

Prefix exposed sns types from candid with keyword `sns` to make their intent more obvious.

refactor: prefix sns types

---

packages/sns/src/sns.wrapper.spec.ts
packages/sns/src/sns.wrapper.ts
packages/sns/src/swap.canister.spec.ts
packages/sns/src/swap.canister.ts

User can notify the swap canister of a participation.
* Add notifyParticipation method to Swap and Wrapper classes
* Use refresh_buyer_tokens service to in the notifyParticipation.
* Test for the new methods.

L2-797: Swap Participation Functionality

---

CHANGELOG.md
HACKING.md
README.md
package-lock.json
package.json
packages/nns/package.json
packages/sns/package.json
scripts/esbuild.mjs

Developers may be using both [nns](/packages/nns) and [sns](/packages/sns) in their projects - as we do in [NNS-dapp](https://github.com/dfinity/nns-dapp/). That is s why, to help tree-shaking and avoid duplication of code, the libraries of this project need to reference [agent-js](https://github.com/dfinity/agent-js) as peer dependencies.
When we are building here both `nns` and `sns`, as both builds are standalone, `agent-js` libs get bundled within the outcome. Which is fine if the libraries were always use separately but unfortunately, as we noticed in NNS-dapp, when both are consumed app bundlers are not always able to tree-shake correctly the code afterwards. So developers might end-up with `agent-js` libs twice in their code.
- set `agent-js` libraries as peer dependencies …

build: agent-js peer dependencies

---

package-lock.json
packages/nns/package.json

Resolve #143.
This will also fix the usage of the lib for testing purpose as it referenced a version of `google-protobuf` that fails with `jest` in a NodeJS context - e.g. when running tests in NNS-dapp.
- bump `google-protobuf` last version

build: bump google-protobuf for nns

---

CHANGELOG.md
packages/sns/src/errors/governance.errors.ts
packages/sns/src/governance.canister.spec.ts
packages/sns/src/governance.canister.ts
packages/sns/src/index.ts
packages/sns/src/mocks/governance.mock.ts
packages/sns/src/sns.wrapper.spec.ts
packages/sns/src/sns.wrapper.ts
packages/sns/src/types/governance.params.ts

Add method `getNeuron` to get neuron data by id.
* Add getNeuron to wrapper and governance classes.
* Add tests for new method.
* Add and change a little bit the mock data for testing.

L2-868: Get SNS neuron

---

packages/sns/src/converters/governance.converters.ts
packages/sns/src/governance.canister.spec.ts
packages/sns/src/governance.canister.ts
packages/sns/src/sns.wrapper.spec.ts
packages/sns/src/sns.wrapper.ts
packages/sns/src/types/governance.params.ts

Method to remove neuron permissions.
* New method in sns governance "removeNeuronPermissions".
* New method in sns wrapper "removeNeuronPermissions"
* Test for new wrapper method.
* Test for new sns governance method.

L2-705: SNS Remove Hotkey

---

scripts/update-version.mjs

Make sns/nns nightly build reference also the utils peer dependency as nightly otherwise only previous major/minor version can be installed in consumer apps.
- apprend `-nightly` to peer dependencies for nightly build

build: nightly peer dependencies version

---

.github/workflows/nightly.yml
scripts/update-version.mjs

If would be convenient sometimes to be able to not wait for the nightly builds. This PR adds the support for manually triggering the GitHub actions workflow - i.e. to publish manually to npm the nightly build.
- update actions to support manual trigger [workflow_dispatch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch)
- enhance versioning script to support multiple versions a day

build: manually publish nightly version to npm

---

CHANGELOG.md
packages/nns/src/canisters/governance/response.converters.ts
packages/nns/src/enums/governance.enums.ts
packages/nns/src/enums/icp.enums.ts
packages/nns/src/governance.canister.spec.ts
packages/nns/src/icp.spec.ts
packages/nns/src/icp.ts
packages/nns/src/utils/neurons.utils.spec.ts

Bring consistency in the exposed enums of NNS-js. Useful for the community to follow a pattern and for NNS-dapp/dashboard to share the i18n labels.
- governance and icp enums renamed with Pascal case
- new enum `NnsFunction`

feat: nns enums consistency

---

HACKING.md
package-lock.json
package.json

We are already using agent-js v0.13.2 in NNS-dapp. This PR aligns it in ic-js.
- bump agent-js from v0.13.1 to v0.13.2

build: agent-js v0.13.2

---

packages/nns/src/account_identifier.ts
packages/nns/src/canisters/governance/request.converters.ts
packages/nns/src/governance.canister.spec.ts
packages/nns/src/governance.canister.ts

Introduce new functionality to nns governance: setDissolveDelay and setNodeProviderAccount
* New nns governance canister methods: setDissolveDelay and setNodeProviderAccount.
* Move how an account identifier is parse to candid to AccountIdentifier class.
* Tests provided for the new methods.

Feat: New HW functionalities

---

.github/workflows/publish.yml

`npm ci` and `npm run build` need to be run before being able to publish.
in addition, add manual trigger so that we can also (re) launch manually if needed.

build: fix missing publish steps and manual trigger

---

.github/workflows/publish.yml

Com'on!  `npm` keyword missing in build script to `npm run build`

build: fix npm missing typo

---

CHANGELOG.md
package-lock.json
packages/nns/package.json
packages/sns/package.json
packages/utils/package.json

A first versio of `@dfinity/utils` has been released already, this bumps to next `v0.0.2`.

build: bump utils-js version

---

CHANGELOG.md
packages/nns/README.md
packages/nns/src/token.spec.ts
packages/nns/src/token.ts

Improvements on `TokenAmount` API.
- `token` param in `TokenAmount` factory methods is mandatory instead of using ICPToken as default.
- `TokenAmount.fromNumber` does not return `FromStringToTokenError`, only `TokenAmount`.
* Add `token` param to all tests.

GIX-1005: Improve Token Amount Class

---

packages/sns/README.md
packages/sns/src/converters/sns-index.converters.ts
packages/sns/src/errors/sns-index.errors.ts
packages/sns/src/index.ts
packages/sns/src/sns-index.canister.spec.ts
packages/sns/src/sns-index.canister.ts
packages/sns/src/types/sns-index.params.ts
scripts/docs.js

Add method to get the transactions of an account.
* Add SnsIndexCanister with "getTransactions" method.
* Test for the new sns canister.

GIX-996: SNS Transactions

---

packages/sns/candid/sns_index.certified.idl.js
packages/sns/candid/sns_index.d.ts
packages/sns/candid/sns_index.did
packages/sns/candid/sns_index.idl.js

There is a bug in the candid definition of the Index canister.
* Change the type of oldest_tx_id from GetTransactions
Not applicable

Fix: Index canister candid parsing issue

---

packages/sns/README.md
packages/sns/src/converters/governance.converters.ts
packages/sns/src/governance.canister.spec.ts
packages/sns/src/governance.canister.ts
packages/sns/src/index.ts
packages/sns/src/sns.wrapper.spec.ts
packages/sns/src/sns.wrapper.ts
packages/sns/src/types/governance.params.ts

Add methods to check and refresh neuron balances.
* New methods "claimNeuron", "refreshNeuron" and "queryNeuron" in SNS Governance.
* New methods "getNeuronBalance" in SNS wrapper.
* "getNextNeuronAccount" uses "queryNeuron" instead of checking the balance. Neurons can have balance 0.
* Tests for new methods.
* Fix broken tests after refactor.

GIX-1116: Check SNS Neuron balances

---

packages/sns/README.md
packages/sns/src/sns.wrapper.spec.ts
packages/sns/src/sns.wrapper.ts
packages/sns/src/utils/governance.utils.spec.ts
packages/sns/src/utils/governance.utils.ts

Renaming in SNS.
* Rename getNextNeuronAccount to nextNeuronAccount in sns-wrapper.
* Rename getNeuronSubaccount to neuronSubaccount in sns governance utils
Fix tests

FIx: Rename "getNextNeuronAccount" method

---

packages/sns/README.md
packages/sns/src/governance.canister.spec.ts
packages/sns/src/governance.canister.ts
packages/sns/src/index.ts
packages/sns/src/sns.wrapper.spec.ts
packages/sns/src/sns.wrapper.ts

Add method to retrieve the Nervous System Functions from an SNS project.
Those are the "topics" that a neuron can follow.
* Add listNervousSystemFunctions method to sns governance.
* Add listNervousSystemFunctions method to sns wrapper.
* Export ListNervousSystemFunctionsResponse and NervousSystemFunction types.
* Test new sns wrapper method.
* Test new sns governance method.

GIX-1111: List SNS Proposal Topics

---

packages/sns/README.md
packages/sns/src/converters/governance.converters.ts
packages/sns/src/governance.canister.spec.ts
packages/sns/src/governance.canister.ts
packages/sns/src/index.ts
packages/sns/src/sns.wrapper.spec.ts
packages/sns/src/sns.wrapper.ts
packages/sns/src/types/governance.params.ts

Expose functionality to manage followees of an sns neuron.
* Add method setTopicFollowees to sns governance.
* Add method setTopicFollowees to sns wrapper.
* Test new sns governance method.
* Test new sns wrapper method.

GIX-1113: SNS Neuron Followee Management

---

packages/nns/src/token.spec.ts
packages/nns/src/token.ts

An issue was found when converting the number "0.3319" to an ICP amount. There was a rounding error.
* TokenAmount.fromNumber uses fromString. Raises error if number has more than 8 decimals.
* Changed tests to adapt to new raised error.
* Add the test for the specific bug.

Fix: TokenAmount.fromNumber problems

---

packages/sns/README.md
packages/sns/src/constants/governance.constants.ts
packages/sns/src/converters/governance.converters.ts
packages/sns/src/enums/governance.enums.ts
packages/sns/src/governance.canister.spec.ts
packages/sns/src/governance.canister.ts
packages/sns/src/index.ts
packages/sns/src/mocks/governance.mock.ts
packages/sns/src/sns.wrapper.spec.ts
packages/sns/src/sns.wrapper.ts
packages/sns/src/types/governance.params.ts

Add method in SNS Governance to fetch proposals.
* Add "listProposals" to SNS Governance which calls "list_proposals".
* Add two new SNS enums: SnsProposalRewardStatus and SnsProposalDecisionStatus.
* Add "listProposals" to SNS Wrapper.
* New converter toListProposalRequest.
* Add tests for new listProposals method in SNS Governance and Wrapper.

GIX-1210: List Sns Proposals

---

packages/nns/README.md
packages/nns/src/canisters/ledger/ledger.request.converts.ts
packages/nns/src/governance.canister.ts
packages/nns/src/ledger.canister.spec.ts
packages/nns/src/ledger.canister.ts
packages/nns/src/types/ledger_converters.ts
packages/sns/README.md
packages/sns/src/sns.wrapper.ts
packages/sns/src/types/governance.params.ts
packages/sns/src/types/ledger.params.ts

Add optional param createdAt in NNS Transfers.
This parameter is used in the NNS Ledger to identify duplicated transactions. Without it, two transfers with the same params from the same caller would be considered as two different transactions. This could happen if agent-js or the client retries the request.
If the request has the createdAt set and agent-js retries the call, the Ledger canister will consider it as a duplicated and not perform the transaction twice.
* Add createdAt optional param to `TransferRequest` type.
* Handle the new param in transferHardwareWallet.
* Handle the new param in toTransferRawRequest.
* Add a test to check that the new param is added in the request.

Feat: Add createAt param for NNS Transfers

---

packages/sns/src/converters/governance.converters.ts
packages/sns/src/governance.canister.spec.ts
packages/sns/src/types/governance.params.ts

Add support for the param `to_account` when disbursing SNS neuron.
This is not used in the nns-dapp.
* Add optional toAccount in SnsDisburseNeuronParams
* Add support for the extra param in toDisburseNeuronRequest
* Add new converter toCandidAccount in governance.converters. The toCandidAccount in ledger.converters can't be used because the Account type in governance and ledger canisters are different.
* Extend current test case to check that toAccount is used.

Chore: Support account to in sns disburse

---

packages/nns/src/canisters/governance/request.proto.converters.ts
packages/nns/src/governance.canister.spec.ts
packages/nns/src/governance.canister.ts

Enable merge neurons for HW controlled neurons
* Support for merge neurons is in candid. Remove the redirection to the proto method.
* Remove unnecessary test case.

Chore lm enable merge neurons candid

---

packages/ledger/src/utils/ledger.utils.spec.ts
packages/ledger/src/utils/ledger.utils.ts

There was a bug with the encoding and decoding of ICRC-1 accounts when it involved subaccounts.
* Change the extra bytes when encoding and decoding ICRC-1 accounts.
* Adapt tests.

Fix: Encode ICRC-1 accounts

---

CHANGELOG.md
packages/ledger/src/mocks/ledger.mock.ts
packages/ledger/src/types/ledger.responses.ts

As for other metadata, expose a constant for the Icrc1 metadata LOGO as well.

feat: export a constant for the Icrc1 metadata logo

---

packages/utils/src/utils/did.utils.spec.ts
packages/utils/src/utils/did.utils.ts

`toNullable` checks only `undefined` to add array or not.
Candid uses `[] | [T]` for optional parameteres. `T` can also be a falsy value like `null`, `false` or `0`.
* Change `toNullable` implementation.
* Add tests to cover falsy cases.

Fix: ToNullable checks only undefined

---

CHANGELOG.md
packages/utils/README.md
packages/utils/src/index.ts
packages/utils/src/utils/debounce.utils.spec.ts
packages/utils/src/utils/debounce.utils.ts
packages/utils/src/utils/nullish.utils.spec.ts
packages/utils/src/utils/nullish.utils.ts

Copy/move nullish and debounce functions from NNS-dapp to utils. That way we can use these in NNS-dapp but also in ic-js libraries or gix-cmp.

feat: nullish and debounce functions

---

packages/utils/README.md
packages/utils/src/utils/did.utils.spec.ts
packages/utils/src/utils/did.utils.ts

Extend `toNullable` to handle `null`.
As discussed with @lmuntaner .

feat: extend toNullable to handle null

---

packages/sns/src/index.ts

Make swap error types visible from outside.
- add swap.errors to index.ts

fix: swap.errors visibility

---

CHANGELOG.md
packages/ckbtc/README.md
packages/ckbtc/src/errors/minter.errors.ts
packages/ckbtc/src/index.ts
packages/ckbtc/src/minter.canister.spec.ts
packages/ckbtc/src/minter.canister.ts
packages/ckbtc/src/mocks/minter.mock.ts
packages/ckbtc/src/types/minter.params.ts
packages/ckbtc/src/types/minter.responses.ts
packages/sns/src/index.ts

Implement and propose the two functions required to convert ckBTC to BTC.
- implement `get_withdrawal_account` and `retrieve_btc`

feat: ckBTC get_withdrawal_account and retrieve_btc

---

package-lock.json
package.json
packages/ckbtc/package.json
packages/cmc/package.json
packages/ledger/package.json
packages/nns/package.json
packages/sns/package.json
packages/utils/package.json

The `package.json` we publish to npm are not currently referencing the libraries peer dependencies (e.g. https://www.npmjs.com/package/@dfinity/ledger?activeTab=explore) which is not accurate.
- `npm rm @dfinity/agent @dfinity/candid @dfinity/principal && npm i @dfinity/agent @dfinity/candid @dfinity/principal --workspaces --save-peer`
(`--workspaces` is the key here)

build: peer dependencies propagated to npm

---

packages/nns/candid/ledger.certified.idl.js
packages/nns/candid/ledger.d.ts
packages/nns/candid/ledger.did
packages/nns/candid/ledger.idl.js

We do not used these, therefore we should be fine but additional values in the `Operation` variant have been added to the ICP ledger on mainnet. Therefore better have these in the code.
- update candid and generate types

feat: icp ledger operation variant

---

packages/nns/README.md
packages/nns/src/token.spec.ts
packages/nns/src/token.ts

Avoid throwing error on exponential formatted numbers
https://dfinity.atlassian.net/browse/GIX-1373
- apply `toLocaleString` on exponential number strings
- update test to be more precise
before
after

Gix 1373 avoid exponent format in icp amount

---

HACKING.md
package.json

`npm ci && npm run test` on a clean branch gives errors because of dependencies between the packages.
1. Add a line in HACKING.md about building `utils` and `ledger` first.
2. Add `npm run test-all` script which builds packages in the correct order before running all the tests.
`rm -rf packages/*/dist node_modules/ && npm run test-all`

Build utils and ledger before other packages

---

packages/ledger/README.md
packages/ledger/src/ledger.canister.spec.ts
packages/ledger/src/ledger.canister.ts
packages/sns/README.md
packages/sns/src/sns.wrapper.spec.ts
packages/sns/src/sns.wrapper.ts

Show important data like total tokens supply in the Project Detail page in the nns dapp.
Therefore, we expose the ledger endpoint `icrc1_total_supply` to use it in nns dapp and others to get this important data.
* Add new endpoint `totalTokensSupply` to IcrcLedgerCanister.
* Add new endpoint `totalTokensSupply` to Sns Wrapper.
* Test new endpoint in IcrcLedgerCanister
* Test new endpoint in SNS Wrapper

GIX-1381: Add total tokens supply endpoint

---

.github/workflows/checks.yml
package-lock.json
package.json

Calculate the cost of the ic-js libs when the GA checks run.
I think the GA or `size-limit` weight also the size of the peer dependencies so it provides a result for each libraries as if it was not used together with another library.
```
@dfinity/ckbtc 86kb
@dfinity/cmc 76kb
```
which in reality is maybe something like
```
@dfinity/ckbtc 26kb
@dfinity/cmc 16kb
@dfinity/agent-js 60kb
```
- use action [andresz1/size-limit-action@v1](https://github.com/andresz1/size-limit-action) in CI

build: check libraries size limit with GitHub actions

---

package.json

Ignore peer dependencies (agent-js, utils and ledger) in size comparison.
- add `ignore` patterns to `package.json`

build: ignore peer dependencies in size limit

---

package.json
packages/sns/src/converters/governance.converters.spec.ts
packages/sns/src/converters/governance.converters.ts
packages/sns/src/index.ts
packages/sns/src/types/actions.ts
packages/sns/src/types/common.ts

Users should understand the parameters in SNS proposal actions.
For that, we don't want to show optional parameters as `[] | [T]`, instead as `undefined | T`.
* Add converter `toActionOptional` that converts the Action of SNS proposals.
* New types to be used in the converter function above: ActionOptional, TransferSnsTreasuryFundsOptional, ... Pattern is `<Type>Optional`.
* Test the converter with each action in the variant.

GIX-1220: Add SNS action converters

---

CHANGELOG.md
packages/ckbtc/README.md
packages/ckbtc/candid/minter.certified.idl.js
packages/ckbtc/candid/minter.d.ts
packages/ckbtc/candid/minter.did
packages/ckbtc/candid/minter.idl.js
packages/ckbtc/src/minter.canister.spec.ts
packages/ckbtc/src/minter.canister.ts
packages/ckbtc/src/types/minter.params.ts
packages/ckbtc/src/types/minter.responses.ts

Update ckBTC for last canister implementation.
- `estimate_fee` renamed to `estimate_withdrawal_fee`
- new endpoint `get_deposit_fee` added

feat: ckbtc estimate fee renamed and get deposit fee added

---

packages/nns/README.md
packages/nns/candid/genesis_token.did
packages/nns/candid/governance.certified.idl.js
packages/nns/candid/governance.d.ts
packages/nns/candid/governance.did
packages/nns/candid/governance.idl.js
packages/nns/candid/ledger.did
packages/nns/candid/sns_wasm.did
packages/nns/src/governance.canister.spec.ts
packages/nns/src/governance.canister.ts

Add endpoint to get the latest reward event of the NNS Governance
* New endpoint in NNS Governance `lastestRewardEvent`.
* Update nns-js candid interfaces. Only changes in governance canister.
* Add test for new endpoint.

GIX-1481: Get latest reward event NNS Governance

---

.github/workflows/nightly.yml
.github/workflows/publish.yml

Publish provenance alongside our libraries to npm.
- https://github.blog/2023-04-19-introducing-npm-package-provenance/
- https://github.blog/changelog/2023-04-19-npm-provenance-public-beta/
- add flag `--provenance` next to `npm publish`

build: publish to npm with provenance

---

packages/nns/src/enums/governance.enums.ts

We want to support payload rendering for BitcoinSetConfig proposals.
According to the instructions [here](https://github.com/dfinity/nns-dapp/blob/main/HOWTO.md), we need to update this enum in ic-js.
[Here](https://github.com/dfinity/ic/blob/master/rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs#:~:text=BitcoinSetConfig%20=%2039) is the corresponding value from the governance canister.
Add `BitcoinSetConfig = 39,` to `enum NnsFunction` in `packages/nns/src/enums/governance.enums.ts`
None

GIX-1518 Add BitcoinSetConfig to enum NnsFunction

---

.github/workflows/checks.yml

The size checker should not run on `main` as it results in error there. We want to compare the size of new code.

build: do not run size checker on main

---

packages/ledger/README.md
packages/ledger/src/types/ledger.params.ts

```
export interface BalanceParams extends QueryParams {
owner: Principal;
subaccount?: Subaccount;
}
```
is actually equals to
```
export type BalanceParams = IcrcAccount & QueryParams;
```
i.e. `IcrcAccount` represent the owner and subaccount.

refactor: ledger balance params are equals to type IcrcAccount and certified

---

packages/nns/README.md

A developer reported on [Discord](https://discord.com/channels/748416164832608337/1104349948440490066/1104349948440490066) an issue with NNS `accountBalance`.
Turned out the issue was the sample in the readme as the function returns already a `bigint` and therefore do not need to be caster `.toE8s`.

docs: fix sample in readme

---

packages/sns/candid/sns_governance.certified.idl.js
packages/sns/candid/sns_governance.d.ts
packages/sns/candid/sns_governance.did
packages/sns/candid/sns_governance.idl.js
packages/sns/candid/sns_root.certified.idl.js
packages/sns/candid/sns_root.d.ts
packages/sns/candid/sns_root.did
packages/sns/candid/sns_root.idl.js
packages/sns/candid/sns_swap.certified.idl.js
packages/sns/candid/sns_swap.d.ts
packages/sns/candid/sns_swap.did
packages/sns/candid/sns_swap.idl.js
packages/sns/src/converters/governance.converters.spec.ts
packages/sns/src/converters/governance.converters.ts
packages/sns/src/sns.wrapper.spec.ts
packages/sns/src/swap.canister.spec.ts
packages/sns/src/types/actions.ts
scripts/compile-idl-js
scripts/import-candid

We want to use the `confirmation_text` and `restricted_countries` fields in SNS participation on NNS dapp.
**Note**: This is a breaking change. The new fields are declared as optional in Candid, but in TypeScript that results in types like `[] | [string]` which are not optional. So when upgrading the ic-js dependency those fields will be required to be at least `[]`.
Each of these are a separate commit, which might help reviewing:
1. In `scripts/import-candid` change `icrc1.did` to `ledger.did`. The former no longer exists and has been replaced by the latter.
2. In `scripts/compile-idl-js`, require version `didc 0.1.4`. I first used `didc 0.1.6` and it caused breaking changes.
3. Run `scripts/import-candid`
4. Revert the changes in other packages than `sns`.
5. Run …

GIX-1545 ic-js: Import new candid

---

packages/nns/candid/genesis_token.did
packages/nns/candid/governance.certified.idl.js
packages/nns/candid/governance.d.ts
packages/nns/candid/governance.did
packages/nns/candid/governance.idl.js
packages/nns/candid/ledger.certified.idl.js
packages/nns/candid/ledger.d.ts
packages/nns/candid/ledger.did
packages/nns/candid/ledger.idl.js
packages/nns/candid/sns_wasm.certified.idl.js
packages/nns/candid/sns_wasm.d.ts
packages/nns/candid/sns_wasm.did
packages/nns/candid/sns_wasm.idl.js
packages/nns/src/governance.canister.spec.ts

We want to use the API to simulate merging neurons, but also keep candid up-to date in general.
Simulating merging neurons was added in [this PR](https://gitlab.com/dfinity-lab/public/ic/-/commit/1866f8f1a94dcc6e98065e0fd554c8e0e93965df) / [this commit](https://github.com/dfinity/ic/commit/1866f8f1a94dcc6e98065e0fd554c8e0e93965df).
I used `bin/dfx-software-ic-latest --after 1866f8f1a94dcc6e98065e0fd554c8e0e93965df -x ../../ic` from snsdemo to find commit b9fc66eafca530e997313aa68aaac31d41e6a875.
1. Checked out commit `b9fc66eafca530e997313aa68aaac31d41e6a875` in my IC repo.
2. Ran `scripts/import-candid ../../ic` to import candid from the IC repo at that commit.
3. Reverted the changes in packages other than `packages/nns`.
4. Ran `scripts/compile-idl-js`
5. Changed …

Import candid for nns package

---

packages/ckbtc/README.md
scripts/docs.js

Just noticed I forgot to add the `btc.utils` to the list of files to process to generate the ckBTC README.

docs: generate README docs for BTC utils

---

packages/sns/src/sns.spec.ts
packages/sns/src/sns.wrapper.ts

We need the Sns index cansiter id to be exposed in the wrapper for NNS-dapp feature [#2639](https://github.com/dfinity/nns-dapp/pull/2639) but also (most probably) because in the future it will be possible to get the balance of an account not only from the ledger but also from the index canister.

feat: expose Sns index canister id in wrapper

---

.github/workflows/docs.yml
packages/ckbtc/README.md
packages/ledger/README.md
packages/ledger/src/ledger.canister.ts
packages/nns/README.md
packages/sns/README.md

- add `npm run build` before generating the docs. this allow the doc library to resolve few parameters that were documented as `any`
- While not necessary, it's probably a best practice to set node version before running the script
- Bump `actions/checkout` to v3 for no particular other reason than using a more up-to-date version

build: improve docs generation

---

package.json
packages/ckbtc/README.md
packages/ckbtc/candid/minter.certified.idl.js
packages/ckbtc/candid/minter.d.ts
packages/ckbtc/candid/minter.did
packages/ckbtc/candid/minter.idl.js
packages/ckbtc/src/index.ts
packages/ckbtc/src/minter.canister.spec.ts
packages/ckbtc/src/minter.canister.ts

Expose new ckBTC `get_minter_info` (already available on mainnet) which returns internal minter parameters such as the minimal amount to retrieve BTC, minimal number of confirmations or KYT fee.
- update did files
- imeplement `get_minter_info`

feat: ckBTC get minter info

---

CHANGELOG.md
packages/ckbtc/README.md
packages/ckbtc/src/minter.canister.spec.ts
packages/ckbtc/src/minter.canister.ts

The ckBTC `get_deposit_fee` can (or should) be deprecated. Instead, the new `get_minter_info` should be used.
Confirmed by Léo:
> get_deposit_fee = get_minter_info.kyt_fee

feat: deprecate ckBTC deposit fee

---

packages/nns/README.md
packages/nns/src/governance.canister.spec.ts
packages/nns/src/governance.canister.ts

Prepare for migration of HW to Candid.
If the fee is not passed, the transfer fetches it. Yet, the Ledger App doesn't support fetching the transfer fee.
One solution is to pass a fee when staking a neuron, which is then passed when making the transfer.
Another solution (not here) is to use an anonymous identity when fetching the fee. This is not straightforward because we use classes. The identity is in the agent, which is passed in the initialization of the class.
* Add a `fee` parameter when staking an NNS neuron.
* Add a test to check that the `fee` parameter is passed then to the `transfer` method.

Chore: Add fee to nns stake neuron method

---

CHANGELOG.md
README.md
package-lock.json
package.json
packages/ic-management/README.md
packages/ic-management/src/errors/ic-management.errors.spec.ts
packages/ic-management/src/errors/ic-management.errors.ts
packages/ic-management/src/ic-management.canister.spec.ts
packages/ic-management/src/ic-management.canister.ts
packages/ic-management/src/ic-management.mock.ts
packages/ic-management/src/index.spec.ts
packages/ic-management/src/index.ts
packages/ic-management/src/types/canister.options.ts
packages/ic-management/src/types/ic-management.did.ts
packages/ic-management/src/types/ic-management.response.ts
packages/ic-management/src/utils/ic-management.converters.ts
scripts/docs.js

- copy `getCanisterDetails` and `updateSettings` from NNS dapp to implement `@dfinity/ic-management`.
- adapt structure and file naming (no functional changes)
- fix `packages` instead of `package` in root `package.json`
- set size limit checker
- adapt docs to generate docs for canister

feat: implement IC mgmt - copy getCanisterDetails and updateSettings from NNS dapp

---

packages/ckbtc/README.md
packages/ic-management/README.md

Of course I had to notice after release there was a typo in the title of the readme 😆.

docs: fix library name

---

ADMIN.md
scripts/build-next

When we build next, the version and utils dependencies is tweaked so we should do that for `ic-management` too.

build: fix ic-mgmt next dependencies and version

---

CHANGELOG.md
package-lock.json
package.json
scripts/esbuild.mjs

When the dapp - as NNS dapp - does not polyfill correctly, the library can hit a `global undefined`. Therefore this PR redo the global polyfill for the browser and bump to minor version to release to npm.
Reverts the polyfill removed in https://github.com/dfinity/ic-js/pull/350

build: redo global polyfill

---

.github/workflows/publish.yml
CHANGELOG.md
package-lock.json
package.json
packages/ic-management/package.json

Last publish failed for `@dfinity/ic-management`: https://github.com/dfinity/ic-js/actions/runs/5332655039
Root cause is npmjs that displays v0.0.1 but has already received v0.0.2.
This PR temporary comment the publication of other libs (will be reactivated in #362) and bump `ic-management` for a release.

build: publish ic-management

---

package-lock.json
package.json

Fix semver vulnerable to Regular Expression Denial of Service [CVE-2022-25883](https://github.com/advisories/GHSA-c2qf-rxjj-qqgw).
- pin `semver` to v7.3.5

Bump semver

---

packages/ic-management/README.md
packages/ic-management/src/ic-management.canister.ts
packages/utils/README.md
packages/utils/src/utils/actor.utils.ts

agent-js applies a transformation to interpret the canister id when instantiating the IC management canister: https://github.com/dfinity/agent-js/blob/e292412e51a48d2fc34310c149984822a64418d5/packages/agent/src/actor.ts#L399
This is useful to interact with it from the local environment. It was also part of the Dart iteration of NNS-dapp.
- copy `transform` method from agent-js
- extend `createService`

fix: usage of ic-management locally

---

packages/ic-management/candid/ic-management.certified.idl.js
packages/ic-management/candid/ic-management.d.ts
packages/ic-management/candid/ic-management.did
packages/ic-management/candid/ic-management.idl.js
packages/ic-management/src/ic-management.canister.spec.ts
packages/ic-management/src/ic-management.canister.ts
scripts/import-candid

They have moved the `ic.did` file in the https://github.com/dfinity/interface-spec repo, therefore we have to adapt the source we use to populate the did file with a script.
At the same time, this PR upgrades the related did file.

feat: update IC management did file and source

---

packages/ledger/README.md
packages/ledger/src/utils/ledger.utils.ts

There is now a dedicated markdown file that describes the ICRC text encoding in the related repo.
Resolves #381

docs: correct ICRC text encoding reference

---

package-lock.json
package.json
packages/ckbtc/package.json
packages/cmc/package.json
packages/ic-management/package.json
packages/ledger/package.json
packages/nns/package.json
packages/nns/src/governance.canister.spec.ts
packages/sns/package.json
packages/sns/src/sns.wrapper.spec.ts
packages/utils/package.json
scripts/update-agent

Bump `agent-js` version to `v0.18.1`. This is required to resolve an "endless loop issue" when the ic-mgmt library is used to request the statuses of canister for which the caller is not a controler.
"endless loop" because from obversation it seems to ends after 5min.
Will be integrated in NNS dapp (https://github.com/dfinity/nns-dapp/pull/2950) to solve similar issue.
- bump agent-js last version
- add a script `npm run update:agent` to update all peer dependencies of the libs that use agent-js

build: bump agent-js v0.18.1

---

CHANGELOG.md

I want to release agent-js. All version number are already ready, we just need the changelog.

docs: release v0.18.1

---

package.json
packages/sns/README.md
packages/sns/src/converters/governance.converters.ts
packages/sns/src/governance.canister.spec.ts
packages/sns/src/governance.canister.ts
packages/sns/src/sns.wrapper.spec.ts
packages/sns/src/sns.wrapper.ts
packages/sns/src/types/governance.params.ts

Add `disburseMaturity` to sns functions
- `disburseMaturity` function
- related types
- increased size limit for sns: 14Kb -> 16Kb
- disburseMaturity params spec

Sns disburse maturity function

---

CHANGELOG.md
packages/utils/README.md
packages/utils/src/index.ts
packages/utils/src/utils/json.utils.spec.ts
packages/utils/src/utils/json.utils.ts

The other day I was that close to use these functions we are using in NNS Dapp in another project. Ultimately I did not but it can be someday useful for the community to use these JSON reviver and replacer. That's why it's cool to move these from the dapp to the utils lib.
- integrate JSON reviver and replacer utils from NNS Dapp

feat: json reviver and replacer utils

---

packages/sns/README.md
packages/sns/src/errors/common.errors.ts
packages/sns/src/index.ts
packages/sns/src/swap.canister.spec.ts
packages/sns/src/swap.canister.ts
packages/sns/src/utils/error.utils.spec.ts
packages/sns/src/utils/error.utils.ts

Check the error raised in getFinalizationStatus to return a new error UnsupportedMethodError
This way, the clients using the endpoints can easily identify whether a method is supported by the canister or not.
* New error `UnsupportedMethodError`.
* New error util `isMethodNotSupportedError`.
* Use new error util and error in `getFinalizationStatus`.
* Test new error util.
* Test new functionality in getFinalizationStatus

GIX-1841: Add unsupported method error for getFinalizationStatus

---

packages/sns/src/errors/common.errors.ts

I forgot to add the `readonly` to `UnsupportedMethodError` property in the previous PR.
* Set `methodName` of `UnsupportedMethodError` as readonly
Not necessary

Chore: Add readonly to property

---

CHANGELOG.md
package-lock.json
packages/ckbtc/package.json
packages/ckbtc/src/utils/btc.utils.ts
packages/nns/README.md
packages/nns/package.json
packages/nns/src/account_identifier.ts
packages/nns/src/governance.canister.ts
packages/nns/src/utils/account_identifier.utils.ts
packages/sns/package.json
packages/sns/src/utils/governance.utils.ts

Similar to what was done in `agent-js` to solve the issue regarding last version of Chrome and validation of the certificate, replace `js-sha256` with `@noble/hashes`.
Related agent-js PR is https://github.com/dfinity/agent-js/pull/753

feat: replaces the js-sha256 library with @noble/hashes

---

packages/sns/candid/sns_governance.certified.idl.js
packages/sns/candid/sns_governance.d.ts
packages/sns/candid/sns_governance.did
packages/sns/candid/sns_governance.idl.js
packages/sns/candid/sns_governance_test.certified.idl.d.ts
packages/sns/candid/sns_governance_test.certified.idl.js
packages/sns/candid/sns_governance_test.d.ts
packages/sns/candid/sns_governance_test.did
packages/sns/candid/sns_governance_test.idl.d.ts
packages/sns/candid/sns_governance_test.idl.js
packages/sns/src/governance.canister.spec.ts
packages/sns/src/governance_test.canister.ts
packages/sns/src/index.ts
packages/sns/src/types/governance_test.params.ts
scripts/import-candid

Add `addMaturity` test function.
Replacement of https://github.com/dfinity/ic-js/pull/406
The only disadvantage is the package size changes +23% vs +0.98%
- add sns/governance_test candid file (4fbe776aeea08222b8b47f5f2902fe77b58b7150)
- update sns/governance candid file to keep both (standard and _test) in sync (4fbe776aeea08222b8b47f5f2902fe77b58b7150)
- related ids
- SnsGovernanceTestCanister
- addMaturity function
Manually tested. No unit tests because of the dev usage only.

Sns test api

---

packages/nns/src/governance.canister.spec.ts

In `governance.canister.spec.ts`, the `describe` block of `listKnownNeurons` has lots of tests that are not about `listKnownNeurons`.
There is also a TODO to fix this from May 2022.
Group tests by tested method.
Pass and the grouping looks like this in the output of `npm run test`:
``` PASS  src/governance.canister.spec.ts
GovernanceCanister
GovernanceCanister.listKnownNeurons
✓ populates all KnownNeuron fields correctly (10 ms)
✓ handles description being undefined (6 ms)
✓ returns all KnownNeurons returned by the Governance canister (4 ms)
GovernanceCanister.stakeNeuron
✓ creates new neuron successfully (6 ms)
✓ stakeNeuron passes fee to the ledger transfer (5 ms)
✓ creates new neuron from subaccount successfully (5 ms)
✓ returns insufficient amount errors (31 ms) …
```

Group tests properly in governance.canister.spec.ts

---

packages/nns/README.md
packages/nns/src/governance.canister.spec.ts
packages/nns/src/governance.canister.ts

We want use ICRC-1 instead of generating account identifiers in the client.
When staking a neuron we first have to transfer the stake to a subaccount of the governance canister.
We want to use an ICRC-1 transfer to do this.
Add `stakeNeuronIcrc1` which is a copy of `stakeNeuron` with minimal changes to use `IcrcLedgerCanister` instead of `LedgerCanister`. The plan is for this to replace `stakeNeuron` once it's been properly tested in nns-dapp.
Add a copy of all the `stakeNeuron` tests and apply minimal changes to make them apply to the new `stakeNeuronIcrc1` method.
Tested manually by installing the local package in a local nns-dapp and using the new method to create a neuron. I tested increasing stake, setting dissolve delay and voting with this new neuron.

Add ICRC-1 version of stakeNeuron method

---

CHANGELOG.md
packages/nns/README.md
packages/nns/src/canisters/ledger/ledger.request.converts.ts
packages/nns/src/errors/ledger.errors.ts
packages/nns/src/ledger.canister.spec.ts
packages/nns/src/ledger.canister.ts
packages/nns/src/types/ledger_converters.ts

We want to transfer ICP using the ICRC-1 API because then we don't have to compute account identifiers in the client.
Passing the ICP ledger canister ID to the ICRC-1 API works but the ICP ledger canister has its own ICRC-1 interface so calling it directly on the ICP ledger API is cleaner.
*Note*: I started with a commit that duplicates the non-ICRC-1 code. That way you can see how the ICRC-1 code differs from the existing code by reviewing the second commit.
1. Added `icrc1Transfer` canister method.
2. Added `toIcrc1TransferRawRequest` request converter.
3. Added `mapIcrc1TransferError` error converter.
4. Added `Icrc1TransferRequest` request type.
Copied the existing tests for `transfer` and applied them to `icrc1Transfer` as far as they made sense. The new method has less custom code …

Add icrc1Transfer method to ICP ledger canister

---

packages/nns/README.md
packages/nns/src/governance.canister.spec.ts
packages/nns/src/governance.canister.ts

Staking a neuron involves transferring tokens to the neuron account.
We want to make this transfer with the ICRC-1 interface.
The ICP ledger canister now also supports the ICRC-1 interface.
When making the ICP transfer in the `stakeNeuronIcrc1` method, use the ICP ledger canister API instead of the generic ICRC-1 ledger canister API.
Updated

Use icrc1Transfer from ICP ledger in stakeNeuronIcrc1

---

packages/nns/src/canisters/ledger/ledger.request.converts.ts
packages/nns/src/ledger.canister.spec.ts

Ledger hardware wallet displays the memo as a number, even though for ICRC-1 transfer the memo is a byte array.
When the memo is not set at all, it renders the number 0, but when the empty byte array is set, it renders the number 422710814078008.
Rendering no memo as 0 seems better than rendering it as 422710814078008 and setting an empty array was done for HW compatibility in the first place so let's stop doing it.
When the memo is absent, keep it like that instead of replacing it with the empty byte array.
Unit test is updated.
Also tested manually with NNS dapp to verify that it renders memo 0 now.

Don't replace absent memo with empty memo on ICRC-1

---

packages/nns/candid/sns_wasm.certified.idl.js
packages/nns/candid/sns_wasm.d.ts
packages/nns/candid/sns_wasm.did
packages/nns/candid/sns_wasm.idl.js
packages/sns/candid/sns_governance.did
packages/sns/candid/sns_governance_test.did
packages/sns/candid/sns_root.did
packages/sns/candid/sns_swap.certified.idl.js
packages/sns/candid/sns_swap.d.ts
packages/sns/candid/sns_swap.did
packages/sns/candid/sns_swap.idl.js
packages/sns/src/index.ts
packages/sns/src/swap.canister.spec.ts

Use the new fields for the Neurons' Fund enhancements.
In this PR, upgrade the candid files for sns canisters.
Script `./scripts/import-candid ../ic`. It uses the local copy of the IC repo.
* Update candid files. Files with extension `.did`.
Script `./scripts/compile-idl-js`.
* Update related candid types and JS files.
Only the change in `src/index.ts`
* Export new type `NeuronsFundParticipationConstraints` that has the maximum commitment of the Neurons' Fund.
* Fixed a mock data with new parameters.

GIX-1909: Update candid files sns-js

---

.github/workflows/nightly.yml

Now that ledger-icp/icrc are offically published to npm, we can adjust the CI to build also their next version.

build: build ledger-icrc/icp next

---

scripts/build-next

Publishing next version failed (see https://github.com/dfinity/ic-js/actions/runs/6391122469/job/17345744326) because the script that manippulate the package.json to update the version number with the "next" prefix was not updated with the new ledger-icrc/icp libs.

build: fix next publication by integrating ledger-icrc/icp in version update script

---

CHANGELOG.md
packages/ledger-icp/src/index.ts

While integrating the new lib in NNS dapp ([PR](https://github.com/dfinity/nns-dapp/pull/3435)) we noticed that few more types need to be exposed by `@dfinity/ledger-icp`.

feat: export blockheight types

---

package.json
packages/nns/src/canisters/governance/response.converters.ts
packages/nns/src/governance_test.canister.ts
packages/nns/src/index.ts

We want to test maturity related features for NNS neurons easily.
In this PR, we expose a new GovernanceTestCanister class for the governance test canister. This canister exposes the `update_neuron` method.
* New `toRawNeuron` converter.
* New `GovernanceTestCanister` with `updateNeuron` method.
No tests. Used only for development and testing environments.

GIX-1928: Add GovernanceTest Canister and updateNeuron method

---

CHANGELOG.md
packages/sns/candid/sns_governance.did
packages/sns/candid/sns_governance_test.did
packages/sns/candid/sns_root.did
packages/sns/candid/sns_swap.certified.idl.js
packages/sns/candid/sns_swap.d.ts
packages/sns/candid/sns_swap.did
packages/sns/candid/sns_swap.idl.js
packages/sns/src/swap.canister.spec.ts

Support the new Neurons' Fund enhancements.
In this PR, we upgrade sns-js to the latest IC commit which includes two new fields in the swap canister.
Automatic changes:
* Changes in `.did` files by running `./scripts/import-candid` and then reverting the non sns-js files.
* The rest of the changes by running `./scripts/compile-idl-js`.
Fix failing test.

GIX-1934: New SNS fields for NF enhancements

---

CHANGELOG.md
packages/nns/candid/genesis_token.did
packages/nns/candid/governance.certified.idl.js
packages/nns/candid/governance.d.ts
packages/nns/candid/governance.did
packages/nns/candid/governance.idl.js
packages/nns/candid/governance_test.certified.idl.js
packages/nns/candid/governance_test.d.ts
packages/nns/candid/governance_test.did
packages/nns/candid/governance_test.idl.js
packages/nns/candid/sns_wasm.certified.idl.js
packages/nns/candid/sns_wasm.d.ts
packages/nns/candid/sns_wasm.did
packages/nns/candid/sns_wasm.idl.js
packages/nns/src/canisters/governance/request.converters.ts
packages/nns/src/governance.canister.spec.ts
packages/nns/src/types/governance_converters.ts

We want to render the new fields for Neurons' Enhancements also in the proposal action.
In this PR, update the canister types for nns-js.
* `.did` files with `./scripts/import-candid`.
* Rest of the changes inside `nns/candid` directory using `./scripts/compile-idl-js`.
* Fix governance converters with new types.
* Support new filter field for `list_proposals`.
* Add a test for `listProposal` that was missing.

GIX-1943: Upgrade canister types in nns-js

---

packages/ckbtc/candid/minter.certified.idl.js
packages/ckbtc/candid/minter.d.ts
packages/ckbtc/candid/minter.did
packages/ckbtc/candid/minter.idl.js

We want to use the ICRC-2 flow for BTC withdrawal.
This is not available in the current Candid interface we have in ic-js.
So we update minter.did to the newest version.
1. Pulled my IC repo to commit `8be68bc88db7332dd39a26509ddf62c564ca3415`.
2. Ran `scripts/import-candid ../../ic`
3. Reverted everything outside `packages/ckbtc/`
4. Ran `scripts/compile-idl-js`
5. Reverted everything outside `packages/ckbtc/`
I installed @dinifty/ckbtc from local path in nns-dapp and manually tested receiving BTC and sending ckBTC.
not necessary?

Update ckBTC Candid

---

packages/ckbtc/README.md
packages/ledger-icrc/README.md
packages/ledger-icrc/candid/icrc_index.certified.idl.js
packages/ledger-icrc/candid/icrc_index.did
packages/ledger-icrc/candid/icrc_index.idl.js
packages/ledger-icrc/candid/icrc_ledger.certified.idl.js
packages/ledger-icrc/candid/icrc_ledger.d.ts
packages/ledger-icrc/candid/icrc_ledger.did
packages/ledger-icrc/candid/icrc_ledger.idl.js

They improved the Rust code to use `Timestamp` and `BlockIndex` types instead of raw nat64 and bigint.
This PR bumps the did files of `@dfinity/ledger-icrc` but, no functionnal nor interfaces changes.

build: update ledger-icrc did files

---

CHANGELOG.md
packages/ckbtc/README.md
packages/ckbtc/src/errors/minter.errors.ts
packages/ckbtc/src/minter.canister.spec.ts
packages/ckbtc/src/minter.canister.ts
packages/ckbtc/src/types/minter.responses.ts

We want to use ICRC-2 for BTC withdrawals.
1. Add `createRetrieveBtcWithApprovalError` to convert `RetrieveBtcWithApprovalError`.
2. Add `retrieveBtcWithApproval` which calls `retrieve_btc_with_approval` on the minter canister.
3. Add unit tests for `retrieveBtcWithApproval`.
4. Unrelated: Correct a comment about the type of `subaccount` on `getBtcAddress`, which was mentioned as `Principal` but should be `Uint8Array`.
Unit tests pass.
Also tested manually by installing the local changes in nns-dapp.

Add retrieveBTCWithApproval to ckbtc minter canister

---

CHANGELOG.md
packages/nns/candid/genesis_token.did
packages/nns/candid/governance.certified.idl.js
packages/nns/candid/governance.d.ts
packages/nns/candid/governance.did
packages/nns/candid/governance.idl.js
packages/nns/candid/governance_test.certified.idl.js
packages/nns/candid/governance_test.d.ts
packages/nns/candid/governance_test.did
packages/nns/candid/governance_test.idl.js
packages/nns/src/canisters/governance/response.converters.ts
packages/nns/src/mocks/governance.mock.ts
packages/nns/src/types/governance_converters.ts

The field `is_genesis` has been reverted. Therefore, I updated the candid files to the latest commit for nns-js.
* `.did` files with `./scripts/import-candid`.
* Candid related js and type files with `./scripts/compile-idl-js`.
* Fix converters.
* Remove field from neuron mock
I removed a previous entry.

Fix: Update nns-js candid types

---

CHANGELOG.md
packages/sns/candid/sns_governance.did
packages/sns/candid/sns_governance_test.did
packages/sns/candid/sns_root.did
packages/sns/candid/sns_swap.certified.idl.js
packages/sns/candid/sns_swap.d.ts
packages/sns/candid/sns_swap.did
packages/sns/candid/sns_swap.idl.js
packages/sns/src/swap.canister.spec.ts

Support latest fields for Neurons' Fund enhancements.
In this PR, upgrade candid for sns-js
* `.did` files with `./scripts/import-candid`.
* Types and idl files related to candid: `./scripts/compile-idl-js`.
* Reverted changes in packages other than `sns`.
* Add field to mock data.
Still passing.

GIX-1960: Upgrade candid sns-js

---

CHANGELOG.md
packages/ledger-icp/README.md
packages/ledger-icp/candid/index.certified.idl.d.ts
packages/ledger-icp/candid/index.certified.idl.js
packages/ledger-icp/candid/index.d.ts
packages/ledger-icp/candid/index.did
packages/ledger-icp/candid/index.idl.d.ts
packages/ledger-icp/candid/index.idl.js
packages/ledger-icp/src/constants/canister_ids.ts
packages/ledger-icp/src/index.canister.spec.ts
packages/ledger-icp/src/index.canister.ts
packages/ledger-icp/src/index.ts
packages/ledger-icp/src/ledger.canister.spec.ts
packages/ledger-icp/src/ledger.canister.ts
packages/ledger-icp/src/mocks/ledger.mock.ts
packages/ledger-icp/src/types/common.ts
packages/ledger-icp/src/types/ledger.params.ts
packages/ledger-icp/src/utils/account_identifier.utils.ts
packages/ledger-icp/src/utils/params.utils.ts
scripts/docs.js
scripts/import-candid

Add support for ICP index canister in `@dfinity/ledger-icp`.
The ledger and the index canisters providing both a way to fetch the balance, the idea is to use the same function name and same parameters in both canister JS code.
- add did file to import candid and generate idl scripts
- init `IndexCanister`
- implement `accountBalance` function for the new canister
- refactor type `AccountIdentifier` to `AccountIdentiferHex` to avoid conflicts
- refactor `Ledger.accountBalance` params to support account identifier as hex or class

feat: init ICP index canister in ledger-icp and add account balance function

---

packages/nns/README.md

README still shows information and example about the ledger which was moved to a separate lib recently.

docs: update outdated nns-js README

---

packages/nns/src/canisters/governance/response.converters.ts
packages/nns/src/types/governance_converters.ts

There were some fields not appearing in the proposal to open an SNS.
The problem was that the fields were considered optional, and the types didn't catch when they were missing from the converters.
Instead, I used the `Option` utility, to ensure that fields are present, but can be `undefined`.
* Change optional fields to use `Option` in `SwapParameters` of the `CreateServiceNervousSystem`.
* Add missing fields in the converter of the `SwapParameters` of the `CreateServiceNervousSystem`.
After changing the type to `Option`, I run the tests and they were failing to compile because the types didn't match. After adding the fields, the tests pass again.
It was already in the changelog. But the feature was incomplete.

Fix: Add missing swap parameters to SNS proposal action

---

CHANGELOG.md
packages/ledger-icp/README.md
packages/ledger-icp/src/errors/index.errors.ts
packages/ledger-icp/src/index.canister.spec.ts
packages/ledger-icp/src/index.canister.ts
packages/ledger-icp/src/index.ts
packages/ledger-icp/src/types/index.params.ts

Add support to fetch transactions with the ICP Index canister.
- introduce `get_account_identifier_transactions`

feat: ICP index canister getTransactions

---

package.json
packages/ledger-icrc/README.md
packages/utils/README.md
packages/utils/src/index.ts
packages/utils/src/utils/date.utils.spec.ts
packages/utils/src/utils/date.utils.ts

We use the `secondsToDuration` we have built for NNS dapp also in other apps such as Oisy Wallet and VRC.
Therefore it makes sense to move the function to the utils.
- move `secondsToDuration` (no functional changes, just move)
- adapt it to accept a record of languages to support i18n
- default to english

feat: seconds to duration

---

CHANGELOG.md
scripts/import-candid

When candid is imported, the source commit is added to the top of the imported candid files.  This is useful, but the commit date and tags are also useful and it would be convenient if they were included.
* Add the commit date after the IC commit.
* Add any tags on the IC commit.
* Shorten the commit.  (Entirely optional - I worried about the line getting too long but it may be fine.)
The annotation changes like this, if the commit is tagged:
```
-// Generated from IC repo commit ec140b74dc4fef2f4bee3fad936e315380fa5af3 'rs/bitcoin/ckbtc/minter/ckbtc_minter.did' by import-candid
+// Generated from IC repo commit ec140b74dc (2023-11-08 tags: release-2023-11-08_23-01) 'rs/bitcoin/ckbtc/minter/ckbtc_minter.did' by import-candid
```
and without tags:
```
-// Generated from IC repo commit …
```

feat: Include tags in label

---

.github/workflows/checks.yml
CHANGELOG.md
packages/ckbtc/candid/minter.d.ts
packages/cmc/candid/cmc.d.ts
packages/ic-management/README.md
packages/ic-management/candid/ic-management.d.ts
packages/ledger-icp/candid/index.d.ts
packages/ledger-icp/candid/ledger.d.ts
packages/ledger-icrc/README.md
packages/ledger-icrc/candid/icrc_index.d.ts
packages/ledger-icrc/candid/icrc_ledger.d.ts
packages/ledger-icrc/src/utils/ledger.utils.ts
packages/nns/candid/governance.d.ts
packages/nns/candid/governance_test.d.ts
packages/nns/candid/sns_wasm.d.ts
packages/nns/src/canisters/governance/response.converters.ts
packages/sns/candid/sns_governance.d.ts
packages/sns/candid/sns_governance_test.d.ts
packages/sns/candid/sns_root.d.ts
packages/sns/candid/sns_swap.d.ts
packages/sns/src/sns.wrapper.ts
packages/sns/src/types/actions.ts
packages/sns/src/types/governance.params.ts
scripts/compile-idl-js

Keep tools up to date.
In this PR, upgrade `didc` to latest version `0.3.5`.
The change is that types of `Uint8Array` are now `Uint8Array | number[]`.
Which means that in some places I had to convert to `Uint8Array` to have a common type for simplicity.
* All files in `*/candid/*` directories. By running `compile-idl-js` with the new `didc` version.
* Readme files with the docs workflow.
* `compile-idl-js` to expect latest `didc`.
* Convert types `Uint8Array | number[]` to `Uint8array` with `Uint8Array.from` where needed.
Still passing.

Chore: Upgrade didc

---

CHANGELOG.md
packages/ckbtc/src/errors/minter.errors.ts
packages/ckbtc/src/index.ts
packages/ckbtc/src/minter.canister.spec.ts

When we call `update_balace` on the ckBTC minter, it will credit deposited BTC from transactions with at least 12 confirmations.
If there are no new transactions with at least 12 confirmations, it will return an error.
If there are transactions with fewer than 12 confirmations, the error will contain the pending UTXOs of those transaction.
Forward the pending UTXOs returned by the minter, in the mapped error.
Existing unit test has been updated.

Expose pending UTXOs returned by the minter

---

ADMIN.md

Improve docs.
* Changes in ADMIN.md
Only docs changes.
Not necessary.

Chore: Improve admin docs

---

CHANGELOG.md
packages/nns/src/canisters/governance/response.converters.ts
packages/nns/src/types/governance_converters.ts

Using `?` is not the same as `Option`. With `?` the field is optional, but with `Option`, the field is mandatory, but the value can be `undefined`.
This small distinction is important when we render the information of proposals in NNS Dapp. We convert the actions to camelcase and remove `[] | [T]`.
If we use `?`, we might forget to convert it and it will never show up in NNS Dapp. By using `Option`, we make sure that the field will always we present in the converters.
You can see the example in the `params`, `maxDirectParticipationIcpE8s` and `minDirectParticipationIcpE8s` fields for the (deprecated) `OpenSnsTokenSwap` proposal action that I had to change when I moved from `?` to `Option`.
* Change the `?` in `types/governance_converters.ts` for `Option`. Only for the fields related to …

Chore: Change "?" for "Option" for optional fields

---

CHANGELOG.md
packages/ckbtc/README.md
packages/ckbtc/src/index.ts
packages/ckbtc/src/minter.canister.spec.ts
packages/ckbtc/src/minter.canister.ts

To query the status of a BTC withdrawal the ckBTC minter has a method called `retrieve_btc_status`.
Expose `retrieveBtcStatus` on the minter canister.
Unit test added.
Tested manually in NNS dapp.

Add retrieveBtcStatus to ckbtc minter

---

.github/workflows/update-ic.yml
.gitignore
CHANGELOG.md
scripts/import-candid

We wish to keep the Internet Computer bindings up to date.
* Create a cron job that periodically checks for new IC releases
* On discovering a release with a meaningful change, the job creates a PR with updated .did files and typescript bindings.
* Created PRs by pushing this branch
* Note: The PRs did not pas CI because some manual changes were needed in addition to reflect the updated bindings.

Workflow to update IC

---

CHANGELOG.md
packages/utils/README.md
packages/utils/src/utils/arrays.utils.spec.ts
packages/utils/src/utils/arrays.utils.ts

Candid changed what used to be `Uint8Array` to `Uint8Array | number[]`.
This means we often have to convert a field to `Uint8Array` just to get rid of the `| number[]` bit.
To make this slightly less painful we can make some functions accept both.
Make `uint8ArrayToHexString` accept both `Uint8Array | number[]`.
I considered changing the name but in that case I don't think it's worth it anymore. What do you think?
Unit test added

Support number[] in uint8ArrayToHexString

---

packages/nns/README.md
packages/nns/src/canisters/governance/services.ts
packages/nns/src/governance.canister.spec.ts
packages/nns/src/governance.canister.ts

`makeProposal` returns currently void which is a bit inconvenient if the caller needs to know which proposal was created which happens to be the case in the small proof of concept I was developing.
Therefore this PR extends the function to return the potential ID of the proposal that was created.
Given the fact that the answer of the Governance canister is a variant I hesitated between returning `Promise<bigint | undefined>` or `{success: boolean; proposalId?: bigint}`. Given the fact that there was no use cases where `success: false^ would be set, I opted for the first simple solution.
- return `Command_1` for `manageNeuron`
- return the proposal ID for `makeProposal`
- make other functions that uses `manageNeuron` continue returning `void`

feat: makeProposal return created proposal ID

---

CHANGELOG.md
packages/utils/README.md
packages/utils/src/enums/token.enums.ts
packages/utils/src/parser/token.spec.ts
packages/utils/src/parser/token.ts

Some tokens (like ckETH) have a precision different than 8 decimals.
In this PR, support decimals precision in the new TokenAmountV2 class.
* Add mandatory field `decimals` in `Token` type.
* Add `decimals` to ICPToken.
* `TokenAmount` rejects tokens with `decimals !== 8`
*  New type `TokenAmountV2` which supports `decimals !== 8`
* Test that `TokenAmount` does not support different decimals.
* Test that TokenAmountV2 supports different decimals.

GIX-2154: Add support for token decimals in TokenAmount

---

packages/utils/README.md
packages/utils/src/parser/token.spec.ts
packages/utils/src/parser/token.ts

`TokenAmountV2` doesn't use e8s.
Change `fromE8s` to `fromUlps` on `TokenAmountV2`.
Updated accordingly
not necessary

Rename fromE8s to fromUlps

---

packages/ledger-icp/src/index.canister.ts

IDL paths for IndexCanister are pointing to ledger canister idls instead of Index
Bug fix, regression, IDL paths in Index Cannister are pointing to Ledger instead of Index.
Updated loading path info for IDLs

Bug Fix: IDL paths to Index from Ledger

---

CHANGELOG.md
package.json
packages/utils/README.md
packages/utils/src/parser/token.spec.ts
packages/utils/src/parser/token.ts

TokenAmountV2 can't convert small numbers such as `0.00000002` which is 2 e8s of ICP.
The problem was that `fromNumber` was using `toString` and `toString` was converting `0.00000002` to the scientific notation. Which we specifically don't want to support when converting from a string.
Solution, use `toFixed(8)` instead of `toString`. We already support only a precision of 8 decimals.
* Use `toFixed(8)` instead of `toString` in `fromNumber` of TokenAmountV2.
* Change test `"does not support scientific notation"` to do it `fromString`.
* Add tests for 8 decimals.
* Add a test for `fromNumber` with very small numbers.
* Add test for `fromNumber` to check that precision is 8 decimals.

Fix: Support converting small number to AmountTokenV2

---

CHANGELOG.md
packages/ledger-icp/src/index.canister.ts
packages/ledger-icp/src/utils/params.utils.ts

Utilize ICP Index `accountBalance` and `getTransactions` with account identifier hex directly, eliminating the need for conversion with Buffer and resolving usage in non-polyfilled environments.
- if hex, use hex directly without converting first to an account identifier
Oisy Wallet PR https://github.com/dfinity/oisy-wallet/pull/497 and potentially a bug we will face in NNS dapp as well in the future.

fix: utilize ICP Index `accountBalance` and `getTransactions` with account identifier hex directly

---

CHANGELOG.md
packages/ckbtc/README.md
packages/ckbtc/src/minter.canister.spec.ts
packages/ckbtc/src/minter.canister.ts
packages/ckbtc/src/types/minter.responses.ts

I want to use this to display BTC withdrawal transactions in nns-dapp as pending or failed when appropriate.
Unit tests added.
Tested manually in an nns-dapp branch.

Add retrieveBtcStatusV2ByAccount to ckbtc canister

---

CHANGELOG.md
packages/utils/src/utils/agent.utils.ts

`https://icp-api.io` is recommended over `https://ic0.app` as host given that all canisters are accessible on the first.

feat: defaultAgent host

---

CHANGELOG.md
package-lock.json
package.json
packages/ledger-icp/README.md
packages/ledger-icp/package.json
packages/ledger-icp/src/account_identifier.spec.ts
packages/ledger-icp/src/account_identifier.ts

It was reported that the last version of NNS dapp shipped with SvelteKit v2 and per extension Rollup v4 was not usable on iOS 15 (iOS 17 was fine). Afternarrowing down the issue I figured out that the root cause of the issue was the usage of a static variable using within an object parameter.
```
Unhandled Promise Rejection: SyntaxError: Unexpected token '{'
```
- Replace static usage of `SubAccount.ZERO` with an object to fix the issue
- Add entry in CHANGELOG
- Bump version to release the patch to npm asap.
The fix was tested locally by bundling the library and including it in NNS dapp which was build and served `npx serve public` + `npx local-ssl-proxy --source 3001 --target 3000`. Finally the fix was validated by loading https://locahost:3001 in Xcode simulator with iOS 15.4.

fix: iOS 15 usage and bump version

---

packages/cketh/README.md
packages/cketh/src/errors/minter.errors.ts
packages/cketh/src/index.ts
packages/cketh/src/minter.canister.spec.ts
packages/cketh/src/minter.canister.ts
packages/cketh/src/mocks/minter.mock.ts

Add support for `withdraw_eth` in `@dfinity/cketh` library.
Pattern is really similar to ckBTC `retrieveBtcWithApproval`, kind of copy/paste + search and replace.
- Implement `withdrawEth` and related result errors
- Expose errors and success types in `index.ts`

feat: support for withdraw_eth

---

packages/ckbtc/README.md
packages/ckbtc/src/minter.canister.ts

My documentation lib [tsdoc-markdown](https://github.com/peterpeterparker/tsdoc-markdown) does not manipulate the documentation to prefix potentital markdown title with the actual parent title. So using `#` in a doc comment ends up in a main title. Long story short, this PR just modify a doc comment to remove two `#`.

docs: replace ckbtc code doc title per for note

---

CHANGELOG.md
packages/ic-management/README.md
packages/ic-management/candid/ic-management.certified.idl.js
packages/ic-management/candid/ic-management.d.ts
packages/ic-management/candid/ic-management.did
packages/ic-management/candid/ic-management.idl.js
packages/ic-management/src/ic-management.canister.spec.ts
packages/ic-management/src/types/ic-management.params.ts

Upgrade ic-management candid files that have some changes that break the pipeline even though they are backwards compatible.
This breaking of the pipeline prevents the bot from making PRs that can be merged without manual changes.
* "ic-management.did" file with `./scripts/import-candid ../ic`. In this step, I removed the changes in all the other candid files.
* "ic-managment.certified.idl.js", "ic-management.d.ts", "ic-management.idl.js" files with "./scripts/compile-idl-js"
* "README.md" the documentation bot.
* Changelog
* Add new optional field to `toCanisterSettings`.
* Change the return of `toInstallMode` for the `InstallMode.Upgrade`. In another PR, we might want to add a new field to InstallMode enum to support new functionality.
* Fix tests expecting new optional field.

Chore: Upgrade candid IC-Managment canister

---

packages/cketh/src/minter.canister.ts

ckETH should not reference ckBTC. I guess copy/paste or incorrect auto import lead to important the did service factory declaration from the other package.

fix: ckETH lib incorrectly reference ckBTC

---

packages/cketh/src/minter.canister.ts

Direct import is cleaner than referencing the factory through the namespace. Follow-up of #517.

feat: ckETH factory import direct

---

CHANGELOG.md
packages/utils/README.md
packages/utils/src/parser/token.ts

To add arbitrary ICRC we need to rely on getting the logo from the Ledger Canister metadata. Let's store it in the `Token` with the rest of the metadata.
* Add `logo` to `Token` type in utils.
Still passing.

Feat: Add "logo" param to "Token"

---

CHANGELOG.md
packages/cmc/candid/cmc.certified.idl.js
packages/cmc/candid/cmc.d.ts
packages/cmc/candid/cmc.did
packages/cmc/candid/cmc.idl.js
packages/cmc/src/cmc.canister.spec.ts

Update candid files for CMC and fix the test failure with the new cmc candid files.
This way the bot can make PRs that can be fixed without further intervention.
The new candid types are a breaking change for the `notifyCreateCanister` method.
* Changes in "*/cmc/candid/*.did" from running script `/scripts/import-candid`.
* Changes in "/cmc/candid/*" from running script `/scripts/compile-idl-js`.
* The test in cmc.canister.spec `"CMCCanister.notifyCreateCanister"` was failing because the new parameters were not being passed.

Chore: Upgrade candid files for cmc

---

CHANGELOG.md
packages/sns/candid/sns_governance.certified.idl.js
packages/sns/candid/sns_governance.d.ts
packages/sns/candid/sns_governance.did
packages/sns/candid/sns_governance.idl.js
packages/sns/candid/sns_governance_test.certified.idl.js
packages/sns/candid/sns_governance_test.d.ts
packages/sns/candid/sns_governance_test.did
packages/sns/candid/sns_governance_test.idl.js
packages/sns/candid/sns_root.certified.idl.js
packages/sns/candid/sns_root.d.ts
packages/sns/candid/sns_root.did
packages/sns/candid/sns_root.idl.js
packages/sns/candid/sns_swap.certified.idl.js
packages/sns/candid/sns_swap.d.ts
packages/sns/candid/sns_swap.did
packages/sns/candid/sns_swap.idl.js
packages/sns/src/swap.canister.spec.ts

Update sns-js candid files so that the bot can update the files without manual intervention.
* [First commit](https://github.com/dfinity/ic-js/pull/528/commits/dc20f3445b8ea70c43724a656429c702f33b1f8d): Changes after running "./scripts/import-candid ../ic" and reverting the changes outside the "packages/sns".
* [Second commit](https://github.com/dfinity/ic-js/pull/528/commits/b518b51b2e582b36c3a2e3336f22137c4aa6e869): Changes after running "./scripts/compile-idl-js".
There was a test failure after the automatic changes in swap.canister.spec: `"should return the lifecycle state of the swap canister"`.
* [Third commit](https://github.com/dfinity/ic-js/pull/528/commits/3f25e9701f7bbe0d6a1b0c4fdb63f0f779e11c1a): Add new field in response of `get_lifecycle`.

Chore: Upgrade candid files for sns-js

---

CHANGELOG.md
packages/utils/README.md
packages/utils/src/parser/token.spec.ts
packages/utils/src/parser/token.ts

Support formatting e8s for tokens that have different decimals than 8.
* Add method `toE8s` to `TokenAmountV2`.
* Add tests for new method.

Feat: Add `toE8s` to TokenAmountV2

---

CHANGELOG.md
packages/ckbtc/candid/minter.certified.idl.js
packages/cketh/candid/minter.certified.idl.js
packages/ic-management/candid/ic-management.certified.idl.js
packages/ledger-icp/candid/ledger.certified.idl.js
packages/sns/candid/sns_root.certified.idl.js
scripts/compile-idl-js

Few canisters functions are using the keyword "query" in their name - e.g. `fn query_stats()`.
Given that our command line parser to generate the certified IDL JS/TS files optimistically removes the keyword `query`, such functions ended being delivered with trimmed names - e.g. `fn _stats()`.
- instead of replacing `query`, replace `query;` given that we want to remove the query keyword of the service function in the did files which always ends with a `;`.

fix: certified IDL factory using keyword "query"

---

CHANGELOG.md
packages/ckbtc/README.md
packages/ckbtc/src/index.ts
packages/ckbtc/src/minter.canister.spec.ts
packages/ckbtc/src/minter.canister.ts
packages/ckbtc/src/types/minter.params.ts

Extend ckBTC `retrieveBtcStatusV2ByAccount` with optional account param for consistency reason (other functions expose an optional account) and also because it can be useful to some devs.
- add optional `account` parameter to `retrieveBtcStatusV2ByAccount`

feat: extend retrieveBtcStatusV2ByAccount with optional account param

---

packages/nns/src/enums/governance.enums.ts

Extend NnsFunctions enum with new BoundaryNodes related types.
`nns-dapp` related pr https://github.com/dfinity/nns-dapp/pull/4310
- NnsFunctions update
Works
Not necessary

Add new Boundary Node NnsFunctions

---

CHANGELOG.md
package-lock.json
package.json
packages/nns/src/canisters/governance/response.converters.ts
packages/utils/src/types/actor-type.utils.ts

Maintenance.
- bump all dev dependencies (except TypeScript, lint requires < 5.3)
- continue to use gzip for size-limit comparison (instead of brotlie which is the new default in the tool)

build: bump all dev dependencies

---

CHANGELOG.md
packages/nns/src/canisters/governance/request.converters.ts
packages/nns/src/canisters/governance/response.converters.ts
packages/nns/src/types/common.ts
packages/nns/src/types/governance_converters.ts

Saturday evening, a dev shared an issue on the [forum](https://forum.dfinity.org/t/calculating-subaccounts-from-principal-agent-js/18849/8?u=peterparker) hich was resolved by using the appropriate types. `@dfinity/nns` exposes two types, `AccountIdentifier` and `SubAccount`, that duplicate the effective classes in `@dfinity/ledger-icp`. So, the issue was solved by importing the types from the latest library. To avoid confusion in the future, let's remove those historical types.
- Replace duplicate string type `AccountIdentifier` in `@dfinity/nns` with `AccountIdentifierHex` of `@dfinity/ledger-icp`.
- Remove unused Uint8Array type `SubAccount` in `@dfinity/nns`.

feat: clean-up nns duplicate AccountIdentifier and Subaccount types

---

package-lock.json
package.json
test-setup.ts

`whatwg-fetch` was historically added and used as a dev dependency and to mock some properties for test but we, gix team, never used it. Therefore this PR removes it.

build: remove whatwg-fetch dev dependency

---

package-lock.json

Looks like there was a local dependency leftover in `package-lock` of some `tsdoc-markdown` debugging.
- remove unused local path to `tsdoc-markdown` (we used the lib fetched from npm)

build: clean package-lock of unused local dependency

---

.github/workflows/checks.yml

For forked PRs the github token is not passed in, so it causes the workflow to get stuck.
For PRs made from within the org it will continue to work as-is. For PRs from external contributors we won't pass in the secret. It's possible the CLA could get stuck (what we were originally trying to prevent) and they will need to push an empty commit.

Handle forked PRs differently

---

packages/ledger-icp/src/account_identifier.spec.ts
packages/ledger-icp/src/account_identifier.ts

I am having a scenario where I need to handle more than 256 subaccounts. This is my workaround for now:
```
const principal = identity.getPrincipal()
const generatedAccountId = AccountIdentifier.fromPrincipal({
principal,
subAccount: SubAccount.fromBytes(numberToUint8Array32(newIndexNumber)),
})
```
where `numberToUint8Array32` is the updated `fromID` method.
Updates the `SubAccount.fromID` method to handle up to nine quadrillion subaccounts (which is the max safe int).
It creates a buffer of 32 bytes and uses `writeBigInt64BE` to write the `id` using a 24 offest.
Added one more test for `fromID` method under `account_identifier.spec.ts`. All tests are passing.
- Enjoy!

feat: update SubAccount.formID to handle bigger numbers

---

CHANGELOG.md
packages/sns/README.md
packages/sns/candid/sns_governance.certified.idl.js
packages/sns/candid/sns_governance.d.ts
packages/sns/candid/sns_governance.did
packages/sns/candid/sns_governance.idl.js
packages/sns/candid/sns_governance_test.certified.idl.js
packages/sns/candid/sns_governance_test.d.ts
packages/sns/candid/sns_governance_test.did
packages/sns/candid/sns_governance_test.idl.js
packages/sns/src/governance.canister.spec.ts
packages/sns/src/governance.canister.ts
packages/sns/src/sns.wrapper.ts

Update `listProposals` return type to make available `include_ballots_by_caller` flag (**Breaking Change!**). The flag is needed to differentiate between upgraded canisters that fully supports ballots and w/o support.
- upgrade sns candids and types
- adjust return type in the source
- the `listProposals` should not break when there is no `include_ballots_by_caller` flag provided from the backend (not upgraded canisters don't deliver the flag)

Upgrade nns governance candid 2024 02 19

---

package-lock.json
packages/ckbtc/package.json
packages/cketh/package.json
packages/cmc/package.json
packages/ic-management/package.json
packages/ledger-icp/package.json
packages/ledger-icrc/package.json
packages/nns/package.json
packages/sns/package.json
packages/utils/package.json

A [critical security issue](https://github.com/dfinity/agent-js/security/advisories/GHSA-c9vv-fhgv-cjc3) was patched in agent-js v1.0.1.
Affected version of agent-js are v0.20.x, v0.21.x and v1.0.0. We are currently using v0.20.2.
While NNS dapp is **not** impacted, it is important that we bump and rollout a version of ic-js to help the community upgrade without the need to use the npm `--force` flag (it has already been requested on the [forum](https://forum.dfinity.org/t/agent-js-v1-0-0-is-released/27553/4?u=peterparker)).
- bump agent-js v1.0.1

build: bump agent-js v1.0.1 - security patch

---

packages/ckbtc/README.md
packages/ckbtc/src/minter.canister.ts

Spotted a typo in the description of ckBTC `getMinterInfo`. Probably due to a copy paste originaly.

docs: typo in query params description for ckBTC getMinterInfo

---

CHANGELOG.md
packages/ic-management/README.md
packages/ic-management/src/ic-management.canister.ts
packages/ic-management/src/types/ic-management.params.ts

Fix typo.
- search and replace `senderCanisterVerion` -> `senderCanisterVersion`

fix: typo in ic-management interfaces (senderCanisterVerion -> senderCanisterVersion)

---

CHANGELOG.md

It isn't a JS breaking change but, there is an additional parameter in `GetTransactionsResponse` which can lead to a TypeScript issue if not assigned. So this PR documents it.
Discovered with NNS dapp CI: https://github.com/dfinity/nns-dapp/actions/runs/8140257404/job/22245101959?pr=4586

docs: list TypeScript breaking change in ledger-icrc

---

CHANGELOG.md

Mentionning the `IndexNgCanister` as a new feature is missing in the CHANGELOG.

docs: add IndexNgCanister to CHANGELOG

---

packages/cketh/src/minter.canister.spec.ts

When running tests in `ic-js`, I noticed this error:
```
Test Suites: 2 passed, 2 total
Tests:       16 passed, 16 total
Snapshots:   0 total
Time:        0.911 s, estimated 1 s
Ran all test suites.
/Users/dskloet/dev/ic-js/tree2/node_modules/expect/build/index.js:113
const err = new JestAssertionError();
^
JestAssertionError: expect(received).rejects.toThrowError()
Received promise resolved instead of rejected
Resolved to value: {"gas_limit": 21000n, "max_fee_per_gas": 122272445514n, "max_priority_fee_per_gas": 1500000000n, "max_transaction_fee": 2567721355794000n, "timestamp": [1709707209241181133n]}
at expect (/Users/dskloet/dev/ic-js/tree2/node_modules/expect/build/index.js:113:15)
at Object.<anonymous> (/Users/dskloet/dev/ic-js/tree2/packages/cketh/src/minter.canister.spec.ts:237:7) …
```

Fix async ckETH test

---

packages/ckbtc/src/index.ts

`UpdateBalanceOk` which wraps `Utxo` is exposed in ckBTC-js but, the latest, `Utxo`, isn't. Therefore this PR exposes thoses types.

feat: expose utxo types

---

packages/ic-management/candid/ic-management.certified.idl.js
packages/ic-management/candid/ic-management.d.ts
packages/ic-management/candid/ic-management.did
packages/ic-management/candid/ic-management.idl.js

This PR updates the did files of `@dfinity/ic-management` as provided in #574. The changes come from the specification [#272](https://github.com/dfinity/interface-spec/pull/272). Given that the library does not expose installing chunked code yet (I opened a TODO #575) we can I think update the types without further notice.

build: update ic-mgmt candid files

---

CHANGELOG.md
packages/ic-management/README.md
packages/ic-management/src/ic-management.canister.spec.ts
packages/ic-management/src/ic-management.canister.ts
packages/ic-management/src/index.ts
packages/ic-management/src/types/ic-management.params.ts

Add support for installation of large Wasm modules to `@dfinity/ic-management`. The feature has been rolled out in dfx few weeks ago and was often requested by Azle developers. Not sure there are that much devs that need this with our library but that way the tooling is up-to-date everywhere given. that we already support `installCode`.
Nothing that particular in the implementation, it follows the existing code base. Only particularity is probably `installChunkedCode` which accepts a hash as `Uint8array or number[]` as defined by did but als as `string` hex because most probably it is the type of hash that will effectivelly be used by a consumer - i.e. a human readable hash.
- add support for IC mgmt `upload_chunk`, `clear_chunk_store`, `stored_chunks` and `install_chunked_code`

feat: support for install_chunked_code in ic-mgmt

---

CHANGELOG.md
package-lock.json
package.json
packages/ckbtc/package.json
packages/cketh/package.json
packages/cmc/package.json
packages/ic-management/package.json
packages/ledger-icp/package.json
packages/ledger-icrc/package.json
packages/nns-proto/package.json
packages/nns/package.json
packages/sns/package.json
packages/utils/package.json

I want to prepare a release of Oisy for mainnet in which I like to embed only released version of ic-js. Therefore the motivation behind releasing ic-js.
- bump versions according their respective changes
- add overview to CHANGELOG
- add interesting entry in CHANGELOG according git history

chore: bump next version and prepare release

---

CHANGELOG.md
package-lock.json
package.json
packages/ic-management/README.md
packages/ic-management/package.json
packages/ic-management/src/ic-management.canister.ts

There was an incorrect import path `@dfinity/utils/src` in ic-management. Probably side effect of auto-import of webstorm.
Some day I should take the time to setup an eslint rule to detect those.
- fix import
- prepare patch release

fix: incorrect import path in ic-mgmt

---

.eslintrc.json
packages/ic-management/src/ic-management.canister.ts

There was an issue in release [2024.03.25-1345Z](https://github.com/dfinity/ic-js/releases/tag/2024.03.25-1345Z) because one function was imported as `@dfinity/utils/src` which works fine when the workspace is build but, can lead to issue when used in a dapp. In that case I noticed the error in Oisy.
Given that it was not the first time it happens, thanks Webstorm and other editor auto-import features, this PR provides an eslint rule which aims to detect those type of import to prevent the issue to happen.
- new eslint rule `no-restricted-imports`
Validated locally and in the CI: https://github.com/dfinity/ic-js/actions/runs/8421833902/job/23059661608?pr=590

chore: lint rules to prevent import from @dfinity/*/src

---

CHANGELOG.md
packages/ledger-icp/candid/index.certified.idl.js
packages/ledger-icp/candid/index.d.ts
packages/ledger-icp/candid/index.did
packages/ledger-icp/candid/index.idl.js
packages/ledger-icp/candid/ledger.did
packages/ledger-icp/src/index.canister.spec.ts
packages/ledger-icrc/candid/icrc_index-ng.did
packages/ledger-icrc/candid/icrc_index.did
packages/ledger-icrc/candid/icrc_ledger.did

ICP transactions, as provided by the Index canister, have been extended to include their block timestamp information.
Ran the following to update all candid and then undo everything except the `ledger-icp` package.
```
scripts/import-candid ../../ic
scripts/compile-idl-js
git checkout packages/{sns,nns,ic-management,cmc,cketh,ckbtc}
```
Included transaction data in the test transactions in the unit test.
The transactions are returned exactly as returned from the canister but this should help with test coverage in case that ever changes in the future.

Update candid in ledger-icp package

---

packages/ic-management/candid/ic-management.certified.idl.js
packages/ic-management/candid/ic-management.d.ts
packages/ic-management/candid/ic-management.did
packages/ic-management/candid/ic-management.idl.js
packages/ic-management/src/types/ic-management.params.ts

A type `canister_install_mode` was added in the ic-mgmt did file which can replace the type declared within the library `InstallModeParam`.
- update did and replace type (which is not exposed)

refactor: type canister_install_mode replaces InstallModeParam

---

CHANGELOG.md
packages/ledger-icp/README.md
packages/ledger-icp/src/ledger.canister.spec.ts
packages/ledger-icp/src/ledger.canister.ts

The NNS dapp now requires version 2.4.9 of the Internet Computer Ledger app.
See for context: https://forum.dfinity.org/t/nns-dapp-to-remove-protobuf-dependency-upgrade-your-ledger-ic-app-to-2-4-9/27712
This means that we no longer need to use a separate code path with protocol buffers when making hardware wallet transactions but can instead use the exact same code path as for normal transactions.
One more thing that's different between hardware wallet transactions and normal transactions is that if you don't specify a fee, we make a call to fetch the fee, except when you use a hardware wallet, in which case we use a hard coded default fee of 10,000 e8s.
According to the interface documentation, this is the [only allowed value](https://github.com/dfinity/ic/blob/bfbd6755bff274c2d0b97d6a33e …

NNS1-2886: Don't fetch ICP fee when not specified

---

CHANGELOG.md
packages/ledger-icp/README.md
packages/ledger-icp/src/canisters/ledger/ledger.request.converts.ts
packages/ledger-icp/src/errors/ledger.errors.ts
packages/ledger-icp/src/ledger.canister.spec.ts
packages/ledger-icp/src/ledger.canister.ts

The NNS dapp now requires version 2.4.9 of the Internet Computer Ledger app.
See for context: https://forum.dfinity.org/t/nns-dapp-to-remove-protobuf-dependency-upgrade-your-ledger-ic-app-to-2-4-9/27712
This means that we no longer need to use a separate code path with protocol buffers when making hardware wallet transactions but can instead use the exact same code path as for normal transactions.
NNS-dapp already doesn't use hardware wallet specific code paths since https://github.com/dfinity/nns-dapp/pull/4373
1. Remove all code paths in `packages/ledger-icp` that check `this.hardwareWallet`.
2. Remove all functions that became unused as a result.
Remove hardware wallet specific unit tests.

NNS1-2886: Remove hardware wallet specific code paths from ledger-icp

---

CHANGELOG.md
packages/ledger-icp/README.md
packages/ledger-icp/src/ledger.canister.ts
packages/ledger-icp/src/types/ledger.options.ts

`dfinity/ledger-icp` now uses the same code path for hardware wallet transaction and normal transaction.
The `LedgerCanister` factory method still accepts some options specific to hardware wallet code that no longer exists.
Remove the obsolete options.
Still pass.

NNS1-2886: Remove hardwallet options from ledger-icp

---

CHANGELOG.md

For consistency reasons, in CHANGELOG:
- Move "Breaking changes" as first chapter of the next  release.
- Inline entries.

docs: display breaking changes first in changelog

---

.github/workflows/checks.yml
.github/workflows/update-ic.yml
CHANGELOG.md
scripts/compile-idl-js

I've been using didc v0.3.7 for some time and I'm tired of having to switch tools just for this repository. Therefore, this PR bumps didc to v0.3.7.
Compared to v0.3.5, didc v0.3.7 generates nicer service interfaces. Interfaces which are for example useful when one install a canister in JS as they can import the `init` types.
- bump didc v0.3.7 in GitHub Actions
- set min required version to 0.3.7

build: upgrade didc v0.3.7

---

.github/workflows/next.yml

Whenever we make changes to ic-js, we almost always do a manual "Next Publication" in order to pull the new changes into another repo.
Having an addition "Next Publication" every night does not really provide value.
And not having frequent next publications actually makes it easier to see when you've forgotten to do a publication before updating the gix-components dependency in another repo.
1. Remove the scheduled runs of "Next Publication".
2. Rename `nightly.yml` to `next.yml` to reflect the purpose more accurately.

Do not publish 'next' every night.

---

CHANGELOG.md
packages/cketh/candid/minter.certified.idl.js
packages/cketh/candid/minter.d.ts
packages/cketh/candid/minter.did
packages/cketh/candid/minter.idl.js
packages/cketh/src/minter.canister.spec.ts

The field `smart_contract_address` has been added back (and marked as deprecated) in the `minter_info` of ckETH.
- bump candid files
- redo field in test mock data
- update CHANGELOG to transform "breaking changes" into a "features" entry

feat: redo smart_contract_address in ckETH minterInfo

---

packages/ledger-icrc/src/index-ng.canister.spec.ts

I guess there was a merge conflicts at some point, I spotted two tests that were duplicated.
- Remove duplicate suite `describe(balance)` in Index canister test.

chore: remove duplicated tests

---

CHANGELOG.md
packages/ic-management/README.md
packages/ic-management/src/ic-management.canister.spec.ts
packages/ic-management/src/ic-management.canister.ts
packages/ic-management/src/types/ic-management.params.ts
packages/ic-management/src/types/ic-management.responses.ts

Ic-mgmt `canisterInfo` cannot be called by users. According @mraszykt he only way to call this function is to proxy the call via a cycles wallet. Per extension, exposing the feature in ic-js leads to some confusion (which happened to be the case today even by employee of the foundtion). Therefore, let's remove it.
- remove `canisterInfo` in `@dfinity/ic-management`

feat: remove canisterInfo

---

packages/nns/src/enums/governance.enums.ts

There is a new proposal type to rent subnets, using NNS function 52.
Add `SubnetRentalRequest` value to `NnsFunction` enum.
not tested
not added

Add SubnetRentalRequest NnsFunction

---

CHANGELOG.md
packages/nns/src/enums/governance.enums.ts

The new proposal type to rent subnets, has its own topic.
Add topic `SubnetRental` to `Topic` enum.
not tested

Add SubnetRental to Topic enum

---

README.md
packages/ledger-icp/README.md
packages/nns/README.md

Keep readme files up to date. The nns-proto is not needed anymore for nns-js and ledger-icp
* Remove the mention of nns-proto in the installation steps of nns-js and ledger-icp as well as the main readme file.
Not necessary.

Remove nns-proto dep from readme files

---

CHANGELOG.md
packages/utils/README.md
packages/utils/src/parser/token.spec.ts
packages/utils/src/parser/token.ts

When creating a `TokenAmountV2` from a `number`, we first convert it to a string with 8 decimals.
When the number has more decimals, they are just truncated. But number input components in gix-components don't allow more than 8 decimals.
But when the token allows fewer than 8 decimals, this results in an error.
The happened to be one of the few combinations without a unit test but will be needed for ckUSDC.
When converting the number to a string with a fixed number of decimals, instead of always using 8 decimals, use the minimum of 8 and the number of decimals the token allows.
1. Added a unit test.
2. Tested in NNS dapp that this error no longer appears:

Fix TokenAmountV2.fromNumber for decimals < 8

---

.github/workflows/docs.yml

I faced today the same error as the one I noticed in ic-js few weeks ago in Juno's CI. After debugging locally, I figured out the root cause of the issue, not being able to extract the version of a library with an npm command and jq, was related to the fact that for some reason providing `--json` to the npm commands did not simply output the json anymore but also some build information. Before trying to resolve the issue, I bumped npm to check if it was not a potential npm issue and, indeed, bumping to a newer version of npm resolved the issue.
Therefore this PR that ensures the latest version of npm is always used in CI Actions. Likewise, the PR also bumps Node LTS (20) given that we aim to use last version.
Resolves #618.

fix: CI parse error "Invalid numeric literal at line 2, column 2"

---

CHANGELOG.md
packages/ic-management/candid/ic-management.certified.idl.js
packages/ic-management/candid/ic-management.d.ts
packages/ic-management/candid/ic-management.did
packages/ic-management/candid/ic-management.idl.js
packages/ic-management/src/ic-management.canister.spec.ts
packages/ic-management/src/types/ic-management.params.ts

The canisters APIs have been updated.
* Updated the candid interface files for the canisters used in this library.
* Updated the javascript bindings for the latest candid interfaces.

Update Candid Files

---

packages/cketh/README.md
packages/cketh/candid/orchestrator.certified.idl.d.ts
packages/cketh/candid/orchestrator.certified.idl.js
packages/cketh/candid/orchestrator.d.ts
packages/cketh/candid/orchestrator.did
packages/cketh/candid/orchestrator.idl.d.ts
packages/cketh/candid/orchestrator.idl.js
packages/cketh/src/index.ts
packages/cketh/src/minter.canister.ts
packages/cketh/src/orchestrator.canister.spec.ts
packages/cketh/src/orchestrator.canister.ts
packages/cketh/src/types/canister.options.ts
scripts/docs.js
scripts/import-candid

Add the ckEth orchestrator ([source](https://github.com/dfinity/ic/tree/master/rs/ethereum/ledger-suite-orchestrator)) to `@dfinity/ledger-cketh` and expose function `get_orchestrator_info`.
This additional canister is responsible for spinning up Ledger and Index canisters for ckERC20 tokens when (and if) the respective proposals are approved and executed (for example, proposal  [129750](https://nns.ic0.app/proposal/?u=qoctq-giaaa-aaaaa-aaaea-cai&proposal=129750)).
One might want to use this canister to fetch at runtime the list of ledgers and indexes or the list of supported ckERC20 tokens, but most probably, as in Oisy, one might use this feature to set up a job that periodically checks automatically if new tokens were approved and deployed.
- set-up did and idl generation for …

feat: ckEth orchestrator

---

packages/ledger-icp/README.md
packages/ledger-icp/src/ledger.canister.ts

Unlike most libraries of the repo, we were not using the `Canister` abstract class in the ICP `LedgerCanister`. This PR aligns the implementation and will also allow us to use the inherited `caller` utilities in the implementation.
- Extend standard implementation - `class LedgerCanister extends Canister<LedgerService>`

feat: align icp ledger constructor implementation

---

packages/ledger-icrc/src/ledger.canister.spec.ts
packages/ledger-icrc/src/mocks/ledger.mock.ts

Spotted a typo in `tokeMetadataResponseMock`.

chore: mock data naming typo

---

packages/ic-management/candid/ic-management.certified.idl.js
packages/ic-management/candid/ic-management.d.ts
packages/ic-management/candid/ic-management.did
packages/ic-management/candid/ic-management.idl.js
packages/ic-management/src/ic-management.canister.spec.ts
packages/ic-management/src/types/ic-management.params.ts

Updating the `log_visibility` Candid types as provided by the weekly batch (PR #633) requires also adapting the function to `update_settings` accordingly.
- update Candid types as in #633
- add `log_visibility` to mock data
- create new enum `LogVisibility` (same pattern as `InstallCode`)
- extend function `toCanisterSettings` to map the log visibility

feat: update ic-mgmt candid and log_visibility support

---

packages/ic-management/candid/ic-management.did
scripts/import-candid

In #643, we need to download another did file from a repository other than the IC repository. Therefore, we have to use a one more curl command in our `import-candid` script. This PR creates a function for handling such did files in import-candid, and also uses the GitHub API to collect the commit hash and add it as a comment in the generated file.

chore: download did script

---

CHANGELOG.md
packages/ledger-icp/README.md
packages/ledger-icp/src/canisters/ledger/ledger.request.converts.ts
packages/ledger-icp/src/errors/ledger.errors.ts
packages/ledger-icp/src/index.ts
packages/ledger-icp/src/ledger.canister.spec.ts
packages/ledger-icp/src/ledger.canister.ts
packages/ledger-icp/src/mocks/ledger.mock.ts
packages/ledger-icp/src/types/ledger_converters.ts

In the signer standard working group, the common example of usage of the new wallet standards is the ICRC2 approve function. While this function is available in the ledger ICRC library, it has not been exposed so far in the ICP ledger library.
- Add `icrc2Approve` function (following `icrc1Transfer` pattern) to the ICP ledger lib.

feat: icrc2 approve support for icp ledger

---

packages/ledger-icp/src/index.ts

When I added the missing `Icrc2ApproveRequest` interface for the PR I provided recently, I noticed that actually other Icrc types of the `@dfinity/ledger-icp` were not exposed.
- Expose missing types which are using in functions' parameters.

fix: expose icrc1 types in ICP lib

---

CHANGELOG.md
packages/ic-management/README.md
packages/ic-management/src/ic-management.canister.spec.ts
packages/ic-management/src/ic-management.canister.ts
packages/ic-management/src/index.ts
packages/ic-management/src/types/ic-management.params.ts

Deprecate the `getUtxos` functions of the ic-mgmt library. Replaced by similar functions in the new Bitcoin canister (see #644).
- Remove code `bitcoinGetUtxos` and `bitcoinGetUtxosQuery`

feat: remove ic-mgmt getUtxos

---

packages/ckbtc/src/bitcoin.canister.ts

There was a typo in the `import` of the Candid IDL files (copy/paste of "minter" not updated to "bitcoin"). As a result, when using the library IRL, the functions of the actors were actually undefined.
- Import Bitcoin DID IDL files
Before:
After fix:

fix: Bitcoin canister undefined functions

---

packages/cketh/src/utils/minter.utils.spec.ts

I found more test sample data in the IC repo ([here](https://github.com/dfinity/ic/blob/57414764febc827070ccaf9584f2a59c19c52f45/rs/ethereum/cketh/minter/tests/principal_to_bytes_test.js#L5)) to test the `encodePrincipalToEthAddress` utility of ckETH. So, I thought it would be cool to replicate those in ic-js as well.
- Add more test data and expected results in `@dfinity/cketh`.

test: more test data for ckETH encodePrincipalToEthAddress

---

.github/workflows/checks.yml
packages/nns/src/governance.canister.spec.ts

Dependabot makes pull requests from a repo fork. These PRs can't run CI with personal access token.
This means that if formatting changes are committed, CLA will get stuck which is confusing and requires manual intervention anyway.
It's less confusing if we just fail if formatting changes are required in this case, which they usually aren't for dependabot changes.
In `.github/workflows/checks.yml` when we checkout without token, don't try to commit changes back to the PR but fail instead.
See CI:
* Without formatting: https://github.com/dfinity/ic-js/actions/runs/9561929327/job/26357217738?pr=660
* With formatting: https://github.com/dfinity/ic-js/actions/runs/9561952761/job/26357293034?pr=660
Not sure how to test the fork case without first merging this PR.
not necessary

Do not commit changes without token

---

.github/workflows/checks.yml

This PR is analogous to https://github.com/dfinity/gix-components/pull/441.
Previously we checked if a PR came from a fork to determine if we could use the personal access token. But if the PR doesn't come from a fork, this doesn't guarantee that the token is available.
So we should just check for the presence of the token directly.
Instead of checking of the PR is from a fork, check if the secrets.GIX_CREATE_PR_PAT token is non-empty.
Tested in gix-components repo.
not necessary

Check for token instead of fork

---

CHANGELOG.md
packages/ic-management/candid/ic-management.certified.idl.js
packages/ic-management/candid/ic-management.d.ts
packages/ic-management/candid/ic-management.did
packages/ic-management/candid/ic-management.idl.js
packages/ic-management/src/ic-management.canister.spec.ts
packages/ic-management/src/types/ic-management.params.ts

Add support for `wasm_memory_limit` in IC-mgmt.
https://forum.dfinity.org/t/psa-upcoming-wasm-memory-limit-may-break-your-canisters/30766
- Copy did from #659
- Add field, adapt map and test

feat: add support for wasm_memory_limit

---

CHANGELOG.md
packages/nns/src/canisters/governance/response.converters.ts
packages/nns/src/governance_test.canister.spec.ts
packages/nns/src/governance_test.canister.ts

Currently when you use `updateNeuron` on the `GovernanceTestCanister` for testing, there is no way not to change the neuron subaccount in the process while probably you would never want to change the neuron subaccount.
This is because when calling `update_neuron` the full neuron, including `account` (which is the neuron subaccount) must be specified but `nns-js` never returns the neuron subaccount. It only returns the `accountIdentifier` which is derived from the subaccount in a one-way fashion.
The current implementation of using the `accountIdentifier` as the neuron account is wrong and results in the neuron account changing each time `updateNeuron` is used.
So in order not to change the subaccount when calling `update_neuron` (and without changing the API of `nns-js`) we must first …

Fix updateNeuron not to change the neuron subaccount

---

.github/CODEOWNERS

We were requested by PRODSEC to enable Code Owners approval in the branch protections. Before doing so, we should add the NNS team to the CODEOWNERS file; otherwise, PRs will always require Gix team approval. This way, both NNS and Gix can approve PRs.

chore: add NNS team to CODEOWNERS

---

CHANGELOG.md
packages/nns/README.md
packages/nns/candid/governance.certified.idl.js
packages/nns/candid/governance.d.ts
packages/nns/candid/governance.did
packages/nns/candid/governance.idl.js
packages/nns/candid/governance_test.certified.idl.js
packages/nns/candid/governance_test.d.ts
packages/nns/candid/governance_test.did
packages/nns/candid/governance_test.idl.js
packages/nns/src/canisters/governance/request.converters.ts
packages/nns/src/governance.canister.spec.ts
packages/nns/src/governance.canister.ts
packages/nns/src/governance_test.canister.ts

When neurons are disbursed or merged they don't stop existing but become empty neurons.
Those neurons are not displayed in NNS dapp but are always included in the response and filtered out on the client.
This unnecessarily wasteful so an optional parameter is being added which can be used to stop including empty neurons.
The functionality is not yet implemented but the parameter is added already so that we can start passing it.
1. Ran `scripts/import-candid ../../ic`
2. Ran `scripts/compile-idl-js`
3. Reverted all canisters except the governance canisters.
4. Added optional `includeEmptyNeurons` parameter to `listNeurons` and pass it on to the backend. Note that the backend treats absent as `true`.
1. Unit tests added and updated.
2. Tested manually with NNS dapp. Functionality itself …

Add optional includeEmptyNeurons to listNeurons

---

packages/cketh/src/index.ts

The params `Eip1559TransactionPriceParams` type was added to `eip1559TransactionPrice` but, the params themselves have not been made public in PR #666.
- Expose the params to the consumer of the library.

feat: expose types Eip1559TransactionPriceParams

---

packages/cketh/src/index.ts

Randomly noticed another type, `RetrieveErc20Request`, which is used since quite some time in Oisy but, is actually not directly exposed by the ckETH library module.
- Expose `RetrieveErc20Request` in `@dfinity/cketh`
Searched for other potential not exposed types in Oisy, there weren't.

feat: expose candid type RetrieveErc20Request

---

scripts/publish-npm.sh

@frederikrothenberger discovered that the outupt of `npm pack` is different depending on the npm version.
Later versions of `npm` output some commands. Adding `--silent` ensures that the output is a valid JSON without the commands.
* Add `--silent` to `publish-npm.sh`.
Tested manually.

Add --silent to `npm pack`

---

CHANGELOG.md
packages/nns/README.md
packages/nns/candid/old_list_neurons_service.certified.idl.d.ts
packages/nns/candid/old_list_neurons_service.certified.idl.js
packages/nns/src/governance.canister.spec.ts
packages/nns/src/governance.canister.ts
packages/nns/src/types/governance.options.ts

`list_neurons` is broken with the Ledger HW (current version 2.4.9) because it does not accept a `ListNeurons` with the `include_empty_neurons_readable_by_caller` even if the field itself is not set.
The (temporary?) work-around added in this PR is to keep a service which uses an old version of the `ListNeurons` type to use when the field is not set anyway.
1. Add `old_list_neurons_service.certified.idl.js` which just has what's necessary for the `list_neurons` method without `include_empty_neurons_readable_by_caller`.
2. Use this service when calling `list_neurons` with `certified: true` and `include_empty_neurons_readable_by_caller: undefined`.
1. Unit tests added/adapted.
2. Tested manually at https://qsgjb-riaaa-aaaaa-aaaga-cai.dskloet-ingress.devenv.dfinity.network/

Work around list_neuron not working with HW

---

packages/nns/src/canisters/governance/request.converters.spec.ts
packages/nns/src/canisters/governance/request.converters.ts

Fix mapping `Principal` in the Nns `request.converter`.
```
TypeError: this is not a constructor
at fromText (chunk-GURPV5CO.js?v=adf4f374:738:23)
at Array.map (<anonymous>)
at Ui (@dfinity_nns.js?v=7b572303:2288:226)
at er (@dfinity_nns.js?v=7b572303:2330:80)
at cr (@dfinity_nns.js?v=7b572303:2433:115)
at makeProposal (@dfinity_nns.js?v=7b572303:2753:16)
at makeProposal (icp-proposal.api.ts:102:9)
at async submitProposal (proposal.services.ts:108:22)
at async submitProposal (submit.services.ts:432:34)
at async HTMLFormElement.onSubmit (SubmitReview.svelte:45:19)
```
- `Principal.fromText` cannot be used as a function when mapping an array

fix: Nns request converter "this is not a constructor"

---

packages/nns/src/canisters/governance/request.converters.spec.ts

An unexpected import if `describe` slipped in a recent test which lead `npm run test` to prinout following console log to the terminal when running the tests
> TAP version 13
> # Subtest: request.converters
>     # Subtest: should convert MakeProposalRequest to RawManageNeuron
>     ok 1 - should convert MakeProposalRequest to RawManageNeuron
>       ---
>       duration_ms: 0.252709
>       type: 'suite'
>       ...
>     1..1
> ok 1 - request.converters
>   ---
>   duration_ms: 0.772666
>   type: 'suite'
>   ...
- Remove unexpected import of `describe`

chore: fix test reporting

---

CHANGELOG.md
package-lock.json
packages/ckbtc/package.json
packages/cketh/package.json
packages/cmc/package.json
packages/ic-management/package.json
packages/ledger-icp/package.json
packages/ledger-icrc/package.json
packages/nns/package.json
packages/sns/package.json
packages/utils/package.json

Agent-js v1.4.0 allows the removal of 'unsafe-eval' and 'unsafe-inline' in CSPs.
- Bump agent-js v1.4.0.

build: agent-js v1.4.0

---

CHANGELOG.md
packages/utils/README.md
packages/utils/src/utils/asserts.utils.spec.ts
packages/utils/src/utils/asserts.utils.ts

We sometimes have a value of type `T | undefined` but we know it is of type `T` so we use `foo as T` before using it.
It would be safer to use `assertNonNullish` first but this can be tedious because it can't be used inline.
For example, something as simple as:
```
const getToken = (universe) => {
return universe.canisterId == OWN_CANISTER_ID_TEXT ? ICPToken : universe.summary?.token as Token;
};
```
would become
```
const getToken = (universe) => {
if (universe.canisterId == OWN_CANISTER_ID_TEXT) {
return ICPToken;
} else {
assertNonNullish(universe.summary);
return universe.summary.token;
}
};
```
It would be nicer if we could use `assertNonNullish` inline like this:
```
const getToken = (universe) => {
return universe.canisterId == OWN_CANISTER_ID_TEXT ? ICPToken : …
```

asNonNullish like assertNonNullish but returns the value

---

packages/cketh/candid/minter.did
packages/cketh/candid/orchestrator.certified.idl.js
packages/cketh/candid/orchestrator.d.ts
packages/cketh/candid/orchestrator.did
packages/cketh/candid/orchestrator.idl.js
packages/cketh/src/orchestrator.canister.spec.ts

This PR update the ckETH candid files as provided in bot PR #682 and add the new additional candid optional fields to the orchestrator info mock.
- Copy did files from #682.
- Update `orchestratorInfoMock` with `ledger_suite_version` field.

feat: update cketh candid files

---

.github/workflows/checks.yml

This applies the changes from https://github.com/dfinity/snsdemo/pull/380 (in snsdemo) to ic-js.
`EndBug/add-and-commit` requires that the `checkout` action is called with `ref`, when used on a pull request, so it knows which branch to commit to. For some reason this was not required on older versions (7) of EndBug/add-and-commit.
In https://github.com/dfinity/snsdemo/pull/368 I changed to an earlier version of `EndBug/add-and-commit` to avoid having to pass `ref` to the `checkout` action, depending on whether the run is for a PR, to avoid having to have 4 different checkout steps.
I realized now that I only need to pass the token if I plan to make changes, so I can combine the checkout steps and still only have 2 while also using newer versions of `actions/checkout` and …

Combine access token and pull request checks in workflow

---

CHANGELOG.md
packages/nns/README.md
packages/nns/candid/genesis_token.did
packages/nns/candid/governance.certified.idl.js
packages/nns/candid/governance.d.ts
packages/nns/candid/governance.did
packages/nns/candid/governance.idl.js
packages/nns/candid/governance_test.certified.idl.js
packages/nns/candid/governance_test.d.ts
packages/nns/candid/governance_test.did
packages/nns/candid/governance_test.idl.js
packages/nns/candid/sns_wasm.certified.idl.js
packages/nns/candid/sns_wasm.d.ts
packages/nns/candid/sns_wasm.did
packages/nns/candid/sns_wasm.idl.js
packages/nns/src/canisters/governance/request.converters.spec.ts
packages/nns/src/canisters/governance/request.converters.ts
packages/nns/src/canisters/governance/response.converters.ts
packages/nns/src/enums/governance.enums.ts
packages/nns/src/governance.canister.spec.ts
packages/nns/src/governance.canister.ts
packages/nns/src/mocks/governance.mock.ts
packages/nns/src/types/governance_converters.ts

New types in NNS Governance are added which includes new variants which will fail the automatic update. Add converters for request/response involving those variants
1. Ran scripts/import-candid ../../ic and scripts/compile-idl-js.
2. Get rid of everything other than nns changes: `packages/{ckbtc,cketh,cmc,ledger-icp,ledger-icrc,sns,ic-management}`
3. Added conversion for UpdateCanisterSettings, StopOrStartCansiter, SetVisibility and Neuron::visibility
Unit tests
- [ x] Add entry to changelog (if necessary).

Update IC and add conversions for new NNS Governance types

---

packages/ledger-icrc/README.md
packages/ledger-icrc/src/index.canister.spec.ts
packages/ledger-icrc/src/index.canister.ts

For the import token functionality, we need to ensure that the provided by users index canister is correctly associated with the same token and not mistakenly linked to a different ledger canister. To achieve this, we going to use the `ledger_id` API of the index canister, which returns the corresponding ledger canister ID. This PR introduces a function that makes the `ledger_id` request.
- Add getLedgerId function.
- Test for getLedgerId.
- Tested manually in nns-dapp against localhost.
Not necessary.

icrc index getLedgerId

---

CHANGELOG.md
packages/nns/src/enums/governance.enums.ts

Some topics and proposal types were renamed in backend enums to better reflect reality.
To avoid confusion, we make the names here consistent with what is used in the backend code.
1. Copied the values for the `Topic` and `NnsFunction` enums from https://github.com/dfinity/ic/blob/master/rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
2. Removed the prefixes and converted to camelcase.
3. Fix a typo on the reference to the original proto file.
Prepared changes in nns-dapp to make the tests there pass.

Rename Topic and NnsFunction values

---

CHANGELOG.md
packages/utils/README.md
packages/utils/src/utils/arrays.utils.spec.ts
packages/utils/src/utils/arrays.utils.ts

In NNS dapp and Oisy, the displayed fees of the DOGMI SNS are currently incorrectly displayed (see [forum](https://forum.dfinity.org/t/dogmi-sns-transfer-wrong-transfer-fee/34114/1)). This is the result of an incorrect intepretation of the SNS aggregator results which provides the fees encoded in Candid Nat.
- Provide a utility to transform Candid `Nat` to `BigInt`

feat: candid nat to bigint utils

---

CHANGELOG.md
packages/nns/candid/governance.certified.idl.js
packages/nns/candid/governance.d.ts
packages/nns/candid/governance.did
packages/nns/candid/governance.idl.js
packages/nns/candid/governance_test.certified.idl.js
packages/nns/candid/governance_test.d.ts
packages/nns/candid/governance_test.did
packages/nns/candid/governance_test.idl.js
packages/nns/src/canisters/governance/request.converters.spec.ts
packages/nns/src/canisters/governance/request.converters.ts
packages/nns/src/canisters/governance/response.converters.ts
packages/nns/src/canisters/governance/services.ts
packages/nns/src/governance.canister.spec.ts
packages/nns/src/types/governance_converters.ts

NNS Governance now has different types for proposals depending on request/response (related [PR](https://github.com/dfinity/ic/pull/937)), mainly because we want the `InstallCode` proposal type to have full wasm/arg blobs for requests, but hashes of the blobs for responses. We need to update the ic-js according to the new candid interface.
* Run `import_candid` on the latest ic repo and `compile-idl-js`
* Revert everything other than `packages/nns/governance*`
* Use separate types for request/response types related to proposals
* Change converters for `InstallCode` proposals.
Unit tests

Use different request/response types for NNS proposals

---

packages/utils/README.md
packages/utils/src/utils/arrays.utils.spec.ts
packages/utils/src/utils/arrays.utils.ts

When very large Candid Nat numbers are converted to JSON, the array will have more than 2 elements if the number needs more than 64 bits.
Change `candidNumberArrayToBigInt` to allow more than 2 elements in the input array.
Unit test updated.
Also made the following test in Rust (not committed) to make sure the encoding matches:
```
#[test]
fn test_nat() {
let i : candid::Nat = candid::Nat::from_str(
"345763845793847239482739482739482739482739482374928374234928374"
).unwrap();
let s = serde_json::to_string(&i).unwrap();
assert_eq!(s, "[3735344374,914506646,1139096947,3625449072,77510495,1540130702,55083]");
}
```
covered by existing entry

Support more than 2 parts in candidNumberArrayToBigInt

---

scripts/test-vectors/20220923-spawn-neuron.ts
scripts/test-vectors/20221206-increase-dd.ts
scripts/test-vectors/20230110-sns-add-hotkey.ts
scripts/test-vectors/20230118-sns-manage-neuron.ts
scripts/test-vectors/20230118-sns-remove-hotkey.ts
scripts/test-vectors/20230123-icrc-1.ts
scripts/test-vectors/20230125-sns-stake-maturity.ts
scripts/test-vectors/20230321-disburse.ts
scripts/test-vectors/20230511-add-hotkey.ts
scripts/test-vectors/20230511-remove-hotkey.ts
scripts/test-vectors/20230516-send-icp-stake-neuron.ts
scripts/test-vectors/20230516-spawn-neuron.ts
scripts/test-vectors/20230524-icrc-1.ts
scripts/test-vectors/20230712-sns-set-dissolve-timestamp.ts
scripts/test-vectors/20230927-icrc-stake-neuron.ts
scripts/test-vectors/20240730-icrc21.ts
scripts/test-vectors/date-utils.ts
scripts/test-vectors/sns-governance.idl.ts
scripts/test-vectors/sns-ledger.idl.ts

Expiry takes as a constructor argument the time _delta_ in millis. Supplied was the absolute timestamp as a number (but too large to use accurate integer representation).
This fixes the bug.
In addition, the test vector should be called ICRC-21 rather then ICRC-29.

Fix expiry in test-vector

---

CHANGELOG.md
packages/ckbtc/src/bitcoin.canister.spec.ts
packages/ckbtc/src/types/bitcoin.params.ts

As discussed in #701, let's rename `min_confirmations` parameter of `getUtxos` in ckBTC library to `minConfirmations`.
- Parameter and mapping updated accordingly.

feat: ckBTC min_confirmations renamed to minConfirmations

---

packages/ckbtc/src/bitcoin.canister.spec.ts
packages/ckbtc/src/types/bitcoin.params.ts

As discussed in #701, let's rename `min_confirmations` parameter of `getBalance` in ckBTC library to `minConfirmations`.
- Parameter and mapping updated accordingly.

refactor: rename optional param of getBalance

---

CHANGELOG.md
packages/ckbtc/README.md
packages/ckbtc/src/bitcoin.canister.spec.ts
packages/ckbtc/src/bitcoin.canister.ts
packages/ckbtc/src/types/bitcoin.params.ts

As we learned this week, update calls to the Bitcoin canister for `get_balance` and `get_utxos` are only possible when executed from a canister. Therefore, we remove the support for certified calls regarding those endpoints in `@dfinity/ckbtc`. In addition, to make the exception more obvious and to reflects the actual IC API naming, we also add the suffix `Query` to the functions.
https://internetcomputer.org/docs/current/references/ic-interface-spec/#ic-bitcoin_get_utxos
- Remove `certified` option parameter for `getBalance` and `getUtxos`
- Rename `getBalance` and `getUtxos` to `getBalanceQuery` and `getUtxosQuery`
- Add a warning in the documentation
- Update code to use only endpoints `_query`
- Add breaking change in changelog

feat: bitcoin balance and getUtxos support for queries only

---

packages/ledger-icp/src/types/ledger_converters.ts

Add similar doc for Icrc consent message request objects for ICP as for ICRC provided in PR #710.

docs: add some documentation for Icrc21 request objects

---

package.json

The `@dfinity/ledger-icrc` gained weight (just a bit) in #710. Given that we are really precaucious, it makes the test fails.
- Add 1kb to the limit (5 instead of 4)

build: bump size-limit for ledger-icrc

---

CHANGELOG.md
packages/ckbtc/README.md
packages/ckbtc/src/bitcoin.canister.ts
packages/ckbtc/src/types/bitcoin.params.ts

We want to use Regtest for local development in Oisy, but at the moment, this network is not supported in the `BitcoinNetwork`.
* Add `"regtest"` as supported BitcoinNetwork and change the mapper to support the new value.
No new functionality.

Add support for "Regtest" BTC network

---

CHANGELOG.md
packages/nns/candid/genesis_token.did
packages/nns/candid/governance.certified.idl.js
packages/nns/candid/governance.d.ts
packages/nns/candid/governance.did
packages/nns/candid/governance.idl.js
packages/nns/candid/governance_test.certified.idl.js
packages/nns/candid/governance_test.d.ts
packages/nns/candid/governance_test.did
packages/nns/candid/governance_test.idl.js
packages/nns/candid/sns_wasm.did
packages/nns/src/canisters/governance/request.converters.ts
packages/nns/src/types/governance_converters.ts

We want to keep Candid files in ic-js in sync with the IC repo.
This is normally done by automated jobs, but the changes from https://github.com/dfinity/ic/pull/1157 caused tests to break in the [latest automated update](https://github.com/dfinity/ic-js/pull/714).
1. Ran `git pull` in `../../ic`
2. Ran `scripts/import-candid ../../ic`
3. Ran `scripts/compile-idl-js`
4. Removed `OpenSnsTokenSwap`, `SetSnsTokenSwapOpenTimeWindow`, and `SetDefaultFollowees` from `ProposalActionRequest` in `packages/nns/src/canisters/governance/request.converters.ts`.
5. Remove `OpenSnsTokenSwap`, `SetSnsTokenSwapOpenTimeWindow`, and `SetDefaultFollowees` from `Action` in `packages/nns/src/types/governance_converters.ts`.
6. Reverted the changes in packages other than `nns`.
1. Tests pass.
2. Tested that …

Update nns-js Candid Files

---

package-lock.json
packages/ckbtc/package.json
packages/cketh/package.json
packages/cmc/package.json
packages/ic-management/package.json
packages/ledger-icp/package.json
packages/ledger-icrc/package.json
packages/nns/package.json
packages/sns/package.json
packages/utils/package.json

We need fixes for the Signer Standards that have been patched in agent-js v2.1.0.
Bumped to latest 2.1.1 which contains an additional feature unused by ourselves but, maybe for the community.
- `npm run update:agent`

build: bump agent-js v2.1.1

---

CHANGELOG.md
package-lock.json
packages/ckbtc/package.json
packages/cketh/package.json
packages/cmc/package.json
packages/ic-management/package.json
packages/ledger-icp/package.json
packages/ledger-icrc/package.json
packages/nns/package.json
packages/sns/package.json
packages/utils/package.json

Agent-js has been patched because the community has started frequently encountered issues with "ingress expiry time" error messages. To help the community adopt this version, we need to incorporate it into ic-js.
- Currently the ic-js released version use v2.0.0.
- The patch of Agent-js consists of reverting a PR https://github.com/dfinity/agent-js/pull/935. A suggested them to add a description. Meanwhile conversation on [Slack](https://dfinity.slack.com/archives/C020G13AS4F/p1727430471252989).
- `npm run update:agent`

build: patch agent-js v2.1.2

---

CHANGELOG.md
packages/ledger-icrc/src/converters/ledger.converters.spec.ts
packages/ledger-icrc/src/index.ts

Similarly to #716 for ICP, we also need to exposes the ICRC `ledger.converters` for the signer standards library.
- Expose module in `index.ts`

feat: expose icrc ledger.converters

---

CHANGELOG.md
package-lock.json
packages/ckbtc/package.json
packages/cketh/package.json
packages/cmc/package.json
packages/ic-management/package.json
packages/ledger-icp/package.json
packages/ledger-icrc/package.json
packages/nns/package.json
packages/sns/package.json
packages/utils/package.json

We want to allow the consumers to decide what compatible version of agent-js v2 they wish to use. 
We also need to downgrade agent-js in NNS dapp.
https://github.com/dfinity/nns-dapp/pull/5584
- Downgrade to `^2.0.0`

build: downgrade agent-js ^2.0.0

---

packages/nns/candid/old_list_neurons_service.certified.idl.js

I updated the comment to be more accurate when updating the service file in https://github.com/dfinity/ic-js/pull/729 but then forgot to commit these changes.
Improve the comment's accuracy.
N/A
not necessary

Update comment in old_list_neurons_service.certified.idl.js

---

CHANGELOG.md
packages/cmc/README.md
packages/cmc/src/cmc.canister.ts
packages/cmc/src/cmc.options.ts

In PR  #733 I would like to implement a function for the CMC canister that can be called as `query` or `update` call. The `CMCCanister` does not yet support the service binding for query and it's `create` implementation differs from the standards.
That's why this PR update the create function to use the standard utility `createServices`.
- Update `CMCCanister.create` to use the standardized function.
- Deprecate the use of `string` as creation option for consistency reasons.
The tests were already using a `canisterId` set as `Principal`.

feat: CMC create standardized to support query

---

CHANGELOG.md
packages/utils/README.md
packages/utils/src/index.ts
packages/utils/src/types/agent.utils.ts
packages/utils/src/utils/agent.utils.ts

This small refactoring provides a new interface to the user: the one used by the `createAgent` function.

refactor: Extract createAgent parameters and export them

---

scripts/import-candid

The "Update IC" workflow [failed](https://github.com/dfinity/ic-js/actions/runs/11432725940/job/31803642725) because ledger and Index Candid files were moved to a different directory in https://github.com/dfinity/ic/pull/1682
Updated `scripts/import-candid` to copy the ledger candid files from the new path.
Manually ran `./scripts/import-candid ../../ic` to see that it works again.
not necessary

Update ledger candid path

---

CHANGELOG.md
packages/utils/README.md
packages/utils/src/mocks/agent.mock.ts
packages/utils/src/mocks/identity.mock.ts
packages/utils/src/utils/agent.utils.spec.ts
packages/utils/src/utils/agent.utils.ts

It is a simple but useful class to manage multiple HTTP agents associated with identities.
The original scripts were created by @peterpeterparker in the [OISY repo](https://github.com/dfinity/oisy-wallet). This is just a transposition to a re-usable utility.
New `AgentManager` class with:
- `create` method: static constructor.
- `createAgent` method: as the name suggests, it creates a new HTTP but do not cache it.
- `getAgent` method: it fetches the HTTP agent among the cached, and if does note exists, it creates it and cache it.
- `clearAgents` method: clean slate.
I created a few tests for the few usecases.

feat: add Agent Manager to utils package

---

.github/workflows/checks.yml
.github/workflows/next.yml
.github/workflows/publish.yml
.github/workflows/update-ic.yml

During CI checks, we receive [a few warnings](https://github.com/dfinity/ic-js/actions/runs/11493801539) about an old version of `actions/checkout`, so we bump all the current instances to version `actions/checkout@v4`.

ci: Bump checkout action

---

packages/nns/src/governance.canister.spec.ts

I want to refactor the memo to neuron (sub)account calculation to make it available to clients.
But currently the calculated account identifier is not tested.
So before I start changing that code I want to make sure it's tested.
1. Mock the randomly generated memo.
2. Expect specific values in the calls to `transfer` and `manage_neuron`.
PR is test-only. Tests pass.
not necessary

Improve stakeNeuron test coverage

---

CHANGELOG.md
packages/nns/README.md
packages/nns/src/governance.canister.ts
packages/nns/src/utils/neurons.utils.spec.ts
packages/nns/src/utils/neurons.utils.ts

We want to be able to claim a neuron from NNS dapp if the stake process was interrupted after the transfer but before the claim.
For this we need to be able to calculate the neuron account identifier to confirm that a transaction was made for the purpose of staking.
So we would like to reuse the code that calculates the account identifier of the neuron from a memo.
Extract the code to calculate a neuron account identifier from `packages/nns/src/governance.canister.ts` and export it from `packages/nns/src/utils/neurons.utils.ts`.
1. Added some "change detector" unit tests.
2. The original code is covered by test coverage added in https://github.com/dfinity/ic-js/pull/743

Expose memoToNeuronSubaccount and memoToNeuronAccountIdentifier

---

packages/ic-management/src/index.ts
packages/ic-management/src/utils/ic-management.utils.spec.ts
packages/ic-management/src/utils/ic-management.utils.ts

There isn't that a standard to represent `snapshot_id` but, after double checking with the team, it was confirmed that hex representation was already used in DFX (which makes sense). So let's also use such a format for the exposing the snapshots feature in `ic-management`.
- Two utils that convert string to hex. Basically what we already have in `utils` but that way it makes it a bit explicit.

feat: snapshot id encoder and decoder

---

packages/ic-management/README.md
packages/ic-management/src/ic-management.canister.ts

IDE, or at least Webstorm, cannot resolves the definition of Candid services when those function are not destructed.
- Destruct `const {something} = this.service` in ic-mgmt instead of use `this.service.something`
Opening function's definition if destructed:

refactor: destruct candid service in ic-mgmt

---

packages/ic-management/src/ic-management.canister.spec.ts

I noticed that the pattern to assert functions throw errors in ic-mgmt could be improved. While doing so, I noticed that one test was actually asserting an error but, the root cause was due to an incorect function mock
- Use ` await expect(call).rejects.toThrow(error);` to assert for errors - i.e. assert the error is the one mocked
- Fix mock for `provisional_create_canister_with_cycles` error assertion which was mockding `delete_canister` (I guess copy/paste error)

test: improve throw error assertions (and fix one test)

---

CHANGELOG.md
packages/ic-management/README.md
packages/ic-management/src/ic-management.canister.spec.ts
packages/ic-management/src/ic-management.canister.ts
packages/ic-management/src/index.ts
packages/ic-management/src/types/ic-management.params.ts
packages/ic-management/src/utils/ic-management.utils.ts

Add support for [take_canister_snapshot](https://internetcomputer.org/docs/current/references/ic-interface-spec#ic-take_canister_snapshot) to ic-mgmt.
- Implement `takeCanisterSnapshot`
- Create a type `SnapshotId` for the string representation
- Expose related did types in index for the consumer

feat: add takeCanisterSnapshot to ic-mgmt

---

packages/ic-management/src/index.ts

Few DID types should probably be exposed as they are part of the response but defined by Candid.
- Expose few types in `index.ts` of ic-mgmt

feat: expose ic-mgmt types

---

packages/ic-management/src/ic-management.canister.ts
packages/ic-management/src/utils/ic-management.utils.spec.ts
packages/ic-management/src/utils/ic-management.utils.ts

As suggested by @AntonioVentilii in https://github.com/dfinity/ic-js/pull/759#discussion_r1850750053 we can create a function to map the snapshot id because we will reuse similar pattern in #763.
- Extract mapper in utils
- Use mapper in existing implementation

feat: utils to mapSnapshotId

---

packages/ic-management/README.md
packages/ic-management/src/ic-management.canister.spec.ts
packages/ic-management/src/ic-management.canister.ts
packages/ic-management/src/index.ts

We continue with the [list_canister_snapshots](https://internetcomputer.org/docs/current/references/ic-interface-spec#ic-list_canister_snapshots).
- Add `listCanisterSnapshots` to ic-mgmt

feat: list canister snapshots

---

CHANGELOG.md
packages/ic-management/README.md
packages/ic-management/src/ic-management.canister.spec.ts
packages/ic-management/src/ic-management.canister.ts
packages/ic-management/src/index.ts
packages/ic-management/src/types/ic-management.params.ts

The `install_code` arguments for the `mode` have grown in complexity as `Upgrade` now accepts parameters. Therefore, mapping the arguments those not makes that much sense anymore as we would have to declare variant within the types of the library as well. Therefore, this PR replaces the custom params types with the inherited Candid types.
- Replace `InstallMode` with Candid `canister_install_mode`
- Expose candid type
- Remove mapper
- Adapt code

feat: install code arguments inherited from Candid

---

CHANGELOG.md
package-lock.json
package.json
packages/ic-management/package.json

I should have thought to integrate the `InstallMode` breaking change in yesterday release but, it's nice to have it officially out as well.
- Bump ic-mgmt and version tag
- Add overview to CHANGELOG

chore: prepare ic-mgmt release

---

packages/ic-management/README.md
packages/ic-management/src/ic-management.canister.ts
packages/ic-management/src/utils/transform.utils.spec.ts
packages/ic-management/src/utils/transform.utils.ts

It’s literally impossible to test the internal `transform` function used within the static `create` function of the `ic-mgmt` class. However, as we need to address an issue to support WASM installation with chunks (#773), we must extend it. That’s why this PR extracts the function into a module, allowing us to provide tests for the mapping.
We delegate the responsibility of calling the `transform` function to `agent-js`, as it is used internally there and as we are "just" implementing the interface exposed by agent-js. While it is not thoroughly covered at the moment in the agent, I submitted a PR [#954](https://github.com/dfinity/agent-js/pull/954) today that adds at least one assertion. 
No particular entry in CHANGELOG. This is an internal refactoring.
- Extract internal `transform` …

feat: extract ic-mgmt call transform

---

packages/ic-management/src/utils/transform.utils.ts

We prefer functional code and to avoid casting types.
- Review `args` of `transform`
- Make function functional
- Use `nonNullish`
- Remove unnecessary cast

refactor: ic-mgmt transform

---

CHANGELOG.md
packages/nns/candid/genesis_token.did
packages/nns/candid/governance.certified.idl.js
packages/nns/candid/governance.d.ts
packages/nns/candid/governance.did
packages/nns/candid/governance.idl.js
packages/nns/candid/governance_test.certified.idl.js
packages/nns/candid/governance_test.d.ts
packages/nns/candid/governance_test.did
packages/nns/candid/governance_test.idl.js
packages/nns/candid/sns_wasm.did
packages/nns/src/canisters/governance/response.converters.ts
packages/nns/src/types/governance_converters.ts

The automatic update PR (https://github.com/dfinity/ic-js/pull/778) had failures in the `nns` and `cketh` packages.
This PR addresses the update of the `nns` package.
1. Checked out `git checkout release-2024-11-28_03-15-revert-hashes-in-blocks` in my `ic` repo.
2. Ran `scripts/import-candid ../../ic`
3. Ran `scripts/compile-idl-js`
4. Added conversion for `RefreshVotingPower` command.
5. Removed changes outside the `nns` package by running `git checkout packages/{ckbtc,cketh,cmc,ledger-icp,ledger-icrc,sns}`
The issue was caught by the compiler. There is no logic as the body of the `RefreshVotingPower` type is empty. And there are no existing tests for the changed function.

Update Candid files for nns and convert RefreshVotingPower

---

CHANGELOG.md
packages/cmc/README.md
packages/cmc/src/cmc.canister.spec.ts
packages/cmc/src/cmc.canister.ts
packages/cmc/src/index.ts

If a developer want to discover the list of subnet in which they can create canister, they should actually query another endpoint of the CMC in addition of the already exposed `get_default_subnets`.
The `get_subnet_types_to_subnets` provides additional subnets that can be used to create canisters but, are not used by the CMC itself to create canister on a random subnet when not targeted subnet ID is provided.
A bit complicated but, once you know you need both, it's a bit more clear. 
- Expose `get_subnet_types_to_subnets`.
- Expose did type for the response.

feat: add support for get_subnet_types_to_subnets in CMC

---

CHANGELOG.md
packages/nns/candid/genesis_token.did
packages/nns/candid/governance.certified.idl.js
packages/nns/candid/governance.d.ts
packages/nns/candid/governance.did
packages/nns/candid/governance.idl.js
packages/nns/candid/governance_test.certified.idl.js
packages/nns/candid/governance_test.d.ts
packages/nns/candid/governance_test.did
packages/nns/candid/governance_test.idl.js
packages/nns/candid/sns_wasm.did
packages/nns/src/canisters/governance/request.converters.ts
packages/nns/src/canisters/governance/response.converters.spec.ts
packages/nns/src/canisters/governance/response.converters.ts
packages/nns/src/governance.canister.spec.ts
packages/nns/src/mocks/governance.mock.ts
packages/nns/src/types/governance_converters.ts

The [automatic Candid update](https://github.com/dfinity/ic-js/pull/783) failed because of new optional fields because optional fields become required in JavaScript because of the Candid compiler.
This PR addresses just the issues in the nns package.
1. Take the changes from https://github.com/dfinity/ic-js/pull/783 from just the nns package.
2. Add conversion for the new fields that cause compilation problems.
1. Unit tests added.

Update Candid for nns package

---

packages/nns/candid/genesis_token.did
packages/nns/candid/governance.certified.idl.js
packages/nns/candid/governance.d.ts
packages/nns/candid/governance.did
packages/nns/candid/governance.idl.js
packages/nns/candid/governance_test.certified.idl.js
packages/nns/candid/governance_test.d.ts
packages/nns/candid/governance_test.did
packages/nns/candid/governance_test.idl.js
packages/nns/candid/sns_wasm.did

There is missing a field `RefreshVotingPower` that is needed for the nns-dapp periodic confirmation feature. 
- `import-candid ic` to the [latest release](https://dashboard.internetcomputer.org/proposal/134416) `0f35ac817bdf3b44680111fc90ce5d6e3bc79be1`.
- `compile-idl-js`.
- CI pass.
Not necessary.

Upgrade nns candids

---

package-lock.json

This PR originally aims to solely patch the low [security vulnerability in nanoid](https://github.com/advisories/GHSA-mwcw-c2x4-8c55) but, it turns out we did not patched recent minor issue such as `cookie`. So I resolved all audit issue.
cross-spawn  7.0.0 - 7.0.4
Severity: high
Regular Expression Denial of Service (ReDoS) in cross-spawn - https://github.com/advisories/GHSA-3xgq-45jj-v275
fix available via `npm audit fix`
node_modules/cross-spawn
micromatch  <4.0.8
Severity: moderate
Regular Expression Denial of Service (ReDoS) in micromatch - https://github.com/advisories/GHSA-952p-6rrq-rcjv
fix available via `npm audit fix`
node_modules/micromatch
nanoid  4.0.0 - 5.0.8
Infinite loop in nanoid - https://github.com/advisories/GHSA-mwcw-c2x4-8c55
fix available via `npm audit fix` …

fix: audit vulnerabilities (dev dependencies)

---

packages/utils/README.md
packages/utils/src/utils/nullish.utils.ts

I noticed the jsdocs in `nullish.utils` was not yet well formatted.
- Format jsdocs with `@template`, `@param` etc.

docs: format jsdocs for nullish.utils

---

CHANGELOG.md
package-lock.json
packages/utils/README.md
packages/utils/src/utils/nullish.utils.spec.ts
packages/utils/src/utils/nullish.utils.ts

The number of times I've written `!notEmptyString` is slowly becoming ridiculous 😉. Time to create a function for it! 
- Add `isEmptyString` - the opposite of existing `notEmptyString`

feat: add utility `isEmptyString`

---

package-lock.json
package.json
packages/utils/README.md

I implemented few fixes and improvements in `tsdoc-markdown`, notably this evening, which I thinnk have no impacts on `ic-js` but, to follow-up with the version, this PR bumps the library to latest.
There was no breaking changes. I started adopting semver therefore the jump to v1.x.y.

build: bump tsdoc-markdown

---

packages/nns/src/canisters/governance/response.converters.spec.ts
packages/nns/src/canisters/governance/response.converters.ts
packages/nns/src/types/governance_converters.ts

After introducing new neuron properties (`deciding_voting_power` and `potential_voting_power`), the original `voting_power` field has become [obsolete](https://github.com/dfinity/ic/blob/586c57afa7af796185c76c8ff26bc37e813957c2/rs/nns/governance/canister/governance.did#L744-L751). With this PR, we add three new fields to the NeuronInfo: `decidingVotingPower`, `potentialVotingPower`, and a small drive-by addition `votingPowerRefreshedTimestampSeconds`; and mark the original votingPower field as deprecated.
- Added 3 new fields.
- Mark `votingPower` as deprecated.
- Pass.
- Tested manually by utilizing new fields in the NNS Dapp.
Not necessary.

New voting power related fields in NeuronInfo

---

CHANGELOG.md
packages/ledger-icrc/README.md
packages/ledger-icrc/src/types/ledger.responses.ts
packages/ledger-icrc/src/utils/ledger.utils.spec.ts
packages/ledger-icrc/src/utils/ledger.utils.ts

I've been implementing the same mapper repeatedly, and today I needed it in another library (the oisy-wallet-signer). Instead of reimplementing it again, I added a utility to the ledger-icrc library to map the token metadata information from a ledger response provided in form of Candid arrays into a structured record.
- Add utility `mapTokenMetadata`.

feat: icrc map token metadata to record

---

CHANGELOG.md
packages/ledger-icrc/src/index.ts

Spotted a typo in a re-exported did type of the ledger-icrc.
Fundamentaly this is a breaking change but, given it's "just" a TypeScript type and no functional code, I did not listed the change as a "Breaking Change" but as "Fix".

fix: typo in renamed exposed type IcrcTransferVariatError

---

CHANGELOG.md
packages/ledger-icrc/src/index.ts

We are re-exporting the ICRC transfer result error type. We can do the same for approve and transfer from as we might need those two in the OISY wallet signer.

feat: expose did error types in ledger-icrc

---

.github/repo_policies/BOT_APPROVED_FILES
.github/workflows/update-ic.yml

Starting soon, files changed by bots must be listed in `.github/repo_policies/BOT_APPROVED_FILES`.
1. Added Candid related files which are updated weekly by a bot to `.github/repo_policies/BOT_APPROVED_FILES`.
2. Made bot PRs easier to spot in the future by prepending "bot: " to their titles, like we do in nns-dapp.

Add BOT_APPROVED_FILES

---

scripts/import-candid

The old ICRC1 index canister was deleted in https://github.com/dfinity/ic/pull/3286
This caused the automatic candid update job to fail when it tried to download the candid for this canister:
https://github.com/dfinity/ic-js/actions/runs/12626049412/job/35178612469
I think it will be good to keep the canister in `ic-js` for backwards compatibility, at least for a while.
But since the canister code is deleted, the candid definitely won't be changing anymore so we can stop automatically updating it.
Stop updating the candid for the old ICRC1 index canister in `scripts/import-candid`.
Ran the script before and after and saw that it started working again.
not necessary

Stop updating old ICRC1 index canister candid

---

package.json

The size limit setup was missing in #812 for the new zod-schemas lib.

chore: zod lib size-limit setup

---

LICENSE
packages/ckbtc/LICENSE
packages/cketh/LICENSE
packages/cmc/LICENSE
packages/ic-management/LICENSE
packages/ledger-icp/LICENSE
packages/ledger-icrc/LICENSE
packages/nns-proto/LICENSE
packages/nns/LICENSE
packages/sns/LICENSE
packages/utils/LICENSE
packages/zod-schemas/LICENSE

In OISY we were requested to bump the copyright year to 2025 therefore makes sense to do so in ic-js as well.
- Bump 2021 to 2025

chore: bump copyright year to 2025

---

package-lock.json

Accepting all zod v3 library in #812 was not replicated, it seems, in package-lock.json.

chore: zod peer dependencies wildcard v3

---

CHANGELOG.md

Typo. I corrected it manually in the [release](https://github.com/dfinity/ic-js/releases/tag/2025.01.20-1030Z) but, we can also update the CHANGELOG.

docs: typo in changelog in the name of the new lib

---

CHANGELOG.md
packages/sns/candid/sns_governance.certified.idl.js
packages/sns/candid/sns_governance.d.ts
packages/sns/candid/sns_governance.did
packages/sns/candid/sns_governance.idl.js
packages/sns/candid/sns_governance_test.certified.idl.js
packages/sns/candid/sns_governance_test.d.ts
packages/sns/candid/sns_governance_test.did
packages/sns/candid/sns_governance_test.idl.js
packages/sns/candid/sns_root.did
packages/sns/candid/sns_swap.did
packages/sns/src/converters/governance.converters.spec.ts
packages/sns/src/converters/governance.converters.ts
packages/sns/src/types/actions.ts

Candid for the `sns` package can't be updated automatically because of a new field `chunked_canister_wasm` in `UpgradeSnsControlledCanister`.
1. Checked out `release-2025-01-16_16-18-base` in IC repo.
2. Ran `scripts/import-candid ../../ic`.
3. Ran `scripts/compile-idl-js`.
4. Reverted files outside `packages/sns`.
5. Updated types and tests to take into account the new field.
Unit tests updated.

Update candid for sns package

---

CHANGELOG.md
package-lock.json
package.json
packages/ckbtc/package.json
packages/cketh/package.json
packages/cmc/package.json
packages/ic-management/package.json
packages/ledger-icp/package.json
packages/ledger-icrc/package.json
packages/nns/package.json
packages/sns/package.json
packages/utils/package.json

In today's release [2025.01.20-1030Z](https://github.com/dfinity/ic-js/releases/tag/2025.01.20-1030Z) I did not bumped utils. As a result the new utility `fromNullishNullable` is not released. So I think it's cleaner to make a new release which bumps utils and all libs that use it.
- Bump version and update CHANGELOG

chore: prepare new release

---

CHANGELOG.md
packages/sns/candid/sns_governance.certified.idl.js
packages/sns/candid/sns_governance.d.ts
packages/sns/candid/sns_governance.did
packages/sns/candid/sns_governance.idl.js
packages/sns/candid/sns_governance_test.certified.idl.js
packages/sns/candid/sns_governance_test.d.ts
packages/sns/candid/sns_governance_test.did
packages/sns/candid/sns_governance_test.idl.js
packages/sns/candid/sns_root.did
packages/sns/candid/sns_swap.did
packages/sns/src/converters/governance.converters.spec.ts
packages/sns/src/converters/governance.converters.ts
packages/sns/src/types/actions.ts

The automatic [Candid update PR](https://github.com/dfinity/ic-js/pull/826) [failed](https://github.com/dfinity/ic-js/actions/runs/12981563131/job/36200149623?pr=826) because of a new field `automatically_advance_target_version` in `NervousSystemParameters`.
1. Checked out the branch from https://github.com/dfinity/ic-js/pull/826
2. Reverted the changes not in the `sns` package.
3. Fixed the test by supporting `NervousSystemParameters.automatically_advance_target_version`.
Fixed

Update sns Candid

---

packages/nns/README.md
packages/nns/src/governance.canister.ts

As mentioned [here](https://dfinity.slack.com/archives/C0175CHJ0P6/p1738018577231269) and [here](https://forum.dfinity.org/t/listneurons-api-change-empty-neurons/40311),  the default behavior of `include_empty_neurons_readable_by_caller` in `list_neurons` has been changed from `true` to `false`.
- Update comment
- Test should pass as before
Not necessary

docs(governance): update list_neurons default behavior comment

---

CHANGELOG.md
packages/cmc/README.md
packages/cmc/src/cmc.canister.spec.ts
packages/cmc/src/cmc.canister.ts

It has been flagged as a security concern not to use a certified query when reading the ICP to XDR conversion rate. 
One option is to implement certificate validation, but its complexity seems beyond the scope of the security ticket. Therefore, I am exposing a new parameter to make the call an update call instead of a query call.
[SECFIND-421](https://dfinity.atlassian.net/browse/SECFIND-421)
- New `certified` parameter for `getIcpToCyclesConversionRate` to use the `certifiedService`
- Updated existing test to check that `service` is call when `certified: false`
-  Add  new test to check that `certifiedService` is call when `certified: true`
[SECFIND-421]: https://dfinity.atlassian.net/browse/SECFIND-421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1K …

fix(security): expose certified flag for ICP to XDR conversion rate

---

CHANGELOG.md
packages/utils/README.md
packages/utils/src/index.ts
packages/utils/src/utils/base64.utils.spec.ts
packages/utils/src/utils/base64.utils.ts

In today's Juno live session, I was looking to decode an `IcrcAccount` provided by the OISY Wallet Signer to a string using the `owner` and `subaccount`. The `subaccount`, in this case, is provided as a `base64` string, so I needed to convert it to a `Uint8Array`. I could have done this if I had access to a utility within the `@dfinity/oisy-wallet-signer` library. However, this utility is not exposed. 
I considered exposing it in the signer library but later realized that it makes more sense to move it to the `@dfinity/utils` package, as it could be useful for other use cases.
- Copy `base64.utils` from https://github.com/dfinity/oisy-wallet-signer/blob/main/src/utils/base64.utils.ts to ic-js

feat: Base64 string to and from Uint8Array

---

packages/nns/candid/genesis_token.did
packages/nns/candid/governance.certified.idl.js
packages/nns/candid/governance.d.ts
packages/nns/candid/governance.did
packages/nns/candid/governance.idl.js
packages/nns/candid/governance_test.certified.idl.js
packages/nns/candid/governance_test.d.ts
packages/nns/candid/governance_test.did
packages/nns/candid/governance_test.idl.js
packages/nns/candid/sns_wasm.did
packages/nns/src/canisters/governance/request.converters.ts
packages/nns/src/governance.canister.spec.ts
packages/nns/src/mocks/governance.mock.ts

The [automatic Candid update](https://github.com/dfinity/ic-js/pull/834) failed because of new optional fields in `list_neurons`.
This PR addresses just the issues in the nns package.
A follow-up PR will implement pagination for `list_neurons`. At that time, the new fields will be utilized.
- Checkout ic at `fb16293`
- Ran `./scripts/import-candid ../ic` from ic-js root folder 
- Ran `./scripts/compile-idl-js` from ic-js root folder 
- Revert changes not related to the `nns` package
- Fix `fromListNeurons` type with default 
- Updated expectations for tests based on the new API
- Should pass as before

chore: update nns Candid Files 

---

packages/utils/src/utils/agent.utils.spec.ts
packages/utils/src/utils/agent.utils.ts

As per @peterpeterparker 's suggestion, we change the method `getAgent` and `clearAgents` of `AgentManager` class to arrow functions. In this way, they can be used after deconstruction.
Adjusted the tests.

refactor: make methods of AgentManager usable after deconstruction

---

CHANGELOG.md
packages/nns/README.md
packages/nns/candid/genesis_token.did
packages/nns/candid/governance.certified.idl.js
packages/nns/candid/governance.d.ts
packages/nns/candid/governance.did
packages/nns/candid/governance.idl.js
packages/nns/candid/governance_test.certified.idl.js
packages/nns/candid/governance_test.d.ts
packages/nns/candid/governance_test.did
packages/nns/candid/governance_test.idl.js
packages/nns/candid/sns_wasm.did
packages/nns/src/canisters/governance/request.converters.ts
packages/nns/src/governance.canister.spec.ts
packages/nns/src/governance.canister.ts

#837 is currently blocked because a new field in the `list_neurons` requests is breaking our tests. This PR unblocks it by updating the tests and exposing this new parameter.
This PR addresses just the issues in the nns package.
- Checkout ic at `14c8f44`
- Ran `./scripts/import-candid ../ic` from ic-js root folder 
- Ran `./scripts/compile-idl-js` from ic-js root folder 
- Revert changes not related to the `nns` package
- Fix `fromListNeurons` type 
- Exposed `neuron_subaccounts` through `listNeurons`
- Updated expectations for tests based on the new API
- Should pass as before

chore: update nns Candid Files

---

.github/workflows/next.yml

The package `zod-schemas` was missing from the CI that releases the `next` version.

ci: add zod-schemas to next release CI

---

packages/ledger-icp/src/types/ledger_converters.ts

I noticed that the types and params of the jsdocs of `Icrc2ApproveRequest` were not exactly matching the implementation.
- Review types and params js documentation.

docs: review Icrc2ApproveRequest jsdocs types

---

packages/nns/README.md
packages/nns/src/canisters/governance/request.converters.ts
packages/nns/src/governance.canister.spec.ts
packages/nns/src/governance.canister.ts
packages/nns/src/mocks/governance.mock.ts

As presented [here](https://forum.dfinity.org/t/request-for-feedback-on-governance-list-neurons-pagination-api/40362) and changed [here](https://github.com/dfinity/ic/pull/3358), the NNS governance canister will implement pagination for the `list_neurons` endpoint.
Pagination will only activate if the response contains more than 500 neurons. Currently, most of our cases involve requesting non-empty neurons, and we do not have users with such a high number of neurons, so for those users nothing has changed. However, the nns-dapp has a use case, Reporting, where we also request empty neurons. In this case, we have a few hundred users with more than 500 neurons.
Some [insights](https://dfinity.slack.com/archives/C01R76CSJ4R/p1738328033654549?thread_ts=1738243719.968339&cid=C01R76CSJ4R) from …

feat(governance): implement pagination for list_neurons endpoint

---

package-lock.json
package.json

We bump the latest version of size-limit to inherits only esbuild v0.25.0 which contains the patch for the recent [alert](https://github.com/dfinity/ic-js/security/dependabot/15).
- Bump size-limit libs

build: bump size-limit

---

CHANGELOG.md
package.json
packages/sns/README.md
packages/sns/candid/sns_governance.certified.idl.js
packages/sns/candid/sns_governance.d.ts
packages/sns/candid/sns_governance.did
packages/sns/candid/sns_governance.idl.js
packages/sns/candid/sns_governance_test.certified.idl.js
packages/sns/candid/sns_governance_test.d.ts
packages/sns/candid/sns_governance_test.did
packages/sns/candid/sns_governance_test.idl.js
packages/sns/candid/sns_root.did
packages/sns/candid/sns_swap.did
packages/sns/src/converters/governance.converters.spec.ts
packages/sns/src/converters/governance.converters.ts
packages/sns/src/governance.canister.spec.ts
packages/sns/src/governance.canister.ts
packages/sns/src/mocks/governance.mock.ts
packages/sns/src/types/actions.ts
packages/sns/src/types/governance.params.ts

#846 is blocked due to a new field, `topic`, expected by `convertGenericNervousSystemFunction`. 
This PR adds this new field and also exposes a new function, `list_topics`, to retrieve a list of all topics.
- Checkout ic at `2f02a660f6`
- Ran `./scripts/import-candid ../ic` from ic-js root folder 
- Ran `./scripts/compile-idl-js` from ic-js root folder 
- Revert changes not related to the `sns` package
- Exposed `list_topics` 
- Updated expectations for tests based on the new API
- Increased the size of the `sns` package.
- Added new test for the new function `list_topics`

chore: update sns Candid Files

---

packages/sns/candid/sns_governance.certified.idl.js
packages/sns/candid/sns_governance.d.ts
packages/sns/candid/sns_governance.did
packages/sns/candid/sns_governance.idl.js
packages/sns/candid/sns_governance_test.certified.idl.js
packages/sns/candid/sns_governance_test.d.ts
packages/sns/candid/sns_governance_test.did
packages/sns/candid/sns_governance_test.idl.js
packages/sns/candid/sns_root.did
packages/sns/candid/sns_swap.did
packages/sns/src/converters/governance.converters.spec.ts
packages/sns/src/converters/governance.converters.ts
packages/sns/src/types/actions.ts

The SNS Candid types need to be updated to support `SetTopicsForCustomProposals`. One SNS has already created a proposal of this type, causing the proposals page for this SNS to break in NNS-dapp. To fix this issue and minimize risks, we are updating only the SNS-related types.
1. Checkout ic repo to commit 9769228 (from https://github.com/dfinity/ic-js/pull/855/files#diff-3c03137e7f91cc4a673bcd7bec8c3eb37899014f3ba207b135d1c4809d57b892R1)
2. Run `./scripts/import-candid ic`
3. Revert not “sns” folders

Update sns candid files

---

CHANGELOG.md
packages/ledger-icp/src/utils/accounts.utils.spec.ts
packages/ledger-icp/src/utils/accounts.utils.ts

It may be useful to have a specific function that checks if a string is a valid ICP account identifier, without throwing an error. We [use it in OISY](https://github.com/dfinity/oisy-wallet/blob/3264177e8f3bac3a13ac112b10f24cc565a5d1eb/src/frontend/src/lib/utils/account.utils.ts#L5) already.
- Add function that uses `checkAccountId` but does not throw an error.
Added specific tests.

feat: add util to check if a string is a valid account identifier

---

CHANGELOG.md
packages/utils/README.md
packages/utils/src/utils/nullish.utils.ts

It seems coherent that the util `notEmptyString` will define the type of the input as string, in case of positive results.

feat: add type assertion to notEmptyString util

---

CHANGELOG.md
packages/ic-management/candid/ic-management.certified.idl.js
packages/ic-management/candid/ic-management.d.ts
packages/ic-management/candid/ic-management.did
packages/ic-management/candid/ic-management.idl.js
packages/ic-management/src/ic-management.canister.spec.ts
packages/ic-management/src/types/ic-management.params.ts

New fields  `wasm_memory_threshold` and `memory_metrics` have been added to the IC spec (provided in Candid PR #864).
- Update did files as in #864
- Adapt test accordingly
- Add field `wasMemoryThreshold` to parameters

feat: add support for wasm_memory_threshold and  memory_metrics to ic-mgmt

---

package-lock.json
package.json
packages/ckbtc/README.md
packages/cketh/README.md
packages/cmc/README.md
packages/ic-management/README.md
packages/ledger-icp/README.md
packages/ledger-icrc/README.md
packages/nns/README.md
packages/sns/README.md
packages/utils/README.md

I created a new version of tsdoc-markdown ([v1.2.0](https://github.com/peterpeterparker/tsdoc-markdown/releases/tag/v1.2.0) which splits methods and proprerties in two sections: instances and statics.
- Bump library
- Inherit updates of the documentation

chore: bump tsdoc-markdown

---

packages/utils/README.md
packages/utils/src/utils/debounce.utils.ts

I noticed the `debounce` utility was undocumented.
- Provide JSDocs

docs: jsdocs debounce utils

---

CHANGELOG.md
packages/ledger-icrc/README.md
packages/ledger-icrc/src/index-ng.canister.spec.ts
packages/ledger-icrc/src/index-ng.canister.ts
packages/ledger-icrc/src/mocks/ledger.mock.ts

We would like to expose method `status` in class `IcrcIndexNgCanister`.
Included method `status` in `IcrcIndexNgCanister`.
Included test for new method.

feat: add method status to class IcrcIndexNgCanister

---

package.json

The size limit of `@dfinity/utils` is being breached with PR https://github.com/dfinity/ic-js/pull/871 (see [CI results](https://github.com/dfinity/ic-js/actions/runs/14072188427/job/39425223731)).
So we increase the size limit from `5 kb` to `10 kb`.

build: increase size limit of utils package

---

packages/utils/src/services/query.spec.ts
packages/utils/src/services/query.ts

The current implementation of `queryAndUpdate` does not call the `onError` callback in the unlikely scenario when the `update` call is faster than the `query` calls and the latter fails.
However, it is useful to have it called either way, even when the `query` calls fails after the `update` calls.
Move the error callback before the check to see if the `update` calls was already executed.
Test adjusted.

feat: service queryAndUpdate will always call error callback

---

packages/utils/README.md
packages/utils/src/services/query.spec.ts
packages/utils/src/services/query.ts
packages/utils/src/types/query-and-update.params.ts

As discussed in https://github.com/dfinity/ic-js/pull/871#discussion_r2015855642 , with this PR, we aim to modify service util `queryAndUpdate` to have separate error callbacks: one for `query` and one for `update`.
- Modify `queryAndUpdate` logic to call only `onError` for `query` calls and only `onUpdateError` for `update` calls.
- Remove unnecessary `certified` parameter from `onError` function, since it will always be called for `certified: false`
Adapt tests.

feat: separate error callback in queryAndUpdate service

---

CHANGELOG.md
packages/utils/README.md
packages/utils/src/utils/nullish.utils.ts

Just for completion, it would be useful to have a type predicate in util `isEmptyString` that defines the input as either nullish value or empty string.

feat: add type predicate in util isEmptyString

---

packages/utils/README.md
packages/utils/src/services/query.spec.ts
packages/utils/src/services/query.ts
packages/utils/src/types/query-and-update.params.ts

It makes more sense to rename the `onError` parameters of service `queryAndUpdate` to `onQueryError`, since it is called only for non-certified calls (query) after PR https://github.com/dfinity/ic-js/pull/875 .

refactor: rename onError to onQueryError in service queryAndUpdate

---

packages/sns/src/index.ts

Currently, in the NNS-dapp, SNS topic-related types are imported from a long path like:
`import type { Topic } from "@dfinity/sns/dist/candid/sns_governance"`
It would be much cleaner to import them from the root of the SNS package, e.g.:
`import type { SnsTopic } from "@dfinity/sns"`.
- Expose sns topic related types.
- No.
Not necessary.

Expose sns topic types via root index

---

packages/nns/README.md
packages/nns/src/governance.canister.ts
tsconfig.json

The typescript config had become a bit outdated. This PR refreshes it.
- esnext etc in tsconfig
- update governance.canister because implicit any is not disallowed

chore: refresh tsconfig

---

CHANGELOG.md
packages/ledger-icrc/README.md
packages/ledger-icrc/src/converters/index.converters.ts
packages/ledger-icrc/src/index-ng.canister.spec.ts
packages/ledger-icrc/src/index-ng.canister.ts
packages/ledger-icrc/src/types/index-ng.params.ts

We aim to introduce a new method, [listSubaccounts](https://github.com/dfinity/ic/blob/12ade05922581a5c95de05b63456655eacc6e2af/rs/ledger_suite/icrc1/index-ng/src/main.rs#L1056), in the `IcrcIndexNgCanister` class.
- Added the `listSubaccounts` method to the `IcrcIndexNgCanister` class.
- Created tests for the new method.

feat(icrc): add method list subaccounts

---

eslint.config.mjs

Add a comment on why it makes sense to keep `local-rules/use-option-type-wrapper` disabled here.

chore: eslint keep local-rules/use-option-type-wrapper off

---

eslint.config.mjs
packages/nns/src/types/governance_converters.ts
packages/sns/README.md
packages/sns/src/types/governance.params.ts

chore: eslint no-empty-object-type on

---

packages/nns/src/canisters/governance/services.ts

Randomly spotted the usage of a `!` null check which can be replaced by `isNullish` for consistency reasons.

chore: use isNullish in governance service

---

eslint.config.mjs

Add a comment about why we keep `no-relative-parent-imports` off for now.

chore: eslint keep no-relative-parent-imports off

---

eslint.config.mjs
packages/cketh/src/utils/minter.utils.ts
packages/ic-management/src/utils/transform.utils.ts
packages/ledger-icp/src/utils/account_identifier.utils.ts
packages/ledger-icrc/src/utils/ledger.utils.spec.ts
packages/nns/README.md
packages/nns/src/governance.canister.ts
packages/utils/README.md
packages/utils/src/utils/asserts.utils.ts
packages/utils/src/utils/date.utils.spec.ts
packages/utils/src/utils/date.utils.ts
packages/utils/src/utils/debounce.utils.ts
packages/utils/src/utils/json.utils.ts
packages/utils/src/utils/version.utils.ts

- Toggle rule on
- Adapt some internal functions
- Add some exception either for functional reason, to avoid breaking change or simplity if test

chore: eslint prefer-object-params on

---

packages/nns/src/governance.canister.spec.ts

The structure `mockFunction.mockResolvedValue(Promise.resolve(something))` is redundant, since it can be simplified by `mockFunction.mockResolvedValue(something)`.

chore: Remove unnecessary `Promise.resolve` in tests

---

packages/ckbtc/src/bitcoin.canister.spec.ts
packages/cmc/src/cmc.canister.spec.ts
packages/ledger-icp/src/index.canister.spec.ts
packages/ledger-icp/src/ledger.canister.spec.ts
packages/ledger-icrc/src/index-ng.canister.spec.ts
packages/ledger-icrc/src/index.canister.spec.ts
packages/ledger-icrc/src/ledger.canister.spec.ts
packages/nns/src/governance.canister.spec.ts
packages/nns/src/governance_test.canister.spec.ts
packages/sns/src/governance.canister.spec.ts
packages/sns/src/swap.canister.spec.ts

So, in this PR, we first make it so we await all `expect(...).rejects.toThrow()` statements.

chore: Await all rejects promises in tests

---

packages/ckbtc/src/minter.canister.spec.ts
packages/cketh/src/minter.canister.spec.ts
packages/sns/src/governance.canister.spec.ts

We want to migrate from `Jest` to `Vitest`. However, jest is a bit more lax when comparing error object: `Jest` loosely matches, while `Vitest` is more strict in comparing error objects.
To be more specific, we define the correct test values.

refactor: More specific assertion for error tests

---

packages/nns/src/governance.canister.spec.ts

So, in this PR, we first make it so we await all `expect(...).rejects.toThrow()` statements for package `nns`.

chore: Await all rejects promises in tests for `nns` package

---

packages/sns/src/governance.canister.spec.ts

So, in this PR, we first make it so we await all `expect(...).rejects.toThrow()` statements for package `sns`.

chore: Await all rejects promises in tests for `sns` package

---

packages/cketh/src/minter.canister.spec.ts

So, in this PR, we first make it so we await all `expect(...).rejects.toThrow()` statements for package `cketh`.

chore: Await all rejects promises in tests for `cketh` package

---

packages/ledger-icp/src/ledger.canister.spec.ts

So, in this PR, we first make it so we await all `expect(...).rejects.toThrow()` statements for package `ledger-icp`.

chore: Await all rejects promises in tests for `ledger-icp` package

---

packages/nns/src/canisters/governance/response.converters.spec.ts
packages/nns/src/canisters/governance/response.converters.ts

The maturity_disbursements_in_progress field is new, and not all test environments support it yet.
To ensure ic-js works consistently across all environments, this PR makes the field optional.
- Check for `maturity_disbursements_in_progress` existence before reading it.
- Updated.
- Verified locally that the nns-dapp doesn't break against the outdated NNS dapp canister (ic-js returns undefined).
Not necessary.

Optional disbursements in progress

---

packages/ledger-icp/src/mocks/ledger.mock.ts

@ulan discovered that the value use to mock an account identifier in `ledger-icp` for test purpose is actually a transaction ID and not an Account Identifier. Therefore he rightfully suggested to update the mock with a real value.
- Update `mockAccountIdentifier` with a valid account identifier.

test: replace mock account identifier value

---

.github/workflows/next.yml
scripts/build-next
scripts/update-version.mjs

Agent-js v3 has been released in beta (see [forum](https://forum.dfinity.org/t/agent-js-beta-release-v3-0-0-beta-0/50854)).  IMO, it's a really promising release as it (finally) reduces its size.
However, like other developers using our libraries, we can't easily use this `@beta` version without forcing its installation, which isn't very clean.  
That's why I propose we expand support for releasing versions with a similar tag as well - i.e. being able to release `beta` tag in addition to our existing `next` tags. This way we can stick to next for our lifecycle and beta for experiments.
In addition, this can also be useful when upgrading direct dependencies — as I'm planning to do for the Zod schemas.
- Expand GitHub Actions to support and publish a tag from input
- Pass down the tag to …

build: support for releasing beta tags

---

CHANGELOG.md
packages/ledger-icp/README.md
packages/ledger-icp/src/account_identifier.spec.ts
packages/ledger-icp/src/account_identifier.ts

An inconsistency in the ICP `SubAccount` class was reported. Its formatter is returning an `Error` instead of throwing one unlike all other functions of the same module and generally speaking in our codebase.
This is a breaking changes and requires change in NNS dapp.
- Throw error instead of returning one.

feat: throw error instead of returning one on invalid ICP subaccount length

---

packages/nns/src/utils/neurons.utils.ts

> ESLint: This assertion is unnecessary since it does not change the type of the expression. (@typescript-eslint/no-unnecessary-type-assertion)
- Remove unnecessary cast

chore: remove unnecessary cast

---

CHANGELOG.md
package-lock.json
packages/nns/package.json

`@dfinity/nns` has unfortunately a requirement on the `buffer` library, which is really a pity. This is notably used to convert  identifier from and to bytes back and forth. I guess it's historical code of the governance and/or the hardware wallet.
Anyway, on the other end, agent-js removes its dependency to `buffer` in its version v3. Depency which is currently inherited to build the library.
That is why - because I think that improving nns would require a bit of time - I propose to "just" set `buffer` as an explicit dependency of `nns-js`.
- ` npm i buffer --save-peer -w packages/nns`

build: add explicit lib requirement on buffer to nns

---

CHANGELOG.md
packages/ledger-icp/src/index.ts
packages/nns/src/canisters/governance/request.converters.ts
packages/nns/src/canisters/governance/response.converters.ts
packages/nns/src/governance_test.canister.ts
packages/nns/src/index.ts
packages/nns/src/utils/account_identifier.utils.ts

Agent-js v3 will drop the requirement for `buffer`.
Historically, both the NNS governance (protobuf?) and the NNS dapp (hardware wallet) relied on buffer for a few identifier-to-bytes conversions. This dependency was inherited via the agent-js.
Since buffer will be removed, projects will now need to add it explicitly if needed. This is kind of acceptable for nns-js (#963), but a bit unfortunate for ledger-icp.
After reviewing the code, I noticed that only a few legacy methods in ledger-icp actually require buffer. Looking through the DFINITY org, it seems that only the NNS dapp still depends on them. While these methods arguably don’t belong in nns-js (they handle "account identifier"-related logic), moving them there would be a win: it would prevent other dapps using ledger-icp from …

feat: move few account identifier functions from ledger-icp to nns

---

HACKING.md

The package `ledger` does not exist anymore, in favour of `ledger-icrc`. Just for consistency, we update it in `HACKING.md`.
And since we are here, we fix some small typos.

docs: Update ledger package name in HACKING.md

---

packages/ledger-icp/src/account_identifier.spec.ts
packages/utils/src/parser/token.spec.ts
packages/utils/src/utils/agent.utils.spec.ts
packages/utils/src/utils/arrays.utils.spec.ts
packages/utils/src/utils/date.utils.spec.ts

For consistency, we remove unnecessary global Jest imports.

chore: Remove unnecessary Jest globals imports

---

packages/utils/src/utils/version.utils.spec.ts

Since we are going to migrate to Vitest, we receive an error while testing:
```css
→ [Vitest] Unexpected .only modifier. Remove it or pass --allowOnly argument to bypass this error
```
meaning that Vitest blocks `.only` unless we explicitly allow it.
This is a safety feature to prevent accidentally committing focused tests (`it.only`, `describe.only`) which would skip the rest of your suite.
However, the test suite specific for util `smallerVersion` works correctly, so we remove the modifier.

test: remove `.only` modifier for tests of util `smallerVersion`

---

CHANGELOG.md
package-lock.json
packages/nns/package.json

Unfortunately, `buffer` must be bundled within `@dfinity/nns` and cannot be set as a peer dependency as proposed in #963, because the NNS dapp fails at runtime. `esbuild`, which we use to build `ic-js` and which is configured to treat peer dependencies as external resources, appears to require `buffer` to be included; otherwise, it fails when used in the NNS dapp.
Fundamentally, making `buffer` an explicit dependency of `@dfinity/nns` simply reflects how it already behaves—i.e., `buffer` was already included implicitly.
- `npm rm buffer -w packages/nns && npm i buffer -w packages/nns`
Using npm pack locally.
Before:
After:

build: fix buffer bundle method for nns-dapp

---

packages/nns/src/canisters/governance/response.converters.ts
packages/nns/src/governance.canister.spec.ts
packages/nns/src/types/governance_converters.ts

I merged the weekly Candid PR #980 and noticed a new field related to the recent NNS `get_metrics` PR #977. This mapping includes the additional field `spawning_neurons_count`.
For some reasons tests passed in CI in #980 but, actually, when I run the test on `main` now they don't as this field is missing. i.e. we need this PR.
> packages/nns/src/governance.canister.spec.ts:2410:11 - error TS2741: Property 'spawning_neurons_count' is missing in type '{ total_maturity_e8s_equivalent: bigint; not_dissolving_neurons_e8s_buckets: [bigint, number][]; dissolving_neurons_staked_maturity_e8s_equivalent_sum: bigint; garbage_collectable_neurons_count: bigint; ... 36 more ...; seed_neuron_count: bigint; }' but required in type 'GovernanceCachedMetrics'.
>
>2410     const rawMetrics: …

feat: spawning_neurons_count nns metrics

---

vitest.config.ts

We don't watch for test changes in any of our repo (I think), therefore I propose to turn this off for this repo as well.
>   PASS  Waiting for file changes...
>       press h to show help, press q to quit
- `watch: false` in test config

chore: disable vitest watch

---

packages/nns/candid/genesis_token.did
packages/nns/candid/governance.certified.idl.js
packages/nns/candid/governance.d.ts
packages/nns/candid/governance.did
packages/nns/candid/governance.idl.js
packages/nns/candid/governance_test.certified.idl.js
packages/nns/candid/governance_test.d.ts
packages/nns/candid/governance_test.did
packages/nns/candid/governance_test.idl.js
packages/nns/src/canisters/governance/response.converters.ts
packages/nns/src/governance.canister.spec.ts
packages/nns/src/types/governance_converters.ts

The canister APIs have been updated. This PR reverts the changes made in #984, which itself was a reversion of the changes in #980 and #982, due to a breaking change in the NNS canister.
* Updated the candid interface files for the nns package.
* Updated the javascript bindings for the latest candid interfaces.
* Adds new type to mocks and types.

chore: update Candid files

---

package.json
packages/sns/candid/sns_governance.certified.idl.js
packages/sns/candid/sns_governance.d.ts
packages/sns/candid/sns_governance.did
packages/sns/candid/sns_governance.idl.js
packages/sns/candid/sns_governance_test.certified.idl.js
packages/sns/candid/sns_governance_test.d.ts
packages/sns/candid/sns_governance_test.did
packages/sns/candid/sns_governance_test.idl.js
packages/sns/candid/sns_root.did
packages/sns/candid/sns_swap.did

To use SNS metrics from the aggregator consistently, they need to be encoded to match the Candid format. This PR upgrades the SNS types to make them available in the NNS dapp.
- scripts/import-candid (latest master — 5f36668c9b1685ab41f146a7ff15d05f9ba2e245)
- scripts/compile-idl-js.
- increase sns/size-limit
- Should pass, since there is no changes in old logic/types.

Upgrade IC for Sns Metric types

---

packages/ledger-icrc/src/ledger.canister.spec.ts

Small refactoring of the tests for class `IcrcLedgerCanister`:
- Add `describe` statement for methods `metadata`, `transactionFee` and `totalTokensSupply`: even if there is only one test, it's for consistency.
- Put the test `getBlocks` inside its `describe` statement.

refactor: Organize tests of class `IcrcLedgerCanister`

---

CHANGELOG.md
package-lock.json
packages/ckbtc/package.json

Stay up-to-date with the latest improvements in the dependencies of the libraries.
In a follow-up PR we will be able to deprecate the custom type definition because [base58-js](https://github.com/pur3miish/base58-js) since its version 2 ships the types.
- Bump base58-js to 3.0.3

build: bump base58-js

---

CHANGELOG.md
packages/ckbtc/src/base58.d.ts

`base58-js` (bumped in PR #998) is now shipped with its related TypeScript definitions (see v3 [release notes](https://github.com/pur3miish/base58-js/releases/tag/v3.0.0)). Therefore, we do not need custom types anymore.
- Remove custom TS types for base58-js library

feat: remove base58-js custom type declarations

---

CHANGELOG.md
packages/ledger-icp/src/utils/accounts.utils.spec.ts
packages/ledger-icp/src/utils/accounts.utils.ts

On one hand, we generally want to move away from using `Buffer`, on the other, when bumping TypeScript in #1004, the compiler reports issues related to its usage.  
This PR replaces `Buffer` with `Uint8Array` in the `checkAccountId` function of `@dfinity/ledger-icp` to address both concerns.
- Use existing utils and new comparison utils (introduced in #1005) to replace buffer with Uint8Array.
- Improve tests to validate checksum.

feat: replace usage of Buffer with Uint8Array in checkAccountId

---

packages/ledger-icp/README.md
packages/ledger-icp/src/account_identifier.ts

@marc0olo had some questions yesterday evening about the ICP `AccountIdentifier` and `SubAccount`, which lead me to notice the lack of JSDoc comments. While this doesn't answer everything, I’ve added some comments that should help clarify things a little bit hopefully.
- Provide JSDocs for ICP `AccountIdentifier` and `SubAccount`

docs: ICP account identifier and subaccount

---

CHANGELOG.md
packages/ledger-icrc/README.md
packages/ledger-icrc/src/index.ts
packages/ledger-icrc/src/ledger.canister.spec.ts
packages/ledger-icrc/src/ledger.canister.ts
packages/ledger-icrc/src/types/ledger.params.ts

The idea is too expose the `icrc1_supported_standards` and `icrc10_supported_standards` methods (https://github.com/dfinity/ICRC-1/blob/main/standards/ICRC-1/README.md#icrc1_supported_standards) in the IcrcLedgerCanister class.
Added method `getSupportedStandards` in IcrcLedgerCanister.
Added test for the new method.

feat: Add method icrc1/icrc10_supported_standards to class IcrcLedgerCanister

---

package-lock.json
packages/zod-schemas/package.json

There is currently no particular reason to pin `@dfinity/principal` version in zod-schemas because as far as I know `Principal.fromText` always existed. Therefore and also to ease migration, I propose to accept any version of the peer dependency.
- Mark peer dependency as `*`

build: accept any principal lib version in zod-schemas

---

LICENSE
packages/ckbtc/LICENSE
packages/cketh/LICENSE
packages/cmc/LICENSE
packages/ic-management/LICENSE
packages/ledger-icp/LICENSE
packages/ledger-icrc/LICENSE
packages/nns-proto/LICENSE
packages/nns/LICENSE
packages/sns/LICENSE
packages/utils/LICENSE
packages/zod-schemas/LICENSE

This PR removes the modified appendix from the LICENSE file to ensure full compliance with the Apache 2.0 license, which should remain in its original, unmodified form. This change aligns our repositories with standard practices for license documentation.

chore(license): removes modified boilerplate from license file

---

package-lock.json
package.json
packages/nns/package.json
packages/nns/src/utils/account_identifier.utils.ts

Get finally rid of Buffer in the browser. Best day ever for bundle size!
- Remove `buffer` dependency from `@dfinity/nns`
- Replace single usage by a utility of `@dfinity/utils`

feat: remove usage of Buffer from nns-js

---

packages/ledger-icrc/candid/icrc_index-ng.certified.idl.js
packages/ledger-icrc/candid/icrc_index-ng.did
packages/ledger-icrc/candid/icrc_ledger.certified.idl.js
packages/ledger-icrc/candid/icrc_ledger.d.ts
packages/ledger-icrc/candid/icrc_ledger.did
packages/ledger-icrc/candid/icrc_ledger.idl.js
packages/ledger-icrc/src/converters/ledger.converters.spec.ts
packages/ledger-icrc/src/converters/ledger.converters.ts
packages/ledger-icrc/src/ledger.canister.spec.ts
packages/ledger-icrc/src/types/ledger.params.ts

The latest ICRC-21 introduces a breaking changes https://github.com/dfinity/wg-identity-authentication/pull/229 which remove `LineDisplay` and introduce  `FieldsDisplay`.
The change has now been implemented in the ledger suite as provided by PR #1027.
- Copy did and js for the ledger-icp from #1027
- Remove `LineDisplay` and add `FIeldsDisplay`

feat!: ledger-icrc ICRC-21 LineDisplay replaced by FieldsDisplay

---

package-lock.json

There was a bug in AgentJS that impacted the `@dfinity/ic-management` library resolved in https://github.com/dfinity/icp-js-core/releases/tag/v4.0.2.
While the libraries reference any version of AgentJS v3, for the state of the art, I thought we can bump the Agent for the repo.
- Bump latest AgentJS in `package-lock`

build: update agent-js (in lock file only)

---

CHANGELOG.md
packages/utils/README.md
packages/utils/src/utils/json.utils.spec.ts
packages/utils/src/utils/json.utils.ts

While migratign Juno to AgentJS v3 ([PR](https://github.com/junobuild/juno/pull/1940)), one of my test started failing as the assertion `toBeInstanceOf(Principal)` returned false. I assume this happened because the `Principal` instance used in the test was not the same as the object returned through my library. To overcome the issue, I migrated the test to `Principal.isPrincipal`. That's why, I think we should enhance the `jsonReplacer` with same assertion to avoid those kind of issue.
~~I assume none will be affected by the changes, thinking that aside from NNS dapp and Juno there are rare consumers of the `jsonReplacer`, but still, labelled as breaking change because clients which in the past would have serialized principal not instead of will start serializing those as principal, which …

feat: isPrincipal instead of instanceof for json principal

---

packages/ic-management/README.md
packages/ic-management/src/ic-management.canister.ts

The test did not failed in CI when I extracted an interface for snapshots in #1047. However, there was one issue: for take snapshot the snapshot ID is optional mandatory. This was later discovered by running the test on main.
- Redo param optional.

fix: optional snapshot id param

---

packages/ic-management/README.md
packages/ic-management/src/ic-management.canister.ts
packages/ic-management/src/index.ts
packages/ic-management/src/types/ic-management.params.ts
packages/ic-management/src/types/snapshot.params.spec.ts
packages/ic-management/src/types/snapshot.params.ts
packages/ic-management/src/utils/ic-management.utils.ts

This PR makes the main API easier to read - less code and types duplication - and also initialize a new dedicated modules for the params related to snapshot. Useful as we will have to add more types to support download and upload snapshots.
- Init new module `snapshot.params.ts`
- Move snapshot related interface to it
- Create an `OptionSnapshotParams` and use it to type `takeCanisterSnapshot` (instead of using TS utils in the main API)
- Create and use two utilities to map the snapshot params (to avoid code duplication)

refactor: extract snapshot interfaces and mapper utils

---

.github/workflows/checks.yml
.github/workflows/update-ic.yml
CHANGELOG.md
scripts/compile-idl-js

Before migrating to `@icp-sdk/bindgen`, we need to upgrade `didc` and regenerate the types; otherwise, we risk mixing declaration differences during the migration.  
This is especially relevant for the TypeScript definitions of functions, used in e.g. `ledger-icrc`, which were modified in this [Candid PR](https://github.com/dfinity/candid/pull/627).
It's also interesting to upgrade because latest version of `didc` parses the comments to the output files as well.
- Upgrade `didc` to latest version `v0.5.1` published in Candid release [2025-08-04](https://github.com/dfinity/candid/releases/tag/2025-08-04)

chore: upgrade didc v0.5.1

---

packages/ckbtc/candid/bitcoin.did
packages/ckbtc/candid/minter.did
packages/cketh/candid/minter.did
packages/cketh/candid/orchestrator.did
packages/cmc/candid/cmc.did
packages/ic-management/candid/ic-management.did
packages/ledger-icp/candid/index.did
packages/ledger-icp/candid/ledger.did
packages/ledger-icrc/candid/icrc_index-ng.did
packages/ledger-icrc/candid/icrc_index.did
packages/ledger-icrc/candid/icrc_ledger.did
packages/nns/candid/genesis_token.did
packages/nns/candid/governance.did
packages/nns/candid/governance_test.did
packages/nns/candid/sns_wasm.did
packages/sns/candid/sns_governance.did
packages/sns/candid/sns_governance_test.did
packages/sns/candid/sns_root.did
packages/sns/candid/sns_swap.did

Add spaces after generated-comment in DID files as if generated after #1064.
I proceed the change manually because there is already new types in the IC repo which I did not wanted to incoporate.
- Add spaces after comment.

chore: add spaces to did files

---

scripts/import-candid

We should separate the first DID type of the auto-generated comment. On one end, they are not related, on the other, the new declarations generator `@icp-sdk/bindgen` is suppose to ignore the first comment if followed by a space.
- Add an `echo` in `import-candid` script.

chore: generate a space after auto-generated did comment

---

packages/ledger-icrc/candid/icrc_index-ng.d.ts
packages/ledger-icrc/candid/icrc_index.d.ts
packages/ledger-icrc/candid/icrc_ledger.d.ts

You might noticed that a `callback` type isn't typed anymore as `QueryArchiveFn` (a function) but become a `[Principal, string]`. According SDK team this is expected and is the result of this Candid fix [PR](https://github.com/dfinity/candid/pull/627).

feat: generate ledger-icrc candid declarations with didc v0.5.1

---

packages/ledger-icp/candid/index.d.ts
packages/ledger-icp/candid/ledger.d.ts

feat: generate ledger-icp candid declarations with didc v0.5.1

---

packages/cketh/candid/minter.d.ts
packages/cketh/candid/orchestrator.d.ts

feat: generate cketh candid declarations with didc v0.5.1

---

packages/nns/candid/genesis_token.d.ts
packages/nns/candid/governance.d.ts
packages/nns/candid/governance_test.d.ts
packages/nns/candid/sns_wasm.d.ts

feat: generate nns candid declarations with didc v0.5.1

---

packages/ic-management/candid/ic-management.d.ts

feat: generate ic-mgmt candid declarations with didc v0.5.1

---

packages/sns/candid/sns_governance.d.ts
packages/sns/candid/sns_governance_test.d.ts
packages/sns/candid/sns_root.d.ts
packages/sns/candid/sns_swap.d.ts

feat: generate sns candid declarations with didc v0.5.1

---

package.json

In PR #1046 the `ic-management` library overpasses its size limit. For example see this [job](https://github.com/dfinity/ic-js/actions/runs/18118951284/job/51559984088?pr=1046):
```
{
"name": "@dfinity/ic-management",
"passed": false,
"size": 4417,
"sizeLimit": 4000
}
```
For this reason I propose to bump the size limit to 10kB.
- Bump ic-mgmt size-limit.

chore: bump ic-mgmt size-limit

---

packages/ledger-icp/README.md
packages/ledger-icp/src/account_identifier.spec.ts
packages/ledger-icp/src/account_identifier.ts

We want to remove the use of `Buffer`. While testing the integration in NNS-dapp ([PR](https://github.com/dfinity/nns-dapp/pull/7348)), @yhabib noticed that the application was complaining about the missing polyfilled `Buffer`. This is likely because `nns-js` still relies on it for two features.
The updated test case `Invalid AccountIdentifier: expected 32 bytes, got 4.` - i.e. 4 instead 0 - is due to the fact that the utility ignores spaces and the mock in place is "foo bar". An account identifier does not contain spaces, therefore I think it was ok to update the expected result. 
- Replace usage of `Buffer` with `hexStringToUint8Array` from `@dfinity/utils`

feat: replace usage of Buffer in nns-js to convert hex to uint8Array

---

packages/nns/src/canisters/governance/request.converters.ts
packages/nns/src/utils/account_identifier.utils.ts

We want to remove the use of `Buffer`. While testing the integration in NNS-dapp ([PR](https://github.com/dfinity/nns-dapp/pull/7348)), @yhabib noticed that the application was complaining about the missing polyfilled `Buffer`. This is likely because `nns-js` still relies on it for two features.
- Replace usage of `Buffer` with `uint8ArrayToHexString` from `@dfinity/utils`
- Updated also in a comment in the unlikely event we would uncomment it in the future, just to avoid surprises

feat: replace usage of Buffer in nns-js to convert uint8Array to hex

---

packages/nns/candid/genesis_token.did
packages/nns/candid/governance.did
packages/nns/candid/governance_test.did
packages/nns/candid/sns_wasm.certified.idl.js
packages/nns/candid/sns_wasm.d.ts
packages/nns/candid/sns_wasm.did
packages/nns/candid/sns_wasm.idl.js

There is a new field [skip_update_latest_version](https://sourcegraph.com/github.com/dfinity/ic@f21c91f50877772aad7bfd6b31e6fbc4f86935f7/-/blob/rs/nns/sns-wasm/canister/sns-wasm.did?L4) in `AddWasmRequest`, which is required for displaying some NNS proposals.
This new field was introduced [here](https://dashboard.internetcomputer.org/proposal/138826).
- Checkout ic at `ff761f361981cff6a760b7d181f696551878b92a`
- Ran `./scripts/import-candid ../ic` from ic-js root folder 
- Ran `./scripts/compile-idl-js` from ic-js root folder 
- Revert changes not related to the `nns` package
- Should pass as before
- [] Add entry to changelog (if necessary).

chore(did): bump nns candid files

---

CHANGELOG.md
package-lock.json
package.json
packages/ckbtc/package.json
packages/cketh/package.json
packages/cmc/package.json
packages/ic-management/package.json
packages/ledger-icp/package.json
packages/ledger-icrc/package.json
packages/nns/package.json
packages/sns/package.json

We want to release a version that remove Buffer in nns-js and ledger-icp. We also want to release a version before migrating to `@icp-sdk`.
- Tag versions
- Update CHANGELOG with entries and summary

chore: prepare release v78
